chunky/src/java/se/llbit/chunky/renderer/projection/OmniDirectionalStereoProjector.java, chunky/src/java/se/llbit/chunky/renderer/projection/ProjectionMode.java, chunky/src/java/se/llbit/chunky/renderer/scene/Camera.java
This PR adds a new projector for [Omni-directional Stereo][ods-google] pictures and two new projection modes (left and right eye). The resulting two images of a scene can be used to create stereographic 360° VR spheres. :globe_with_meridians:
Requested in #364. I also already signed the CLA. :+1: 
[ods-google]: https://developers.google.com/vr/jump/rendering-ods-content.pdf
Edit: I uploaded a [demo sphere](https://lemaik.github.io/rs-sphere/). Just click on the VR icon on the bottom right of the page. Works great with Google Cardboard.
=> Added a projector for omni-directional stereo

chunky/src/java/se/llbit/chunky/renderer/Postprocess.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
(I hit the enter key before writing a description, sorry!)
I know that there are plugins, but these two new tone mappings seem to be a useful addition to the core, as there already is the _tonemapping operator 1_.
Sometimes, the scene looks pretty grayish with gamma correction and even with the existing tone mapping operator
Gamma correction:
Tone mapping op. 1:
Hable's tonemapping looks really great, it preserves some colors better than the above modes:
And while we're at it, the ACES tone mapping curve aims to give the scenes a more filmic look, although it requires careful adjusting of the sunlight and exposure (my scene looks a little too blueish, but the contrast and color intensity is much better):
By the way, ACES [is the default tonemap in Unreal Engine …
=> Add Hable (Uncharted 2) and ACES filmic tone mapping

chunky/src/java/se/llbit/chunky/ui/WorldChooserController.java, chunky/src/res/se/llbit/chunky/ui/WorldChooser.fxml
Before:
After:
c84b373
If you have many worlds, after clicking "Change World" button you may experience a slight delay. Now it works a little differently. At the moment loading the list of worlds, window looks like this:
That improvement minimizing delay between button click and window showing.
3b3c5f4
=> World chooser improvements (worlds list: resizing, asynchronous loading)

chunky/src/java/se/llbit/chunky/main/Chunky.java
ZipFileSystem doesn't work with symlinks, so they need to be resolved first. Using symlinks is pretty useful during plugin development.
=> Fix loading of symlinked plugins

chunky/src/res/se/llbit/chunky/ui/SceneChooser.fxml
Fix for issue 510, making the TableView in the "Load Scene" dialog grow vertically when the window is resized.
=> Fix for TableView in the "Load Scene" dialog not stretching when resizing window

chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java, chunky/src/java/se/llbit/chunky/chunk/BlockPalette.java, chunky/src/java/se/llbit/chunky/world/Chunk.java, chunky/src/java/se/llbit/util/BitBuffer.java
As of 20w17a, block states are aligned to 8-byte boundaries. This PR fixes chunk loading (but stays compatible with 1.13+ chunks).
=> Support loading chunks that were saved with 20w17a.

launcher/src/se/llbit/chunky/launcher/ChunkyLauncher.java, launcher/src/se/llbit/chunky/launcher/ui/UpdateDialogController.java, lib/src/se/llbit/chunky/launcher/LauncherSettings.java
This fixes issues with failed library downloads if the update site doesn't have trailing slash.
=> Fix library downloads

chunky/src/java/se/llbit/png/PngFileWriter.java, chunky/src/java/se/llbit/tiff/TiffFileWriter.java
Regression introduced by #583, breaks plugins that require the constructors (e.g. the denoiser plugin).
=> Restore previously removed PngFileWriter and TiffFileWriter constructors

chunky/src/java/se/llbit/chunky/entity/PlayerEntity.java
Fixes part of #595. I couldn't for the life of me get Elytra to work. The values to add a model don't make any sense at all. I got Netherite Armor working, though.
=> Add support for netherite armor

chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/resources/OctreeFileFormat.java, chunky/src/java/se/llbit/math/NodeBasedOctree.java, chunky/src/java/se/llbit/math/Octree.java, chunky/src/java/se/llbit/math/PackedOctree.java
This PR adds a new implementation of the octree but also leaves the old one. The implementation is abstracted a bit, allowing the use of a different octree implementation with the same octree.
This new implementation doesn't use Nodes as its internal representation, it uses a big int array to be more memory efficient. Nonetheless it offers the same interface that the old implementation, limiting the need to change code using the octree. (the depth is no longer available but came be replaced by a call to getDepth()).
The idea behind this implementation is to reduce greatly the memory usage of the octree and, hopefully, improving the performance by being more cache friendly (the algorithms are the exact same). I suggest reading the code if you are curious how it works, there are comments …
=> New octree implementation

chunky/src/java/se/llbit/chunky/renderer/RenderWorker.java
Fixes #603 
Fixes #403 
Regarding #403: The second commit fixes what llbit describes in that issue: The calculation of `jobTime` used to include the time that the thread waited for a job so the the sleep time was way too long.
=> Fix delay before rendering

chunky/src/java/se/llbit/math/Octree.java
When adding the fallback mechanism i made a silly error and added error handling to the wrong method. 
As of now, it won't cause any problem as the method that needs error handling isn't called anymore and the the one just check for error that will never happen, but it doesn't make sense and it's better to fix that
=> Fix silly error in octree

chunky/src/java/se/llbit/math/NodeBasedOctree.java, chunky/src/java/se/llbit/math/PackedOctree.java
This PR fixes the bug causing water not to look as expected when using the packed octree
expected result:
result with buggy packed octree:
This being said, i believe this PR needs a bit a discussion before being merged.
As i've explain earlier on discord, this issue does not occur with the node based octree because, when testing if children must be merged, they all are compared against the old node that has just been replaced that prevents the merging from happening because the children, even if they all compare equals don't compare equals to the old node.
I believe this behavior is a bug but i think its only bad consequence is that sometimes nodes are not merged when they could have been, wasting a bit of memory.
The bug that i think is really the cause of the water problem is the fact …
=> Fix water bug in packed octree

chunky/src/java/se/llbit/math/NodeBasedOctree.java, chunky/src/java/se/llbit/math/Octree.java, chunky/src/java/se/llbit/math/PackedOctree.java
In the octree intersection functions, the initialization (moving the ray to the boundary of the octree if it is outside) is done in the first iterations of the traversal loop.
* This refactor changes the initialization to directly intersect the octree's bounding box instead of marching to it in several iterations. It also moves it outside of the loop and into its own function `enterOctree(Ray ray)`. On top of making the code more readable it removes some iterations and some branching in a hot loop (though I saw no noticeable performance improvements).
* Variable declarations were also moved to more appropriate locations instead of having them all at the beginning of the function.
The initialization part could be reduced to a simple `AABB.intersect` ideally, but the `AABB` class has been …
=> Refactor octree intersection

chunky/src/java/se/llbit/chunky/resources/SignTexture.java, chunky/src/java/se/llbit/chunky/resources/texturepack/FontTexture.java, chunky/src/java/se/llbit/chunky/resources/texturepack/JsonFontTextureLoader.java
[Minecraft 1.16-pre7 added new font characters](https://minecraft.gamepedia.com/Java_Edition_1.16_Pre-release_7) that caused loading the JSON font definitions to fail.
This PR adds support for surrogate characters so that the new characters can be loaded and rendered properly:
=> Add support for surrogate characters in the JSON font loader.

chunky/src/java/se/llbit/chunky/block/Vine.java
Fix the bug where water blocks are rendered as full blocks when under a vine
before:
after:
=> Fix water bug under vine

chunky/src/java/se/llbit/chunky/main/Chunky.java
This fixes Chunky not exiting after headless rendering or snapshot creation (`-render` or `-snapshot` CLI options).
Turns out that a call to getRenderController() in headless Chunky creates a new RenderController with a new scene manager, context and worker threads. To solve this, the headless renderer now initializes the `renderController` properly and the snapshot code makes sure not to use the render controller (it doesn't use any of the factories either).
=> Fix Chunky not exiting in headless mode

chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/resources/OctreeFileFormat.java, chunky/src/java/se/llbit/chunky/ui/render/AdvancedTab.java, chunky/src/java/se/llbit/math/BigPackedOctree.java, chunky/src/java/se/llbit/math/NodeBasedOctree.java, chunky/src/java/se/llbit/math/Octree.java, chunky/src/java/se/llbit/math/PackedOctree.java, chunky/src/res/se/llbit/chunky/ui/render/AdvancedTab.fxml, lib/src/se/llbit/chunky/PersistentSettings.java
Here comes another octree implementation.
Work in the same spirit as the packed octree but using several arrays as to not be limited by the maximum size of an array in java as we discussed earlier this week.
I also added a field in the advanced tab to select the implementation to be used (as well as saving the choice in the scene and as a persistent setting) to make it easier to change the implementation (and as i may have ideas for one more implementation with different trade off)
=> Bigpacked octree

chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/math/Octree.java, chunky/src/java/se/llbit/math/PackedOctree.java
There was a bug where, when a scene json file didn't have an octree implementation specified, it used the packed octree instead of using the one specified in persistent settings. This PR fixes that.
I also removed a function that is now useless that I forgot to remove before
=> Use the settings when loading a scene with no octree implementation specified

chunky/src/java/se/llbit/chunky/block/Water.java, chunky/src/java/se/llbit/chunky/model/WaterModel.java, chunky/src/java/se/llbit/chunky/resources/Texture.java, chunky/src/java/se/llbit/chunky/world/ChunkTexture.java
I made some changes to get some free memory usage reduction by flattening some arrays here and there (and removing a copy of the water normal that was loaded twice)
I measured a 100MB memory usage reduction on the scene i tried but it most likely isn't proportional to the scene size as I mostly changed code about the textures (the change on chunk texture could scale with size of the scene)
=> Memory usage reduction

chunky/src/java/se/llbit/chunky/world/ChunkTexture.java
I made a small typo in #631 that make storing chunk texture reading the wrong float (and maybe triggering an IndexOutOfBoundsException), this fixes it
=> Fix error in chunk texture

chunky/src/java/se/llbit/chunky/renderer/scene/PreviewRayTracer.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
Before:
After:
This was caused by trying to enter the water in the octree when the ray already entered the water of the water plane
=> Fix jello water when cause by interaction between water plane and normal water

chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
While stepping into the path tracing code, i saw that a ray had its previous material set as air even though it was in water, so i added a test to set its previous material to water. I don't really understand why but it fixes the issue with underwater emitters not lighting the block around.
Fixes #528 
Render with fix:
=> Fix underwater emitter issue

chunky/src/java/se/llbit/chunky/chunk/BlockPalette.java, chunky/src/java/se/llbit/chunky/renderer/scene/OctreeFinalizer.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/world/Chunk.java, chunky/src/java/se/llbit/math/BigPackedOctree.java, chunky/src/java/se/llbit/math/NodeBasedOctree.java, chunky/src/java/se/llbit/math/Octree.java, chunky/src/java/se/llbit/math/PackedOctree.java
Related to #633 
Finalizing the octree is slow, especially when dealing with very large scene, because for each block we need to take action depending on its neighboring blocks, this means walking down the octree up to 10 times for each block. Walking down the octree is cheap but not free so, given the number of blocks this ends up costing a lot of time.
The idea of this PR is to do some of the computation requiring neighboring blocks when loading a chunk, when accessing blocks is cheaper as they are directly stored in a flat array. Blocks that are on the edge of a chunk don't have all of their neighbors available so those are still processed in the finalization phase as before.
While implementing this i also added the "whatever" type i suggested on discord that helps merging nodes more …
=> Octree finalization optimization

chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/renderer/scene/SynchronousSceneManager.java
Resetting a scene and providing `null` as new name will generate a new name so the scene directory needs to be set _after_ that.
Re https://github.com/llbit/chunky/issues/639#issuecomment-660552895
=> Fix previous scene directory being used after creating a new scene from a selection

chunky/src/java/se/llbit/chunky/renderer/scene/PathTracer.java, chunky/src/java/se/llbit/chunky/ui/render/SkyTab.java
The underwater emitter fix removed the possibility to have underwater fog.
It seemed underwater fog was not supposed to be but was a consequence of a bug. I made underwater fog work by taking into consideration distance traveled underwater the same as distance traveled in the air. If it is deemed to be preferable, we could add a separate configuration for underwater fog and have separate fogs.
I also made the fog slider logarithmic
=> Underwater fog

chunky/src/java/se/llbit/math/Octree.java
This PR adds a new method to octree implementation interface (with a default implementation) that is used in `enterBlock` and `exitWater`. Functionally it changes nothing but it allow octree implementations to implement a different version (more efficient for example, i have an use case for that)
=> Add a new optional method to OctreeImplementation interface

README.md, chunky/src/java/se/llbit/chunky/renderer/scene/Sky.java
This fixes #643 
:information_source: [I made a debug `Vector3` implementation][1] that validates the vector after every change and throws exceptions if a component becomes `NaN` or if the length is 0 (only for `DebugVector3.NonZero`. This might be helpful for debugging similar bugs in the future because we get stacktraces without printf-style debugging even if we can't reproduce the bugs on our own machines.
[1]: https://github.com/leMaik/chunky/commit/cce8e22d2afda58eab8fdae1a933ffda4e1e7aac
=> Fix cloud deadlock bug

chunky/src/java/se/llbit/chunky/world/Chunk.java
Fixes #648.
Seems like tile entities are somehow missing in the affected chunks after conversion of <1.13 worlds to 1.13+ world format. Maybe that tag doesn't get converted if there are no tile entities in the chunk to speed up the "optimisation" process. Some chunks can be loaded and it seems that these are chunks that contain tile entities (e.g. chests) and thus contain the tile entities tag.
=> Fix chunks not being loaded if the entities or tile entities tags are missing

chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/world/Chunk.java
Until now, Chunky made water blocks full-height if there was either a water-filled block or a solid block above it. #619 already fixed water rendering below vines by marking them as non-solid (which was correct because vines aren't solid), but it turns out that it doesn't matter if the block is solid: water never has full height if there's is no water-filled block above it.
Before:
After:
=> Fix water blocks having full height if any solid block is above it.

chunky/src/java/se/llbit/chunky/renderer/scene/Sky.java
This is the other location that ray.n can be set to zero. Seems to be rarer than the previous case which might be why I missed it during testing.
Credits to leMaik for finding this.
=> Fix cloud deadlock bug part 2 (#647)

chunky/src/java/se/llbit/chunky/ui/ChunkyFxController.java, chunky/src/java/se/llbit/chunky/ui/render/GeneralTab.java, chunky/src/res/se/llbit/chunky/ui/Chunky.fxml
Make open scene directory open the directory of the current scene instead of the directory of all scenes. Change labels to make the buttons more clear.
=> Improve the Open Scene Directory buttons

chunky/src/java/se/llbit/chunky/ui/render/SkyTab.java, lib/src/se/llbit/chunky/ui/SliderAdjuster.java
First time coding Java, plus doing it blind...
fogDensity 0.01 is considered light fog & 0.1 heavy. Having a logarithmic slider here was an improvement but I do feel that offering fogDensity between [0.01 - 2] was not optimal.
Changed the fogDensity range to be [0.001 - 1]; covering from very light fog (0.001) > light fog (0.01) > heavy fog (0.1) > very heavy fog (1).
Opted to create setRange2() as to not break dependencies with setRange() and the 0.01 lower limit for logarithmic calculations (seems to work fine with the fogDensity mind you). - I would have used an optional arg here but I wasn't sure the best approach.. so new method?
=> Adjust fogDensity slider to allow for light fog.

chunky/src/java/se/llbit/chunky/map/WorldMapLoader.java, chunky/src/java/se/llbit/chunky/world/Chunk.java
Fixes #651 (for real this time, I tested it with that world) and adds a system property to customize the number of map loader threads (useful for large worlds, i.e. `-Dchunky.mapThreads=32`).
=> Fix corrupted chunk loading

chunky/src/java/se/llbit/chunky/renderer/scene/PreviewRayTracer.java
Is this micro-optimization? Yes! But I actually measured and this optimization makes calculating the sky occlusion two to three times faster. Might not be a lot of time for most scenes but in ChunkyMap, scenes are tiny (128x128 pixels) and this change really makes a difference.
=> Make alpha computation for transparent sky faster.

chunky/src/java/se/llbit/chunky/renderer/EmitterSamplingStrategy.java, chunky/src/java/se/llbit/chunky/renderer/scene/PathTracer.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/ui/render/LightingTab.java, chunky/src/java/se/llbit/math/Grid.java, chunky/src/res/se/llbit/chunky/ui/render/LightingTab.fxml
This PR is what i showed yesterday on discord, i'm making a draft PR to get some feedback if some of you have ideas on how to improve that.
So, what's that?
This adds emitter sampling to the renderer to greatly increase convergence of scene with emitters. The reason usually scenes lit up only by sun and sky converge quickly is because at every intersection, the sun is sampled, adding its contribution to the ray without the need of a ray randomly hitting it. On the other hand emitters are not sampled so to contribute to the ray, we need to randomly hit them and, especially with small emitters like torches, the probability is low.
The idea is then to sample emitter the same way we sample the sun so as to need solely relying on this low probability.
But whereas there is only one sun in the …
=> Emitter sampling

chunky/src/java/se/llbit/chunky/block/Head.java, chunky/src/java/se/llbit/chunky/block/WallHead.java, chunky/src/java/se/llbit/chunky/entity/Entity.java, chunky/src/java/se/llbit/chunky/entity/HeadEntity.java
This PR adds player head blocks with custom skins. The skins are only downloaded once and then cached. The scene file contains the URL for portability.
Fixes #70
=> Player head skins

lib/src/se/llbit/chunky/ui/DoubleAdjuster.java, lib/src/se/llbit/chunky/ui/SliderAdjuster.java
Fixes setting logarithmic sliders to zero not resulting in a value of zero (e.g. for fog).
This bug was caused by overriding only one of the two `setRange` methods. While looking through the code I saw that `min` and `max` are defined twice, resulting in unneeded overrides to update them in the subclass.
Supersedes #666
=> Fix DoubleAdjuster value clamping.

chunky/src/java/se/llbit/math/Grid.java
Fixes the NullPointerException that appeared when saving a scene without loading chunks
=> Allocate grid in constructor to prevent NullPointerException

chunky/src/java/se/llbit/chunky/block/Lectern.java, chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java, chunky/src/java/se/llbit/chunky/entity/Book.java, chunky/src/java/se/llbit/chunky/entity/Lectern.java, chunky/src/java/se/llbit/chunky/resources/Texture.java, chunky/src/java/se/llbit/chunky/resources/TexturePackLoader.java, chunky/src/java/se/llbit/chunky/world/model/CubeModel.java, chunky/src/java/se/llbit/math/DoubleSidedQuad.java, chunky/src/java/se/llbit/math/Quad.java, chunky/src/java/se/llbit/math/primitive/TexturedTriangle.java
This PR adds rendering of books placed on top of a lectern. The book is not yet customizable but provides everything that is needed to render the enchantment table book.
It also fixes triangles always being double-sided, even if they belong to single-sided quads, which causes rendering issues if two quads overlap but have their textures on different sides (e.g. the book cover, the book pages and the campfire flame).
|before|after|
|---|---|
|![image](https://user-images.githubusercontent.com/5544859/90988639-ad155b80-e594-11ea-9afe-0f01554e3e09.png)|![image](https://user-images.githubusercontent.com/5544859/90988667-e221ae00-e594-11ea-9846-fda8e8be8800.png)|
=> Lectern book

chunky/src/java/se/llbit/chunky/block/Head.java, chunky/src/java/se/llbit/chunky/entity/HeadEntity.java, chunky/src/java/se/llbit/chunky/resources/texturepack/TextureLoader.java
Looks like the base64-encoded value isn't always valid json. This changes the code to get the skin url with a regex instead.
Fixes #680
=> Fix downloading custom head skins if the json is invalid

chunky/src/java/se/llbit/chunky/block/EnchantingTable.java, chunky/src/java/se/llbit/chunky/entity/Book.java, chunky/src/java/se/llbit/chunky/entity/Entity.java, chunky/src/java/se/llbit/chunky/entity/Lectern.java, chunky/src/java/se/llbit/chunky/entity/Poseable.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/ui/render/EntitiesTab.java
This PR adds the books on enchantment tables as poseable entities. The opening angle, rotation and the angle of the two single pages can be configured.
It also fixes the rotation of books on lecterns (oversight in a previous PR) and the pose controls in the entities tab being initialized to radians instead of degrees.
Related to #41, closes #72
=> Enchantment table book

chunky/src/java/se/llbit/chunky/main/Chunky.java, chunky/src/java/se/llbit/chunky/renderer/OutputMode.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/ui/ChunkyFxController.java
The _Save current frame_ dialog only allowed saving in the format specified by the scene's _output mode_. This PR allows selecting the format in the save dialog and makes the code more generic.
=> Allow selecting the output format in the save current frame dialog.

chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
Fixes #687 
The layers are supposed to be 1...8 but for whatever reason (maybe conversion from Bedrock worlds?) the value was 0 here. This workaround clamps it to the correct tange.
=> Clamp the snow layers to the correct range.

chunky/src/java/se/llbit/chunky/world/Chunk.java
I always thought that this was a race condition with the map renderer, but the stripes were also in the 3d view. Turns out the chunk format changed in 1.15.
> 1024 entries of biome data. Each number in the array is the biome for a 4x4x4 volume in the chunk. These 4×4×4 volumes are arranged by X, then Z, then Y. That is, the first 4×4 values in the array are for the 16×16 chunk, at Y levels 0–3, the next 4×4 is for Y levels 4–7, etc.
([source](https://minecraft.gamepedia.com/Chunk_format))
Before:
=> Fix biome data extraction for chunks saved with 1.15 or later.

chunky/src/java/se/llbit/chunky/ui/render/EntitiesTab.java
This fixes an issue where the gear would be replaced by an invalid (red/black) texture when removing it, i.e. setting it to an empty string.
=> Fix removing entity gear

chunky/src/java/se/llbit/chunky/block/Lava.java, chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java, chunky/src/java/se/llbit/chunky/block/Water.java, chunky/src/java/se/llbit/chunky/chunk/BlockPalette.java, chunky/src/java/se/llbit/chunky/model/CauldronModel.java, chunky/src/java/se/llbit/chunky/renderer/scene/OctreeFinalizer.java, chunky/src/java/se/llbit/chunky/renderer/scene/PathTracer.java, chunky/src/java/se/llbit/chunky/renderer/scene/PreviewRayTracer.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/renderer/scene/Sky.java, chunky/src/java/se/llbit/chunky/resources/OctreeFileFormat.java, chunky/src/java/se/llbit/math/BigPackedOctree.java, chunky/src/java/se/llbit/math/Octree.java, chunky/src/java/se/llbit/math/PackedOctree.java, chunky/src/java/se/llbit/math/Ray.java, chunky/src/java/se/llbit/math/primitive/TexturedTriangle.java
In Chunky 1.x, data nodes were used to store block data. As of _the flattening_ in Chunky 2, new block palette entries are created for every block variant (= data configuration) so that data nodes are only used for water and lava to store the corner configuration (different water levels at the four corners; only the base level of the water block is stored in the chunk data, not the corner levels).
This RP remove data nodes from the octree and creates new block palette entries for every data/level configuration of water and lava. This reduces the size of the packed octree by 50% and should not have any negative performance impacts.
Also, this fixes the lava level if there isn't a solid block above lava (used to be full block height, but it's only 14/16th ingame).
=> Remove data nodes from the octree

chunky/src/java/se/llbit/chunky/block/Lava.java, chunky/src/java/se/llbit/chunky/block/Water.java, chunky/src/java/se/llbit/chunky/chunk/BlockPalette.java
Regression introduced by #704: Water and lava actually have levels from 0 to 15, where 8-15 are used for falling water and equal (8 + level of non-falling water).
Thanks to @jackjt8 for finding it
=> Fix wrong water and lava level checks.

chunky/src/java/se/llbit/chunky/renderer/scene/PathTracer.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/ui/render/AdvancedTab.java, chunky/src/java/se/llbit/chunky/ui/render/LightingTab.java, chunky/src/java/se/llbit/math/Grid.java, chunky/src/res/se/llbit/chunky/ui/render/AdvancedTab.fxml, lib/src/se/llbit/chunky/PersistentSettings.java
Various improvements regarding emitter sampling that needed to be done:
- Only create the emitter grid when using sampling strategy One or All (when switching to one of those 2, a warning appears to inform that the chunks need to be reloaded. A problem with this is that when changing sampling strategy before loading any chunks, the warning still appears, it would be better if it didn't)
- Add some advanced options to control the size of the grid cell and, as suggested by Ryhida, add an option to prevent usual emitter contribution when using emitter sampling. 
- Change the internal structure used to store the emitter grid to be (hopefully) more memory efficient. This only changes internals, the interface or the format on disk are unchanged so full backward compatibility.
=> Improvements regarding emitter sampling

chunky/src/java/se/llbit/math/PackedOctree.java
Didn't see that during the review of the changes to packed octree but when adding new nodes, we only need to grow by 8 ints now. Without this small change, we were using as much memory as previously but wasting half of it
=> Fix the growth of packed octree

chunky/src/java/se/llbit/chunky/block/Leaves.java, chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java, chunky/src/java/se/llbit/chunky/entity/LilyPadEntity.java, chunky/src/java/se/llbit/chunky/model/LeafModel.java, chunky/src/java/se/llbit/chunky/world/material/LilyPadMaterial.java
In Minecraft, birch and spruce leaves don't take the biome color into account but always have fixed tint colors instead.
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/5544859/97119882-91a10b00-1713-11eb-9ef9-02c18d9ee586.png)|![image](https://user-images.githubusercontent.com/5544859/97119888-99f94600-1713-11eb-87f1-f6c92abc24fb.png)|
|![image](https://user-images.githubusercontent.com/5544859/97119893-a382ae00-1713-11eb-9e73-2e155d516a5a.png)|![image](https://user-images.githubusercontent.com/5544859/97119899-aa112580-1713-11eb-91e8-27c73afa8b99.png)|
=> Fix spruce and birch leaves

chunky/src/java/se/llbit/chunky/world/Region.java
…due to bad file length checks when reading region files.
This also adds more helpful output _if_ loading a chunk actually fails.
=> Fix not being able to load some chunks

chunky/src/java/se/llbit/chunky/resources/Texture.java, chunky/src/java/se/llbit/math/ColorUtil.java
New memory optimization we talked about in discord.
Remove the linear texture stored as a float array and only keep the BitmapImage (where every pixel, 4 components, is stored as an int).
Gamma correction is then done on the fly by using a look up table.
I made some tests to measure the performance impact this has, The difference in time I measured is in the order of 4% in favor of the gamma correction on the fly! But my RAM was pretty much saturated when I did those measurement so they may not be representative of usages where more memory is available.
In term of memory reduction, the size of textures has been divided by 5 (from one int and 4 float per pixel to only one int), for 16*16 textures this means a reduction of about 4MB
=> Don't store the linear texture and gamma correct on the fly

chunky/src/java/se/llbit/math/Grid.java
When using emitter sampling, check that the position at which we want to retrieve emitter is in the grid. Hopefully should fix the bug @jackjt8 encountered
=> Check position is in bound of the grid

chunky/src/java/se/llbit/chunky/renderer/scene/PathTracer.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
When adding the option to prevent normal emitter behavior I somehow forgot to copy it when copying a scene, so basically the option had no effect, silly me. Must have hardcoded stuff during development and not bother to check it was working with the real option... Also change condition to use normal emitter behavior for a direct ray from camera to emitter, else the emitter appears dark
=> Fix the option prevent normal emitters

chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/math/Grid.java
Instead of having an emitter grid that spans the whole octree, the emitter grid is changed to only span as much as is necessary for the emitter in the scene. This should further decrease memory usage of the grid.
=> Change emitter grid to not store useless cells

chunky/src/java/se/llbit/chunky/block/BlockSpec.java, chunky/src/java/se/llbit/util/NbtUtil.java
Chunky can render chunks with broken nbt block data just fine, as long as it's not using it. When saving the octree, _all_ nbt data gets serialized which throws errors for invalid nbt data (literal `Error` instances, so it crashes).
This means that without this fix there are worlds that you can load and render but not save the octree of.
Related to llbit/jo-nbt#2
=> Fix crash when saving the octree of worlds with corrupted block NBT data

chunky/src/java/se/llbit/chunky/ui/ChunkyFxController.java, chunky/src/java/se/llbit/chunky/ui/SceneChooserController.java, chunky/src/java/se/llbit/chunky/ui/UILogReceiver.java, chunky/src/java/se/llbit/chunky/ui/render/GeneralTab.java, chunky/src/java/se/llbit/chunky/ui/render/LightingTab.java, chunky/src/java/se/llbit/fxutil/AlertFactory.java, chunky/src/java/se/llbit/fxutil/Dialogs.java
The UX when enabling emitter sampling was slightly confusing (reload _world_ instead of _chunks_) so here is the proper dialog from the TODO. If the user doesn't reload the chunks, it disables emitter sampling.
=> Emitter sampling reload chunks

chunky/src/java/se/llbit/chunky/entity/ArmorStand.java, chunky/src/java/se/llbit/chunky/entity/HeadEntity.java, chunky/src/java/se/llbit/chunky/entity/PlayerEntity.java
This PR adds support for players and armor stands to wear player heads. It also adds support for invisible armor stands and armor stands without a base plate.
Closes #727 
Implements some of the features from #452
=> Player head helmet and armor stand updates

chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/resources/TextureCache.java, chunky/src/java/se/llbit/chunky/resources/TexturePackLoader.java, chunky/src/java/se/llbit/chunky/ui/ChunkyFxController.java, chunky/src/java/se/llbit/chunky/ui/ResourceLoadOrderEditor.java, chunky/src/res/se/llbit/chunky/ui/Chunky.fxml, lib/src/se/llbit/chunky/PersistentSettings.java
Currently Chunky always loads the latest local Minecraft version by default. This can cause inconsistencies when rendering the very same scene with the very same (user-selected) resource packs on two different machines (e.g. for leather armor textures, which used to be loaded on start and were never reloaded).
This PR adds an option to disable loading from the local Minecraft version. It also makes it so that textures of primitives in the bvh trees (e.g. armor of armorstands or players) get reloaded too by rebuilding the bvh trees after changing the resourcepacks.
Textures are still cached in Chunky though, so even after removing all resourcepacks, most of the previous textures (anything but bvh primitive textures) will still be loaded. In practice one of the resource pack is usually set …
=> Add an option to disable default texture loading and fix some texture bugs

lib/src/se/llbit/chunky/JsonSettings.java
…after changing the settings directory.
Most likely only an issue when using Chunky as a library because it could yield to unexpected behavior if the .chunky directory exists but you don't want to use it.
=> Reset settings to default values if reloading the settings fails

chunky/src/java/se/llbit/chunky/block/Head.java, chunky/src/java/se/llbit/chunky/entity/PlayerEntity.java
The regex didn't match for Alex skins because the object doesn't start with the url but with the model metadata in that case. We can't use JSON parsing though, as older worlds don't use json for the base64-encoded skull data (no quotes around properties, which would fail parsing).
=> Fix skull texture loading errors

chunky/src/java/se/llbit/math/PackedOctree.java
Simple change. Override the `getWithLevel` function. It technically does the same job as the default implementation but by inlining all of the `getRoot`/`isBranch`/`getChild` it improves performance by around 10% to 15% according to measurements.
=> Override getWithLevel in PackedOctree

chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/resources/FloatingPointCompressor.java
Implement the FPC algorithm to compress the render dumps instead of using gzip.
Compression ratio is similar but with higher reading/writing speed (around 10x).
The render dump format is changed. Backward compatibility is kept by trying to read a magic number (to differentiate from an old dump) and if it doesn't match, puting back the bytes so they are present for the gzip stream
=> Change compression method for render dump

chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
Sometimes chunks contain tile entities that have positions outside of the chunk. Probably corrupted chunk data, but there's no need for the chunk loading to fail since the invalid block entities can just be ignored.
=> Fix out of bounds errors when a chunk contains tile entities with invalid positions

chunky/src/java/se/llbit/math/Octree.java
Force the alpha value of opaque blocks to be 1 when using the fast path (no block-specific intersecion).
When going the "fast path" (`localIntersect` false, so only get the ray color because we already know where we hit the block, which is just a cube in this case), textures with transparent parts can cause live-locks under certain (random but reproducible) circumstances.
This PR fixes it but also keeps glass working (by checking the `opaque` property).
=> Fix workers live-locking on transparent textures for opaque blocks without localIntersect

launcher/src/se/llbit/chunky/launcher/ChunkyLauncher.java, launcher/src/se/llbit/chunky/launcher/JavaFxLocator.java
Change the launcher so it tries to locate javafx in some predefined location (if you think of other locations, tell me).
If javafx is found, restart the launcher with javafx, else stop the launcher as usual but with an additional more descriptive error message.
This doesn't like a robust approach to the problem but I don't have a better idea for now. That's wy I would like some feedback/ideas during developpement.
Passing the argument to the invocation of chunky itself still need to be implemented.
Closes #523 
Closes #484
=> Try to locate javafx

chunky/src/java/se/llbit/chunky/block/Head.java
Sometimes the base64-encoded json contains line breaks that were not ignored by the old regex (`.` does not consume linebreaks by default).
> In dotall mode, the expression . matches any character, including a line terminator. By default this expression does not match line terminators.
https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html#DOTALL
=> Fix player head skin download for some heads

chunky/src/java/se/llbit/chunky/world/ChunkPosition.java, chunky/src/java/se/llbit/chunky/world/WorldTexture.java, chunky/src/java/se/llbit/math/Octree.java
`ChunkPosition` is used very frequently (via `WorldTexture`) and thus the object instances are created with a factory method and cached. The factory method, however, was `synchronized`, which made it block all threads but one very often during rendering.
This PR changes it to use a [ConcurrentHashMap](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html), which supports "full concurrency for retrievals and high expected concurrency for updates". That's exactly what we want for an object cache used by all render threads.
On my machine (16 threads) this improves render times by up to 20%. Especially with larger thread counts, the render threads used to spend a lot of time waiting to call the synchronized method (cc @stormboomer).
---
Edit: By also changing …
=> Concurrent chunk position cache

chunky/src/java/se/llbit/chunky/block/Block.java, chunky/src/java/se/llbit/chunky/model/GrassModel.java, chunky/src/java/se/llbit/chunky/model/HopperModel.java, chunky/src/java/se/llbit/chunky/model/StairModel.java
Fix alpha component of the ray color not always being set to 1 after grass, stairs and hopper intersections.
`Block.intersect` should make sure that the ray color's alpha value is 0 only if it didn't hit. I checked all models and found that allmost all of them enforce this. Only grass, stairs and hoppers didn't in all cases. This would result in infinite loops when using resourcepacks with unexpected transparency (which do exist).
=> Fix infinite loops when using transparent textures for grass, stairs and hoppers

chunky/src/java/se/llbit/chunky/ui/render/SkyTab.java, lib/src/se/llbit/chunky/ui/SliderAdjuster.java
Fixes #733 
The issue says that there are setting sliders, which dont go down to zero, but the textbox allows it. 
I noticed there are 2 casses where this happens:
1. When DoubleAdjuster.setRange(min, max, slider_min) is called to set the range. I suppose this is for the logarithmic scaling, slider_min preventing values too close to zero. I fixed this problem, but it was only in one case (fog density). Now, setRange(min, max) will automatically set the minimum for logarithmic scaling (logScaleStart) to  0.01. For slider positions < logScaleStart, the value is set to 0. Also, for values < logScaleStart, the slider position is set to zero.
2. When DoubleAdjuster(setRange(min, max) is called to set the range, with min > 0. In this case,the slider will go down to min, but the textbox can …
=> Sliders to zero

chunky/src/java/se/llbit/chunky/resources/FloatingPointCompressor.java
Fixes #768 
Reading of render dump was broken due to subtle bug with sign extension when converting byte to int.
Good thing this bug was caught in a snapshot, it is quite major. Good news is that it is the reading that was broken, the render dumps being written were correct and will be read correctly with this fix. (but if a dump was written after reading a broken dump, it is overwritten with garbage and definitively lost)
=> Fix corrupted render dump

chunky/src/java/se/llbit/chunky/renderer/scene/PathTracer.java
Fix the bug encountered by TurtleRunsSlow on discord where light was going through stairs. It was not due to having a small space between cuboid of the stairs model but to the fact that collision with the stairs where ignored because the current material was already the stairs
before
after (best render)
=> Fix the light leaking through stairs when using emitter sampling

chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
Turns out the ACES formular we're using [gives linear color out](https://blog.demofox.org/2020/06/06/casual-shadertoy-path-tracing-2-image-improvement-and-glossy-reflections/) so we still need to gamma-correct it.
Left before, right after:
Suddenly, ACES is actually nice, especially if we reduce the saturation a bit (0.5 as suggested in the linked article):
=> Fix ACES tonemapping

chunky/src/java/se/llbit/chunky/renderer/scene/PathTracer.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/ui/render/MaterialsTab.java, chunky/src/java/se/llbit/chunky/world/Material.java, chunky/src/java/se/llbit/math/Ray.java
This adds a new _roughness_ property to `Material`. In the _Materials_ tab, it can be configured with the _Smoothness_ slider, which controls the _perceptual smoothness_, which is then converted to the roughness. Perceptual smoothness feels more linear when working with it and it's also what LabPBR 1.3 uses for roughness maps.
=> Add rough specular reflections

chunky/src/java/se/llbit/chunky/resources/Texture.java, chunky/src/java/se/llbit/fxutil/FxImageUtil.java, chunky/src/java/se/llbit/util/ImageTools.java
Loading skymaps didn't work in headless mode:
```
java.lang.NoClassDefFoundError: javafx/scene/image/PixelFormat
at se.llbit.chunky.world.SkymapTexture.setTexture(SkymapTexture.java:81)
at se.llbit.chunky.resources.Texture.<init>(Texture.java:1004)
at se.llbit.chunky.world.SkymapTexture.<init>(SkymapTexture.java:73)
at se.llbit.chunky.renderer.scene.Sky.loadSkyTexture(Sky.java:697)
at se.llbit.chunky.renderer.scene.Sky.loadSkymap(Sky.java:197)
at se.llbit.chunky.renderer.scene.Sky.loadSkymap(Sky.java:178)
```
Headless mode shouldn't rely on JavaFX (especially since new JDKs don't ship with it).
=> Fix skymaps not loading in headless mode without JavaFX.

launcher/src/se/llbit/chunky/launcher/ChunkyLauncher.java, launcher/src/se/llbit/chunky/launcher/JavaFxLocator.java
Adds double quotes around javafxDir fixing launch issues with directories like `C:\Program Files\AdoptOpenJDK\jdk-11.0.9.11-hotspot\lib`.
And increment the ChunkyLauncher version to `v1.12.1`.
=> Fix module-path if javafxDir contains spaces

chunky/src/java/se/llbit/chunky/resources/BitmapImage.java
The "flipping" methods' local variables were _flipping_ named rotated!!!
`System.arraycopy` of rows in vertical flip would be faster than individually copying each pixel. (Used in bed & chest texturing)
=> BitmapImage Nameing & Array Copy Fix

chunky/src/java/se/llbit/math/Octree.java
I tried to optimize a bit octree traversal, unfortunately some of the things I tried didn't give good result but here are some changes that seem to have a positive impact.
Basically the idea is to optimize the the computation for intersection ray/axis-aligned plane (and a computation of intersection ray-axis-aligned-box is made of 6 such computations). This is done by caching the coefficient of the computation such as the computation consist only in a multiplication and an addition. (division being substantially more expensive than multiplication or addition).
In addition, to avoid having to update those coefficient after each box test, I don't update the origin of the ray until it is needed (before returning from the function or before inking another function that expects the origin of …
=> Precompute coefficient for intersection computation

chunky/src/java/se/llbit/math/Octree.java, chunky/src/java/se/llbit/math/PackedOctree.java
Javadoc'd all methods in PackedOctree with more information and explanation of how it works, so that it will be easier for the next reader to understand. Also updated a few things that were out of date (such as 2 ints per node in a few comments).
Also touched the methods set and storeNode and getNodeIndex in minor ways (others may have had minor refactors).
=> PackedOctree Javadoc

chunky/src/java/se/llbit/chunky/entity/ArmorStand.java, chunky/src/java/se/llbit/chunky/entity/PlayerEntity.java, chunky/src/java/se/llbit/chunky/entity/SkullEntity.java
This PR brings back support for players and armor stands wearing (wither) skeleton, creeper, zombie and player heads. It also adds support for carved pumpkins and dragon heads.
=> Add carved pumpkin and dragon head skulls, fix wearing other skulls

chunky/src/java/se/llbit/chunky/entity/BeaconBeam.java, chunky/src/java/se/llbit/chunky/entity/Entity.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/ui/render/EntitiesTab.java, chunky/src/java/se/llbit/chunky/world/ExtraMaterials.java, chunky/src/java/se/llbit/chunky/world/material/BeaconBeamMaterial.java
This is a big one compared to what I normally do. This PR includes changes to Beacon Beams including allowing rotation, saving and loading custom colors, and loading colors from the octree.
I've removed the beacon_beam material from the Materials Tab and put that functionality into the Entities Tab to enable the user to change those properties for any beam segment along with the color.
Related to #41
=> Beam upgrades

chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/util/ZipExport.java
Fixes #800 
Keeping `.foliage` and `.grass` in the list of extensions so that exporting old scenes still works.
=> Include emittergrid files in scene exports. Ignore missing files.

chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
Fixes #775, which is a regression introduced in #638
=> Fix water level information being dropped on chunk borders.

chunky/src/java/se/llbit/chunky/renderer/scene/OctreeFinalizer.java
This fixes a regression that I probably introduced in #809. Cross-chunk water still works, so #775 is still fixed.
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/5544859/107154399-0c183280-6973-11eb-96ea-9f6bbc8e8c8e.png)|![image](https://user-images.githubusercontent.com/5544859/107154402-10dce680-6973-11eb-8d92-6ebe414121ab.png)|
=> Fix water water blocks with water above them on chunk borders.

chunky/src/java/se/llbit/chunky/chunk/BlockPalette.java, chunky/src/java/se/llbit/chunky/main/Chunky.java, chunky/src/java/se/llbit/chunky/plugin/API.java, chunky/src/java/se/llbit/chunky/plugin/PluginApi.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/math/BVH.java, chunky/src/java/se/llbit/math/BigPackedOctree.java, chunky/src/java/se/llbit/math/Octree.java, chunky/src/java/se/llbit/math/PackedOctree.java, chunky/src/java/se/llbit/math/primitive/TexturedTriangle.java
This should cover most of the things that are required to hack on a new renderer through a plugin.
- Added a setter to `Chunky.java` for changing the `RendererFactory`
- Added accessors for both the world and water octree in `Scene.java`
- Added a getter for the block palette list in `BlockPalette.java`
- Added a getter for the octree implementation and made `treeData` public in `PackedOctree.java` and `BigPackedOctree.java`
- Made the classes in `BVH.java` public and added an accessor for the root node
=> Added accessors/made things public

chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/ui/render/GeneralTab.java, chunky/src/java/se/llbit/chunky/world/Chunk.java, chunky/src/java/se/llbit/chunky/world/World.java
initial support for tall chunks, in my testing it works as expected
Currently I'm setting `GeneralTab#yMin` and `GeneralTab#yMax` bounds to `-64` to `320` for all worlds. If you want this to change per-world, scene would probably need the `GeneralTab` instance passed to it on `Scene#loadChunks` or something
Also a sneaky bug fix in `Chunk@290`, preventing negative section positions
=> add support for 21w06a tall chunks

chunky/src/java/se/llbit/math/Ray.java, chunky/src/java/se/llbit/util/RingBuffer.java
No noticeable speed cost of increased precision, while reducing rays from hitting the "seams" between blocks, or leaking through diagonals. (Not a true fix, but reduces the problem by ~99%.) These seams are really only noticeable if you zoom in to the edge of a block now, and leaked rays are are fewer and would make much less of an impact (1/100 as many as the few that go through now should make them nigh invisible).
(And while I'm at this super short PR, may as well suppress the only warning, which due to how it is currently used, will never cause crash.)
---
Example of seams (zoomed in to the corner of a grass block):
And if offset variable is increased to unreasonably large values, it shows the same artifact on a larger scale (I think this is 0.1 instead of 0.0001):
This is also …
=> Increase Ray Precision

chunky/src/java/se/llbit/chunky/renderer/scene/NishitaSky.java, chunky/src/java/se/llbit/chunky/renderer/scene/Sky.java, chunky/src/java/se/llbit/chunky/renderer/scene/SkyCache.java, chunky/src/java/se/llbit/math/ColorUtil.java
More aggressive sky cache synchronization, fixed black regions in the sky, fixed Nishita horizon offset. Sun is now drawn if `Draw Sun` is enabled but `Enable Sunlight` is disabled.
=> Sky cache bug fixes.

chunky/src/java/se/llbit/chunky/main/Chunky.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/renderer/scene/SkyCache.java, chunky/src/java/se/llbit/chunky/ui/ChunkMap.java
- Added a common thread pool that is accessible through `Chunky.getCommonThreads()`
- Modified existing methods to use this.
- Modified `ChunkMap.drawViewBounds` to wait for scene synchronization on a separate thread (if it is already waiting, subsequent requests do not create new jobs and instead are ignored).
- This fixes #415
=> Fixed freeze on load and added common thread pool.

chunky/src/java/se/llbit/chunky/main/Chunky.java, chunky/src/java/se/llbit/chunky/ui/ChunkMap.java
Currently only methods that are associated with loading chunks are ratelimited. I felt like 3 fps was decent just to show progress without giving the impression that Chunky has crashed, however larger values shouldn't have too big of a performance impact.
Also while I was here I cleaned up some code from my previous pull to just use a `volatile boolean` instead of an `AtomicBoolean`.
=> Ratelimit for javafx refresh when loading chunks

chunky/src/java/se/llbit/chunky/renderer/scene/PreethamSky.java, chunky/src/java/se/llbit/chunky/renderer/scene/Sky.java
This fixes #840 by clamping the sky's internal sun position to be always above the horizon and follow the sun properly when above the horizon.
The `SkyCache` is now properly set when loading a scene (previously it would always be in `PreethamSky` until the `Sky&fog` menu is opened).
=> Fixed Preetham sky rendering bug and sky not being set properly when loading a scene.

chunky/src/java/se/llbit/chunky/chunk/BlockPalette.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
This alternates between two `ChunkData` objects, decompressing the next while the current one is being added to the octree
=> Async chunk load & decomp

chunky/src/java/se/llbit/chunky/map/WorldMapLoader.java, chunky/src/java/se/llbit/chunky/world/WorldTexture.java, chunky/src/java/se/llbit/math/Octree.java, chunky/src/java/se/llbit/math/PackedOctree.java
Some random optimisations I saw looking through the codebase
In my testing outside of the chunky environment (in a similar use-case), there is so much noise in results inside chunky that it's probably unreasonable to draw any conclusions from such small tweaks
The `Pair` implementation is ~9% faster
The `HashMap` implementation is ~7% faster
=> Minor optimisations 2

chunky/src/java/se/llbit/chunky/main/SceneHelper.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/ui/SceneChooserController.java
… if the scene description file doesn't exist. Also show them in the scene chooser dialog.
This should make scenes that fail to save not just disappear anymore. Fixes #829
=> Automatically load backup scene description files

chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
Fixes #839
Should also fix #801; If you have the time, I would appreciate if you could verify, @jackjt8 :upside_down_face:
=> Fix octree shifting by storing yMin and yMax in the scene file.

chunky/src/java/se/llbit/chunky/ui/RenderCanvasFx.java
When the view window and canvas sizes aren't a good ratio, there are aliasing artifacts. (Image works best fullscreen, notice the repeated grid-like aliasing and smeared pixels).
This fixes it by rounding the scale ratio down to the nearest 12.5% (1/8) which reduces artifacts while still allowing a reasonable range in scales.
=> Reduce aliasing artifacts from fit-to-screen.

chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
Previously when chunk loading times out, `System.out.println(ignored.getCause().getMessage());` is called. However, `ignored.getCause()` returns null for timeout exceptions. I changed it to be more clear in logging and to use the `Log` utility instead of printing it to `stdout`. This should fix #853.
=> Fix null pointer exception when chunk loading times out.

chunky/src/java/se/llbit/chunky/block/Water.java, chunky/src/java/se/llbit/chunky/renderer/scene/PreviewRayTracer.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/ui/render/WaterTab.java, chunky/src/res/se/llbit/chunky/ui/render/WaterTab.fxml, lib/src/se/llbit/chunky/PersistentSettings.java, lib/src/se/llbit/chunky/ui/SliderAdjuster.java
- fixes #854
- unify naming of water world mode
- rework config for the water world mode feature
- allow any water plane height (as a double)
- use slider for the water height
- add checkbox for default minecraft water height offset (-0.125 below full block)
- fallback for older scene files
- remove water plane height from persistent settings
- improve preview chunk grid (blue if submerged, darker grid for chunks in octree)
=> Improved water world mode

chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
Setting the octree last serialization timestamp before the file being written to closed was causing issues with the timestamp being a couple of milliseconds behind. Now, the timestamp is only set after the file is closed if saving completed without error. This fixes #844.
=> Fix unnecessary octree resaving.

chunky/src/java/se/llbit/chunky/entity/SignEntity.java, chunky/src/java/se/llbit/chunky/resources/BinaryBitmapImage.java, chunky/src/java/se/llbit/chunky/resources/PalettizedBitmapImage.java, chunky/src/java/se/llbit/chunky/resources/SignTexture.java
The way SignTexture works is it has 2 textures, one for the background, shared with all the other signs of the same material, and one texture for the text, unique per sign.
The text texture ends up consuming a lot of memory so I changed the way it is stored, instead of using a 32 bpp bitmap, I'm using a 4 bpp bitmap because the color of sign text is already limited to 16 choices. As I also need to represent transparency, I use an additional 1 bpp bitmap that acts as a mask. So in the end, I am using 5 bits per pixels instead of the 32 initially, dividing by a lit more than 6 the memory usage of those texture.
As an additional optimization, sign that don't contain any text don't have a text texture at all, leading to more savings. This is especially good as sign are often use without text …
=> Reduce memory usage of sign texture

chunky/src/java/se/llbit/math/primitive/TexturedTriangle.java
While I'm at it, here is another memory saving PR.
I inline the uv coordinate of the vertices of the triangle, this saves 72 byte per triangle (24 for each point: 8bytes from the pointer and 16 bytes from the `Vector2` header).
For entity heavy scene, that's MB worth of memory: for 1 region of greenfield, I had 300k entities, reducing memory by 21MB.
(If only java had value types already...)
=> Inline uv coordinate of vertices of texture triangles

launcher/src/se/llbit/chunky/launcher/JavaFxLocator.java
The double escaping seems to be required only on Windows but it breaks the launcher e.g. on Ubuntu 20.04. This fix fixes it for Ubuntu 20.04 so that it works out of the box again.
Not yet verified on Windows…
=> Fix the javafx locator on systems other than Windows.

chunky/src/java/se/llbit/chunky/renderer/RenderManager.java, chunky/src/java/se/llbit/chunky/renderer/renderdump/DumpFormat.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/renderer/scene/SynchronousSceneManager.java
- Merging through the GUI makes more sense (you can now merge even if the render is not started, merged frame will be displayed after merging is finished).
- Fixed merging task tracker lag (Apparently `Platform.runLater` does not being spammed with millions of tasks`).
- Improved CLI merging speed.
=> Better dump merging UX.

chunky/src/java/se/llbit/resources/ImageLoader.java
OpenJDK <11 [has a bug][1] where it would ignore the transparent color of RGB PNG files. This was fixed [in OpenJDK 11][2] but is still an issue in Java 8.
This bug causes issues with some resourcepacks that use RGB PNGs with a transparent color, e.g. [Sapixcraft 128x][3] (e.g. the _Azure Bluet_).
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/5544859/113322531-17edf880-9315-11eb-9c18-d001883937bd.png)|![image](https://user-images.githubusercontent.com/5544859/113322439-fab92a00-9314-11eb-92c0-0fd12b0cc08f.png)|
(Note how the issue does not appear on grass blocks where the texture uses 32-bit RGBA PNG)
[1]: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6788458
[2]: https://github.com/AdoptOpenJDK/openjdk-jdk11/commit/e9be6a236f8a752a768b29660482e52fba56 …
=> Fix RGB textures with transparent color not working properly on Java 8.

chunky/src/java/se/llbit/chunky/model/TorchModel.java
Fixes a regression introduced in #877. The wall torch model goes out of the 1x1x1 block box and needs to be "clipped" (i.e. hits outside of the box must be ignored).
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/5544859/113587330-ea63c080-962e-11eb-8d24-f721ac301031.png)|![image](https://user-images.githubusercontent.com/5544859/113587360-f780af80-962e-11eb-9c35-db61c45e33b4.png)|
=> Clip the torch model to the block box.

chunky/src/java/se/llbit/chunky/ui/RenderCanvasFx.java, chunky/src/res/se/llbit/chunky/ui/render/HelpTab.fxml
Camera key bindings work slightly differently with different projections; Controls listed are for standard projection which is typically what people use. Fullscreen has been removed thus `U` does nothing. `K` & `J` only move by 1 unit thus redundant. Added a mention of the `CTRL` modifier key.
=> Update camera controls in Help tab

chunky/src/java/se/llbit/chunky/block/SeaPickle.java, chunky/src/java/se/llbit/chunky/chunk/BlockPalette.java
Turns out [sea pickles are supposed to emit light](https://minecraft.fandom.com/wiki/Sea_Pickle#Usage) depending on the number of pickles (3, 6, 12, 15) if they are waterlogged.
=> Make sea pickles emit light.

chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/resources/OctreeFileFormat.java, chunky/src/java/se/llbit/math/Octree.java, chunky/src/java/se/llbit/math/PackedOctree.java
This PR changes the way blocks are set into the octree during loading. 
Setting a block is quite slow (we need to walk down the tree, make the change and try to merge). Especially when doing work that is undone later like when node are subdivised and later merged back because they were of the same type.
The idea of this PR is to amortized a bit this cost by setting a bunch of blocks at once, here 16\*16\*16. This is done with a new method on octree implementation with a default implementation that simply set block one by one. There is a specialized implementation for Packed.
With this change (and by using Packed octree) I saw a 10% reduction of the total loading time of 9 regions of the greenfield map (128.9s before, 116.3s after)
=> Bulk octree set

chunky/src/java/se/llbit/chunky/map/MapView.java, chunky/src/java/se/llbit/chunky/map/SurfaceLayer.java, chunky/src/java/se/llbit/chunky/map/WorldMapLoader.java, chunky/src/java/se/llbit/chunky/ui/ChunkyFxController.java, chunky/src/java/se/llbit/chunky/ui/render/GeneralTab.java, chunky/src/java/se/llbit/chunky/world/Chunk.java, chunky/src/java/se/llbit/chunky/world/ChunkView.java, chunky/src/java/se/llbit/chunky/world/EmptyChunk.java, chunky/src/java/se/llbit/chunky/world/EmptyRegionChunk.java, chunky/src/java/se/llbit/chunky/world/RegionParser.java, chunky/src/res/se/llbit/chunky/ui/Chunky.fxml
As [suggested on Reddit](https://old.reddit.com/r/chunky/comments/mmw1ae/ylevel_view_slider_in_chunky_2/), this adds a control to change the y level in the map view which is useful if you are searching for underground structures to render.
This also changes the reload behavior to not clear the chunk selection anymore.
=> Add a y level slider to the map view

chunky/src/java/se/llbit/chunky/renderer/export/PictureExportFormats.java
This sorts the export formats alphabetically in the Advanced tab.
This is especially helpful with a larger list of formats registered by plugins and would be beneficial for my MagickExportPlugin 😉
=> Sort PictureExportFormats::formats

chunky/src/java/se/llbit/chunky/block/BrewingStand.java, chunky/src/java/se/llbit/chunky/block/DaylightDetector.java, chunky/src/java/se/llbit/chunky/block/Piston.java, chunky/src/java/se/llbit/chunky/block/ShulkerBox.java, chunky/src/java/se/llbit/chunky/block/Snow.java
This back-ports block fixes and optimizations from #901. Marking blocks as opaque reduces memory usage because it allows us to replace the blocks they cover with a special _any_ block in the octree. Adjacent _any_ blocks can be stored more efficiently.
In this picture the daylight sensor is marked as opaque (also fixed by this PR) and thus the (as far as chunky is concerned) invisible dirt block was replaced with _any_ and rendered as stone.
=> Fix and optimize some blocks

chunky/src/java/se/llbit/chunky/renderer/renderdump/ClassicDumpFormat.java, chunky/src/java/se/llbit/util/ProgressListener.java, chunky/src/test/se/llbit/chunky/renderer/renderdump/RenderDumpTests.java
- fixes #905 including "test"
- adds default fallback implementation for ProgressListener which ignores eta to allow creation of listeners as lambda
=> Fix dump loading progress indicator for ClassicDumpFormat

chunky/src/java/se/llbit/chunky/block/Water.java, chunky/src/java/se/llbit/chunky/renderer/scene/PreviewRayTracer.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/ui/render/WaterTab.java, chunky/src/res/se/llbit/chunky/ui/render/WaterTab.fxml
Switch water-world to use the blockpalette water which allows for changing it's material properties.
Removed `Water.OCEAN_WATER` since it was not being used outside of water-world.
=> Better waterworld.

chunky/src/java/se/llbit/chunky/chunk/ChunkData.java, chunky/src/java/se/llbit/chunky/chunk/EmptyChunkData.java, chunky/src/java/se/llbit/chunky/chunk/GenericChunkData.java, chunky/src/java/se/llbit/chunky/chunk/SimpleChunkData.java, chunky/src/java/se/llbit/chunky/renderer/scene/PreviewRayTracer.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/world/Chunk.java, chunky/src/java/se/llbit/chunky/world/EmptyChunk.java, chunky/src/java/se/llbit/chunky/world/EmptyRegionChunk.java
Forgot to stage this in the last PR. A world texture contains a chunk texture iff that chunk is loaded, no need to get or check the color.
=> Speed up isChunkLoaded by not checking the color.

chunky/src/java/se/llbit/chunky/ui/ChunkyFxController.java, chunky/src/java/se/llbit/chunky/ui/render/CameraTab.java, chunky/src/java/se/llbit/chunky/ui/render/EntitiesTab.java, chunky/src/java/se/llbit/chunky/ui/render/GeneralTab.java, chunky/src/res/se/llbit/chunky/ui/Chunky.fxml, chunky/src/res/se/llbit/chunky/ui/render/CameraTab.fxml, chunky/src/res/style.css, lib/src/se/llbit/chunky/ui/Adjuster.java, lib/src/se/llbit/chunky/ui/DoubleTextField.java, lib/src/se/llbit/chunky/ui/IntegerTextField.java, lib/src/se/llbit/chunky/ui/NumericTextField.java, lib/src/se/llbit/chunky/ui/SilentNumberStringConverter.java
Currently all numeric inputs throw `RuntimeException`s if the input can't be converted to a number. While this error can safely be ignored it produces a lot of noise and frequently makes people think that it's a bug.
This PR fixes that and introduces new convenient `TextField`s for numeric input that get a red border if the input is invalid.
=> Improve numeric fields

chunky/src/java/se/llbit/chunky/world/Chunk.java, chunky/src/java/se/llbit/chunky/world/EmptyChunk.java, chunky/src/java/se/llbit/chunky/world/EmptyRegionChunk.java, chunky/src/java/se/llbit/chunky/world/RegionParser.java
`Chunk#loadChunk` now returns whether the input `ChunkData` object was modified, which is used to prevent useless calls to `ChunkData#clear`
=> RegionParser only clears chunk data if modified

chunky/src/java/se/llbit/chunky/world/ChunkPosition.java
eliminates one hashmap get
also uses `computeIfAbsent` insead of `get` nullcheck `put` which is also faster
=> Make ChunkPosition#get much faster

chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
Fix #934
The bug was because the origin was not taken into account when doing the height comparison of the water plane with the y of the ray origin.
The bug does not manifest itself when yMin is 0 which is probably the reason you couldn't reproduce it.
=> Fix broken water world

chunky/src/java/se/llbit/math/Octree.java
Fix the bug where we had this
instead of this
when loading a single chunk with yMin-yMax to 0-16.
The cause of the bug is that, during finalization we checked blocks out of bounds of the octree when trying to do the replacement by ANY, those out of bounds access wrapped around and where accessing the blocks at the other end of the octree. When the blocks at the other end of the octree are solid, the block at the edge of the octree is thought to be hidden when it is not.
See how this is bug is also reproduced with a 32\*32\*32 octree
Or even by a situation a bit more complex:
The front face is wrong because the adjacent blocks are thought to be the one on the back of the chunk in the background.
Anyway the fix is to check for out of bound access and return Air in this case
=> Fix bug where the blocks were wrong with small octree

chunky/src/java/se/llbit/chunky/ui/ChunkyFx.java, lib/src/se/llbit/chunky/PersistentSettings.java, lib/src/se/llbit/fxutil/WindowPosition.java
Small quality of life feature (maybe more for me that for real users).
I was annoyed with chunky starting maximized every time I start it (often while debugging) when I don't want it to cover the whole screen.
I was not able to test this with multiple screen, if someone can try that, I'd appreciate it. I'm especially worried about the situation where the chunky window is put on the second screen, close (saving its position), the second screen is unplugged and chunky reopened, I don't know where chunky would go in this situation
=> Save the window position/size on close and restore that on startup

chunky/src/java/se/llbit/chunky/ui/ChunkMap.java, chunky/src/java/se/llbit/chunky/ui/render/GeneralTab.java, chunky/src/res/style.css
Related to #945 but doesn't actually fix the bug but only prevents users from creating empty scenes (which is a tiny UX improvement).
=> Prevent empty scene creation

chunky/src/java/se/llbit/chunky/block/Head.java, chunky/src/test/se/llbit/chunky/block/SkullTextureTest.java
…also add tests so that this doesn't break again, hopefully (they test all known bugs with this feature, testing it manually is very tedious).
Fixes #680 again
=> Fix parsing skull textures that are not valid json (again)

chunky/src/java/se/llbit/chunky/renderer/postprocessing/GammaCorrectionFilter.java, chunky/src/java/se/llbit/chunky/renderer/postprocessing/PixelPostProcessingFilter.java, chunky/src/java/se/llbit/chunky/renderer/postprocessing/PostProcessingFilter.java, chunky/src/java/se/llbit/chunky/renderer/postprocessing/PostProcessingFilters.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/ui/render/PostprocessingTab.java, chunky/src/java/se/llbit/tiff/TiffFileWriter.java
This logs a warning and saves without post-processing.
I also moved the default post-processor into the scene because it's more of a default value for a scene than something related to the post-processing itself.
=> Handle unsupported post-processors more gracefully when exporting a tiff

chunky/src/java/se/llbit/chunky/renderer/TileBasedRenderer.java
cf discussion on discord.
I set a value to the normal after the ray is created. The actual value doesn't matter, the only case where it isn't replaced is when the camera is inside a block and the screen will be black.
Fix #963
=> Prevent normal being (0, 0, 0) which leads to lock in the renderer

chunky/src/java/se/llbit/chunky/main/Chunky.java, chunky/src/java/se/llbit/chunky/renderer/DefaultRenderManager.java, chunky/src/java/se/llbit/chunky/renderer/RenderManager.java, chunky/src/java/se/llbit/chunky/ui/ChunkyFxController.java
In the denoiser plugin I don't want to save snapshots for albedo or normal maps and add my own snapshot control for that reason. Turns out it had no effect.
=> Fix overwriting snapshot control having no effect on saving snapshots.

chunky/src/java/se/llbit/chunky/block/Head.java, chunky/src/test/se/llbit/chunky/block/SkullTextureTest.java
Fixes #969 
Unfortunately, llbit's json parser doesn't have an option to ignore missing `""`. That would help a lot because we could then remove the regex and parse the JSON properly.
For future readers (probably me): My first commit fixed the issue because .* is greedy, unlike .+?, so it matches everything until the very last " in the string, not only until the first " (which is what we need). The second commit (fix suggested by @Stenodyon) makes this more clear.
=> Fix another skull json regex error.

chunky/src/java/se/llbit/chunky/world/ChunkTexture.java, chunky/src/java/se/llbit/math/ColorUtil.java
Back with my memory usage obsession, this time I changed ChunkTexture to be stored as byte instead of float and doing the conversion to linear on the fly.
I think I didn't touch it last time I changed several classes because iirc NotStirred wanted to change how it's done. But  WorldTexture (due to ChunkTexture) is now the biggest object in memory (when using optimized octrees) and the change is simple that it's worth it even if ChunkTexture is changed in a month (especially if this makes it to chunky 2.4 but not the changes NotStirred wanted to make).
I've not measured a performance drop due to this (but it was a small scale test).
The format on disk is unchanged.
=> Reduce memory usage of ChunkTexture

chunky/src/java/se/llbit/chunky/renderer/scene/OctreeFinalizer.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/resources/OctreeFileFormat.java, chunky/src/java/se/llbit/math/BigPackedOctree.java, chunky/src/java/se/llbit/math/NodeBasedOctree.java, chunky/src/java/se/llbit/math/Octree.java, chunky/src/java/se/llbit/math/PackedOctree.java, chunky/src/test/se/llbit/chunky/main/PluginApiTest.java
Now that we know that even <1.13 world support won't require data, we can drop all related code.
To improve memory efficiency, `Node get(int,int,int)` and `set(Node,int,int,int)` should be removed, too (but I don't know how to replace their implementations).
=> Remove deprecated/unused octree methods

chunky/src/java/se/llbit/chunky/ui/ChunkMap.java
locked to 24fps, can make it configurable if requested
Here is greenfield 2021 example:
before
https://user-images.githubusercontent.com/16853282/119767438-b5495100-beae-11eb-9728-1285352979f7.mp4
after
https://user-images.githubusercontent.com/16853282/119767456-bed2b900-beae-11eb-932a-7ec4af3b73ea.mp4
=> Prevent map view from attempting to render as fast as possible

chunky/src/java/se/llbit/chunky/ui/ChunkMap.java
This fixes the regressions from #979 that I described in #985.
View updates and repainting are now a bit more deferred:
- The view is _always_ updated (position and size) and a deferred repaint is scheduled
- On deferred repaint, the mapBuffer is updated if it needs to be updated (this is the part that needed to be deferred to fix freezes e.g. for @NotStirred)
This ensures that `repaintDeferred` always uses the _latest_ position and size (i.e. `view`) but still doesn't repaint on every `viewUpdated` call. Not too many repaints (= no freezing) yet still always rendering the _latest_ position/size (= no lagging behind the cursor or missing updates e.g. after launching or resize)
=> Fix lags and dropped repaints in the map view.

chunky/src/java/se/llbit/chunky/map/WorldMapLoader.java, chunky/src/java/se/llbit/chunky/ui/ChunkyFxController.java, chunky/src/java/se/llbit/chunky/world/ChunkTopographyUpdater.java, chunky/src/java/se/llbit/chunky/world/World.java
Fixes #926 and removes listeners and clears queues so that the map view updates faster after reloading a world.
=> Fix worlds being loaded twice

chunky/src/java/se/llbit/chunky/ui/render/PostprocessingTab.java
The post processors are sorted alphabetically but displaying none in the middle doesn't make sense.
This improves it to look like this:
=> Move none to the top of the post processor combobox and add a separator.

chunky/src/java/se/llbit/chunky/block/Ladder.java
Fix water height below ladders and legacy world block connections to ladders.
Once #901 ist done, we should go through the translucent blocks and check if they actually are solid.
=> Mark ladders as non-solid

chunky/src/java/se/llbit/chunky/renderer/DefaultRenderManager.java, chunky/src/java/se/llbit/chunky/renderer/RenderWorkerPool.java, chunky/src/java/se/llbit/chunky/renderer/Renderer.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/test/se/llbit/chunky/renderer/TestDeadlock.java
Fixed an issue where finalization occurred twice.
Public'ed `RenderWorker.resetSleep()`.
Fixed an issue where you couldn't change the PreviewRenderer.
Allowed render jobs to throw `InterruptedException`.
Refactored `RenderWorkerPool` to return wait-able Futures.
=> Small RenderManager bug fixes.

chunky/src/java/se/llbit/chunky/renderer/DefaultRenderManager.java
The preview callback was checking the wrong `Renderer`'s `auotPostProcess()` method.
=> Fix preview not updating under certain plugin circumstances.

chunky/src/java/se/llbit/chunky/renderer/DefaultRenderManager.java
Replaced `withSceneProtected()` to `withEditSceneProtected()` when setting render-mode to `PAUSED`
=> Fix bug where opening the `Advanced Tab` with certain plugins installed would cause a crash.

chunky/src/java/se/llbit/chunky/renderer/RenderWorkerPool.java
This allows plugins to actually use the `RenderWorkerPool`
=> Make `RenderJob` public.

chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/util/mojangapi/MojangApi.java
This fixes an NPE when loading players without a skin:
```
Exception in thread "Scene Manager" java.lang.NullPointerException: Cannot invoke "se.llbit.util.mojangapi.PlayerSkin.getUrl()" because "skin" is null
at se.llbit.chunky.renderer.scene.Scene.loadChunks(Scene.java:909)
at se.llbit.chunky.renderer.scene.SynchronousSceneManager.loadChunks(SynchronousSceneManager.java:178)
at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.lambda$loadChunks$3(AsynchronousSceneManager.java:152)
at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.run(AsynchronousSceneManager.java:82)
=> Fix NPE when loading players that don't have a skin

chunky/src/java/se/llbit/chunky/renderer/scene/AsynchronousSceneManager.java
Exceptions are now logged and shown to the user.
Out of memory errors get a special message:
=> Better error handling in Asynchronous Scene manager.

chunky/src/java/se/llbit/chunky/ui/render/AdvancedTab.java, chunky/src/java/se/llbit/chunky/ui/render/PostprocessingTab.java, chunky/src/java/se/llbit/chunky/ui/render/SkyTab.java
Properly handle `null` cases in StringConverters.
Closes #1016
=> Fix null pointer exception from StringConverter.

chunky/src/java/se/llbit/chunky/renderer/renderdump/RenderDump.java
This buffers the Input/Output streams for dumps, allowing dump formats that take many small operations to be much much faster. May help on existing dumps by just a little.
(I thought this was added a while ago.)
=> Buffered Dump IO

chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
See #1018 for motivation for this.
---
now:
Setting rayDepth to 1 -> light cannot bounce off the ground, thus everything but the sky is black.
Setting rayDepth to 2 -> light can bounce off of the ground/blocks, but cannot bounce off of anything else. Emitters do not work.
Setting rayDepth to 3 -> hey look, torches give off light now!
Setting rayDepth to 4 -> the start of indirect illumination from emitters...
=> Quick Removal Of The Incorrect Russian Roulette.

chunky/src/java/se/llbit/chunky/renderer/scene/AsynchronousSceneManager.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/ui/ChunkyFxController.java
* Added an `enqueueTask` api to AsynchronousSceneManager which allows for synchronized scene modifications to happen off the JavaFx thread.
* Add a query to to Scene to check if it is currently loading a scene.
* Adjust render control buttons to use the `enqueueTask` api and ignore clicks while the Scene is loading.
This closes #832 (Pausing loading should probably be separate since it would be quite complex)
=> Stop render control buttons from causing Chunky to freeze while loading a scene.

chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/world/ChunkTexture.java, chunky/src/java/se/llbit/chunky/world/WorldTexture.java
Some benchmarks:
Greenfield:
|    | Heap used |
|---|-----------|
| master | 4,718,981,222 bytes |
| deduped | 4,369,123,080 bytes |
4 regions of a real world:
|   | `WorldTexture` size | Number of `ChunkTexture`s |
|---|-------------------|----------------------------|
| master | 27,787,634 bytes |  36,864 textures |
| deduped | 2,271,314 bytes  | 1,786 textures|
=> Deduplicate WorldTextures to save a lot of memory.

chunky/src/java/se/llbit/chunky/world/ChunkPosition.java, chunky/src/java/se/llbit/chunky/world/Heightmap.java
By indexing the map used by Heightmpa with a long instead of a ChunkPosition, we don't need to call ChunkPosition.get, which incurs another map lookup and a temporary Long allocation, every time we use HeightMap.get or Heightmap.set. Those temporary Long represent a good chunk of the allocation during the 2D map loading so removing them reduces gc pressure.
This makes the 2D map loads faster, about -12% to get the same area completely loaded. I don't know how much is due to having only one hash map lookup vs 2 and how much is because of reduce gc pressure but it doesn't really matter
=> Replace the map used by Heightmap to reduce gc pressure

chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
Linked lists aren't particularly memory efficient ... and there can be a lot of entities. In my entity test scene `Scene` total size went from `21,288`B to `8,952`B.
=> Convert entity collections from LinkedList to ArrayList.

launcher/src/se/llbit/chunky/launcher/ChunkyLauncher.java, launcher/src/se/llbit/chunky/launcher/JavaFxLocator.java
- add Java version 16 and 17 paths for linux
- add checking parent directory of `jre` and `jdk` folders for windows (relevant for ojdkbuild)
- add home directory installation `.chunky` check
- add checks for lib directory and its parent directory
- add eager check for directories named `*javafx*` in some locations (relevant for JavaFX SDKs extracted from the downloads from https://openjfx.io/ resp. https://gluonhq.com/products/javafx/)
=> Revamp javafx locator

chunky/src/res/se/llbit/chunky/ui/Chunky.fxml
- move render controls into left panel
- give the start and pause buttons text
- add spacing to progress texts
pros: dedicated area for render controls (they even take up about the width of the sidebar) using less vertical space
cons: more "semantic distance" from the progress report in the layout
left side: current Chunky
right side: this PR
behaviour under minimal size:
=> Move render controls UI

chunky/src/java/se/llbit/chunky/ui/ChunkMap.java, chunky/src/java/se/llbit/chunky/world/ChunkSelectionTracker.java
I didnt know about the control to deselect groups of chunks until I looked at the code. If a rectangle region of chunks is all selected already, then deselecting them makes sense, as clicking an individual chunk toggles it, and regions do something similar.
=> Deselect Chunks In Rectangle If All Selected

chunky/src/java/se/llbit/chunky/ui/ChunkyFxController.java, chunky/src/java/se/llbit/fxutil/Dialogs.java, chunky/src/res/se/llbit/chunky/ui/Chunky.fxml
This does not close #1034, but is an simple fix to prevent unwanted deletion of selected chunks when clicking the current confirmation dialog away.
=> Implement more intrusive confirmation dialog for chunk deletion

chunky/src/java/se/llbit/chunky/block/legacy/LegacyBlocks.java, chunky/src/java/se/llbit/chunky/map/SurfaceLayer.java, chunky/src/java/se/llbit/chunky/world/Chunk.java, chunky/src/java/se/llbit/chunky/world/CubicWorld.java, chunky/src/java/se/llbit/chunky/world/ImposterCubicChunk.java, chunky/src/java/se/llbit/chunky/world/World.java
The main speedup for legacy worlds is the static initialisation of tags. Instead of creating a new tag object for every single block, it just indexes a pre-initialised 4096 length array.
In `SurfaceLayer#<init>` I *actually use the heightmap data* calculated the line before calling it, instead of recalculating it in the constructor
Ideally don't merge this PR at the same time as #1031 as I have to implement these optimisations there too. I'd prefer merging #1031 first, to keep things together that logically should be, but it doesn't really matter
=> Simple map view optimisations

chunky/src/java/se/llbit/chunky/renderer/DefaultRenderManager.java, chunky/src/java/se/llbit/chunky/renderer/RenderWorkerPool.java
Closes #1047.
Persist the sleep interval timer through fetching a new job. Set the minimum sleep duration to 100ms and maximum to 1000ms. Properly set the CPU load on initialization of the render manager.
4 Threads:
| CPU Utilization | Task Manager Reported CPU | %  of 100% |
|------------------|---------------------------------|-------------|
| 100% | 60% | 100% |
| 90% | 53% | 88% |
| 70% | 44% | 73% |
| 50% | 34% | 56% |
| 25% | 19% | 31% |
| 1% | 1.1% | 1.8% |
=> Fix CPU load setting.

chunky/src/java/se/llbit/chunky/main/CommandLineOptions.java, chunky/src/test/se/llbit/chunky/main/OptionHandlerTest.java
Allows negative numbers for _value_ in `-set <NAME> <VALUE> [<SCENE>]`
Fixes #1030
=> Allow negative numbers as command line arguments in options

chunky/src/test/se/llbit/chunky/chunk/BlockPaletteTest.java, chunky/src/test/se/llbit/chunky/entity/MarshallingTest.java, chunky/src/test/se/llbit/chunky/nbt/NBTTest.java, chunky/src/test/se/llbit/chunky/renderer/BlankRenderTest.java, chunky/src/test/se/llbit/chunky/renderer/DeadlockTest.java, chunky/src/test/se/llbit/chunky/renderer/renderdump/RenderDumpTest.java, chunky/src/test/se/llbit/chunky/renderer/scene/SceneManagerTest.java, chunky/src/test/se/llbit/chunky/renderer/scene/SceneTest.java, chunky/src/test/se/llbit/fxutil/GroupedChangeListenerTest.java, chunky/src/test/se/llbit/log/LogTest.java, chunky/src/test/se/llbit/math/MutableAABBTest.java, chunky/src/test/se/llbit/math/QuickMathTest.java, chunky/src/test/se/llbit/util/RingBufferTest.java
This fixes inconsistent test class naming (e.g. TestBlockPalette/PluginAPITest/RenderDumpTests) and test method naming.
Now follows the Java Unit Naming Convention https://wiki.c2.com/?JavaUnitNamingConvention
and https://stackoverflow.com/questions/3146821/naming-convention-junit-suffix-or-prefix-test
Naming schema is now:
`<<ClassName>>Test.java`
`@Test void test<<WhatIsTested>>()`
=> Rename various tests and test classes to have consistent naming scheme

chunky/src/java/se/llbit/chunky/block/Lava.java, chunky/src/java/se/llbit/chunky/block/Water.java, chunky/src/java/se/llbit/chunky/model/AABBModel.java, chunky/src/java/se/llbit/chunky/model/AnimatedQuadModel.java, chunky/src/java/se/llbit/chunky/model/CauldronModel.java, chunky/src/java/se/llbit/chunky/model/HoneyBlockModel.java, chunky/src/java/se/llbit/chunky/model/QuadModel.java, chunky/src/java/se/llbit/chunky/model/SlimeBlockModel.java, chunky/src/java/se/llbit/chunky/model/SpriteModel.java, chunky/src/java/se/llbit/chunky/model/TexturedBlockModel.java, chunky/src/java/se/llbit/chunky/model/TorchModel.java, chunky/src/java/se/llbit/chunky/model/WaterModel.java, chunky/src/java/se/llbit/chunky/renderer/TileBasedRenderer.java, chunky/src/java/se/llbit/chunky/renderer/scene/PathTracer.java, chunky/src/java/se/llbit/chunky/renderer/scene/PreviewRayTracer.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/renderer/scene/Sky.java, chunky/src/java/se/llbit/chunky/renderer/scene/Sun.java, chunky/src/java/se/llbit/math/AABB.java, chunky/src/java/se/llbit/math/Octree.java, chunky/src/java/se/llbit/math/Ray.java, chunky/src/java/se/llbit/math/primitive/TexturedTriangle.java
This was unintentionally changed in #901. Change `Ray.getN()` back to `Ray.getNormal()` to fix compatibility with plugins such as denoiser. Also re-add `Ray.orientNormal(...)` which saves on a `Vector3` allocation which should improve rendering performance. Clean up the old intersection logic from `TorchModel` which was not being used.
=> Rename getN to getNormal.

chunky/src/java/se/llbit/chunky/renderer/scene/SynchronousSceneManager.java, chunky/src/java/se/llbit/chunky/world/MaterialStore.java
This PR fixes some issues that happen when embedding Chunky in another tool (e.g. ChunkyCloud or ChunkyMap) and creating new `Chunky` instances.
Makes #670 pretty much obsolete.
=> Fix issues when using Chunky as a library

chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
Mushroom block and cartography table had their east and west texture swapped.
Before:
Now:
=> Fix Mushroom Block and Cartography Table.

chunky/src/java/se/llbit/chunky/world/Chunk.java, chunky/src/java/se/llbit/util/NbtUtil.java
Does not support biome palettes.
Across the snapshots the sections array has been in `.Level.Sections` -> `.Level.sections` -> `.sections`
do you want me to add support for `.Level.sections` as well? iirc it's in a few of the snapshots though I can't really remember
Notable changes for review:
- Added `getTagFromNames` function, which gets the first valid tag from the given names (helps with mojang moving around identical structures)
- Changed `Map<String, Tag> data` to `Tag data` for easier use of `getTagFromNames`
=> Basic support of the new block data location in 1.18

.github/workflows/gradle.yml
For larger pull requests, it is often helpful for there to be a build for non-developers to try out the new features. This publishes 2 artifacts per build, a documentation artifact and a release jar artifact.
=> Build distribution and upload artifact.

chunky/src/java/se/llbit/chunky/world/Chunk.java
Small regression introduced last-minute in #1078
=> Fix regression when loading pre-1.18 worlds.

launcher/src/se/llbit/chunky/launcher/ui/ChunkyLauncherController.java
We frequently get questions from people who use the "latest version", but not knowing the actual version makes providing help pretty difficult.
=> Show the actual version next to "latest" in the version dropdown.

chunky/src/java/se/llbit/chunky/ui/SceneChooser.java, chunky/src/java/se/llbit/chunky/ui/SceneChooserController.java, chunky/src/res/se/llbit/chunky/ui/SceneChooser.fxml
- Default sorting of scenes is by most recent at the top, just as you've always wanted. You're welcome :)
- Rebalanced column widths (Can now fit the default scene name)
- ~~some stuff for cropping scenes, currently unused and/or commented out. Will be used once sub-scene tiling/cropping comes in #786)~~
Closed #437
=> Scene Picker UI: Cleanup & Sort By Last Modified

chunky/src/java/se/llbit/chunky/resources/TexturePackLoader.java
Closes #1137.
Java was not happy with an empty root path for some reason.
=> Fix texture loading from zip files.

chunky/src/java/se/llbit/chunky/ui/ChunkyFxController.java, chunky/src/java/se/llbit/chunky/ui/WorldChooserController.java, chunky/src/java/se/llbit/fxutil/Dialogs.java
=> Make load world confirmation always on top.

chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
Set `chunkData` to `EmptyChunkData` if it is `null`.
=> Fix NPE when trying to load an invalid chunk.

chunky/src/java/se/llbit/chunky/map/MapTile.java
Fix when invalid chunks are selected once you select the chunk at (0, 0).
Master:
Now:
=> Fix map selection of invalid chunks.

chunky/src/java/se/llbit/chunky/main/Chunky.java, chunky/src/java/se/llbit/chunky/renderer/scene/AsynchronousSceneManager.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/renderer/scene/SceneManager.java, chunky/src/java/se/llbit/chunky/renderer/scene/SynchronousSceneManager.java, chunky/src/java/se/llbit/chunky/ui/ChunkyFxController.java, chunky/src/java/se/llbit/chunky/ui/SceneChooserController.java
There were several places where we assumed the scene directory was the default location, which is
not the case when using the `-scene-dir` argument.
This PR removes `resolveSceneDirectory()` entirely, as that assumed the default location
In my testing, this works correctly both with no `-scene-dir` argument, and a specified one.
I have not fiddled with this part of chunky before, so some testing from someone more experienced would be appreciated
=> Use the correct scene directory throughout the project

chunky/src/java/se/llbit/chunky/ui/Icons.java, chunky/src/java/se/llbit/chunky/ui/elements/SizeInput.java, chunky/src/java/se/llbit/chunky/ui/render/tabs/GeneralTab.java, chunky/src/res/se/llbit/chunky/ui/render/tabs/GeneralTab.fxml, chunky/src/res/style.css, lib/src/se/llbit/chunky/ui/Adjuster.java, lib/src/se/llbit/chunky/ui/IntegerAdjuster.java, lib/src/se/llbit/chunky/ui/IntegerTextField.java, lib/src/se/llbit/chunky/ui/NumericTextField.java, lib/src/se/llbit/chunky/ui/SizeInput.java, lib/src/se/llbit/chunky/ui/ValidatingNumberStringConverter.java, lib/src/se/llbit/math/ObservableSize2D.java, lib/src/se/llbit/math/QuickMath.java, lib/src/se/llbit/math/Size2D.java, lib/src/se/llbit/math/WritableSize2D.java
closes #1125 
This PR builds upon #1171
=> Feature: UI for locking canvas size aspect ratio

chunky/src/java/se/llbit/chunky/world/Chunk.java
Closes #1191 
Looks like sections that are optimized by not including a block data array and rather just having a single block palette with a non-air block were ignored.
=> Fix empty 16x16x16 sections of identical blocks.

lib/src/se/llbit/chunky/ui/NumericTextField.java
When the input box has focus, do not autoformat until enter is pressed or focus is lost. Otherwise, only autoformat when it is not focused.
Closes #1202.
=> Do not autocomplete `.0` until enter is pressed or focus is lost.

chunky/src/java/se/llbit/resources/ImageLoader.java
If on Java 8, try loading with AWT first. If this fails, try loading with ImageIO.
Closes #1207 . Note, some transparent textures may be broken (see #872 ).
=> Load textures with ImageIO if AWT fails.

chunky/src/java/se/llbit/chunky/ui/controller/ChunkyFxController.java, chunky/src/res/se/llbit/chunky/ui/Chunky.fxml, lib/src/se/llbit/chunky/ui/IntegerAdjuster.java, lib/src/se/llbit/chunky/ui/PositiveIntegerAdjuster.java
Closes #1210
Add PositiveIntegerAdjuster to cover the cases where it was required
Negative ints are properly accepted in the correct fields. (As soon as you click off the errored field it will clamp it to the minimum)
=> Fix weird special-casing for positive bounds on IntegerAdjuster

chunky/src/java/se/llbit/chunky/chunk/GenericChunkData.java, chunky/src/java/se/llbit/chunky/chunk/SimpleChunkData.java
- fix biomeData NPE on SimpleChunkData clear
(Had this happen in some chunks of my worlds, which caused them to not load.)
- also moved member initialization from constructor to declaration (removed trivial constructor)
=> Fix biomeData NPE on SimpleChunkData clear

chunky/src/java/se/llbit/chunky/model/MangroveRootsModel.java
Fixes #1248 
The pixels of the inner planes of the mangrove roots texture now line up with the pixels on the outer planes.
The same fix for Minecraft, "This is a very easy fix - all of the "0.8" values in the model should be changed to "0" and every "15.2" to "16"," ([MC-250075](https://bugs.mojang.com/browse/MC-250075)), also applied to Chunky.
Minecraft 22w17a:
Chunky latest snapshot:
Fixed:
=> 22w17a - Update Mangrove Roots Model

chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java, chunky/src/java/se/llbit/chunky/world/region/RegionParser.java
also add a general catch for the region parser to prevent such errors from going unnoticed / without a stacktrace
=> Fix palette error due to expecting block name to contian "minecraft:"

chunky/src/java/se/llbit/chunky/main/CommandLineOptions.java
Let the following command :
```
chunky -set chunkList "[[1,-2]]" scene
```
Before this commit, scene.json will result in (which is invalid) :
```
{
...
"chunkList": "[[1,-2]]",
...
}
```
After this commit, scene.json will result in :
```
{
...
"chunkList": [
[
1,
-2
]
],
...
}
```
=> Headless mode : Allow json parameter in -set option

chunky/src/java/se/llbit/chunky/resources/ResourcePackLoader.java
Only `ZipFileSystem` may be `close`d, other file systems throw due to an unsupported operation.
=> Fix loading resourcepacks from a directory.

chunky/src/java/se/llbit/chunky/main/Chunky.java, chunky/src/java/se/llbit/chunky/renderer/scene/PreviewRayTracer.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/renderer/scene/biome/BiomeStructure.java, chunky/src/java/se/llbit/chunky/renderer/scene/biome/Trivial2dBiomeStructureImpl.java, chunky/src/java/se/llbit/chunky/renderer/scene/biome/Trivial3dBiomeStructureImpl.java, chunky/src/java/se/llbit/chunky/resources/OctreeFileFormat.java, chunky/src/java/se/llbit/chunky/ui/render/tabs/AdvancedTab.java, chunky/src/java/se/llbit/chunky/ui/render/tabs/GeneralTab.java, chunky/src/java/se/llbit/math/Ray.java, chunky/src/java/se/llbit/math/structures/Position2IntStructure.java, chunky/src/java/se/llbit/math/structures/Position2ReferenceStructure.java, chunky/src/java/se/llbit/math/structures/Position2d2IntPackedArray.java, chunky/src/java/se/llbit/math/structures/Position2d2ReferencePackedArrayStructure.java, chunky/src/java/se/llbit/math/structures/Position3d2IntPackedArray.java, chunky/src/java/se/llbit/math/structures/Position3d2ReferencePackedArrayStructure.java, chunky/src/res/se/llbit/chunky/ui/render/tabs/AdvancedTab.fxml, chunky/src/res/se/llbit/chunky/ui/render/tabs/GeneralTab.fxml, lib/src/se/llbit/chunky/PersistentSettings.java
In the future it would be great to add a better implementation for performance
=> Add trivial implementation of 3d biomes and 3d blur (off by default)

chunky/src/java/se/llbit/chunky/ui/ChunkMap.java, chunky/src/java/se/llbit/chunky/ui/render/tabs/GeneralTab.java, chunky/src/java/se/llbit/chunky/world/ChunkSelectionTracker.java, chunky/src/java/se/llbit/chunky/world/listeners/ChunkUpdateListener.java
In theory this is much faster for large selections, though due to the weirdness of the map view there is no performance gain
(`chunkUpdated` must be fired for each chunk with its selection changed, `regionUpdated` is only correct if the scale is showing regions tiles)
This PR will give a nice way of getting per-region chunk selection for scene loading without having to collect the chunk positions into a map before loading them.
=> Add per-region selection instead of a list of chunks

chunky/src/res/se/llbit/chunky/ui/Chunky.fxml
=> Re-allow right panel in map tab to be resizable to 0

chunky/src/java/se/llbit/chunky/renderer/SunSamplingStrategy.java, chunky/src/java/se/llbit/chunky/renderer/scene/PathTracer.java, chunky/src/java/se/llbit/chunky/renderer/scene/PreviewRayTracer.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/renderer/scene/Sky.java, chunky/src/java/se/llbit/chunky/renderer/scene/Sun.java, chunky/src/java/se/llbit/chunky/ui/render/tabs/LightingTab.java, chunky/src/res/se/llbit/chunky/ui/render/tabs/LightingTab.fxml
Closes #1184.
This adds a `Sun Luminosity` setting which changes the true brightness of the sun when intersected with organically and a new sun sampling mode which does both sun samples and allows for sun intersections for diffuse materials. This new sun sampling mode allows for visual effects like caustics (with much render time):
=> Add `High Quality` sun sampling mode. Fix issue where enabling draw sun but not enabling sunlight would draw a sun with no contribution to the scene.

chunky/src/java/se/llbit/chunky/block/UnknownBlock.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/ui/render/tabs/AdvancedTab.java, chunky/src/res/se/llbit/chunky/ui/render/tabs/AdvancedTab.fxml
Closes #1302 
This PR hides unknown blocks at intersection time. We could also hide them while creating the octree (ie. in `BlockSpec.toBlock()` but that would require access to the scene, which we don't have there yet.
=> Hide unknown blocks

launcher/src/se/llbit/chunky/launcher/ChunkyLauncher.java, launcher/src/se/llbit/chunky/launcher/ui/ChunkyLauncherController.java, lib/src/se/llbit/chunky/launcher/LauncherSettings.java
* Check for Chunky update on startup (even if launcher is disabled).
* Fix bug where release channel would say:
* Fix bug where release channels would be empty:
=> Check for Chunky update on startup & fix release channel bug.

chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
=> Fix crash when saving the octree of a scene created with Chunky versions prior to 2.3

chunky/src/java/se/llbit/chunky/ui/ChunkyFxController.java
Fixed an issue where the Export ZIP had an incorrect tooltip and the Export PNG had no tooltip.
=> Fix Export ZIP and Export PNG tooltips

chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/world/Chunk.java
Closes #1343 
We were previously assuming the biomeIdxStructure was always compatible with 3d coordinates, which isn't true
I'll make a PR to clean up the biome palette stuff soon (@leMaik suggested something which I've yet to implement), but wanted to get it fixed straight away
=> Fix incorrect biomes in some worlds

chunky/src/java/se/llbit/chunky/entity/PlayerEntity.java
=> Fix crash if a armor stand skull owner uuid can not be resolved.

chunky/src/java/se/llbit/chunky/ui/ChunkyFxController.java, chunky/src/res/se/llbit/chunky/ui/Chunky.fxml
The name was inaccurate, as using this option does not actually require a restart.
Added a tooltip to the control.
=> Update singleColorBtn name.

chunky/src/java/se/llbit/chunky/ui/controller/ResourcePackChooserController.java, chunky/src/res/se/llbit/chunky/ui/dialogs/ResourcePackChooser.fxml
The control had no indication of a required restart, and provided no further information of what its functionality is.
- Updated the control name to indicate a required restart.
- Added a tooltip to the control to indicate its functionality.
=> Update Disable default textures control

chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/ui/render/tabs/CameraTab.java, chunky/src/res/se/llbit/chunky/ui/render/tabs/CameraTab.fxml
The underlying feature does not work as expected* and can also be accessed in EntitiesTab via "Camera to Entity".
* Code assumes that only one player exists in the scene, otherwise it uses the last loaded one - since we are able to load all players in a world, this is not what the user wants to do in most cases.
=> Remove outdated "Move Camera to Player" button in CameraTab

chunky/src/java/se/llbit/chunky/renderer/scene/SimplexWaterShader.java
Not using procedural water makes water tiling evident over large distances. Enabling procedural water fixes that issue, but not many people may understand what the controls do and may leave them at their default values. Procedural water at its default values does not look very realistic, and on the example scene, also causes a large perfromance drop. The new defaults look much more like the old "Fast" water does, but without the tiling. Additionally, on the example scene, the new default values outperformed the "Fast" water.
**Default procedural water settings: 168190 SPS.**
**New default procedural water settings: 436860 SPS.**
**"Fast" water: 432483 SPS.**
=> Update procedural water defaults

chunky/src/java/se/llbit/chunky/ui/elements/TextFieldLabelWrapper.java, chunky/src/java/se/llbit/chunky/ui/render/tabs/CameraTab.java, chunky/src/res/se/llbit/chunky/ui/render/tabs/CameraTab.fxml, chunky/src/res/style.css
- Have labels for each input field:
Previous:
- Moved the "center camera" (above loaded chunks) button to the camera coordinate input.
- Also rewritten some of the tooltips and removed self-explanatory ones.
This PR is based on top of #1350
=> Add more labels to camera controls

chunky/src/java/se/llbit/chunky/chunk/ChunkLoadingException.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/world/Chunk.java, chunky/src/java/se/llbit/chunky/world/region/MCRegion.java
The user is also warned about chunks being skipped in both map view loading, and in octree loading.
=> Throw exception when failing to load a chunk, allowing it to be safely skipped

chunky/src/java/se/llbit/chunky/ui/render/tabs/EntitiesTab.java, chunky/src/res/se/llbit/chunky/ui/render/tabs/EntitiesTab.fxml
Since the entity location controls in the `Entities` tab apply not only to players, but also to other entities, the names and tooltips of the pertaining controls have been updated to show this information.
=> Update entity and camera location controls

chunky/src/java/se/llbit/chunky/ui/controller/ResourcePackChooserController.java
Previously, Chunky would attempt to open the resource pack itself in the file explorer, which would fail if the file format of the resource pack were not supported by the system file explorer. This fix makes Chunky attempt to open the parent folder of the selected resource pack. Fixes #1381
=> Make Chunky open the parent folder of the selected resource pack

chunky/src/java/se/llbit/chunky/ui/render/tabs/EntitiesTab.java, chunky/src/res/se/llbit/chunky/ui/render/tabs/EntitiesTab.fxml
Closes #1325
I thought it fit better next to scale and head scale, as it's the position of the entity overall, not the position of any part
=> Add entity position fields to allow user to position the entity

chunky/build.gradle
As of #1110 we changed from publishing to `chunky-core` to `chunky`, which is possibly a change in default behaviour in the publish plugin.
It could've been defaulting to `archivesBaseName`, where it now defaults to the top level project `archivesBaseName`?
=> Fix pom publish regression from #1110

chunky/build.gradle
Causing inconsistent metadata errors in dependent projects
Would it be better to store the version somewhere? We don't actually store this anywhere at the moment, so I just hardcoded it
See this [chunky-editor build](https://github.com/chunky-dev/chunky-editor/runs/7527395032?check_suite_focus=true) as an example
```
> Could not resolve all files for configuration ':compileClasspath'.
> Could not resolve se.llbit:chunky-core:2.5.0-SNAPSHOT.
Required by:
project :
> Could not resolve se.llbit:chunky-core:2.5.0-SNAPSHOT.
> inconsistent module metadata found. Descriptor: se.llbit:chunky-core:2.5.0-SNAPSHOT.162.g94748109 Errors: bad version: expected='2.5.0-SNAPSHOT' found='2.5.0-SNAPSHOT.162.g94748109'
```
=> Fix pom version not matching actual version

README.md
Chunky supports Minecraft Java Edition 1.19.1; the readme was updated to indicate that.
=> Update Minecraft compatibility

lib/src/se/llbit/chunky/ui/ValidatingNumberStringConverter.java
This is a quick fix to a weird issue where we often update the text field with the internally stored value. Closes #1268
Currently on any focus loss, or enter press to an input field we set the text to a locale formatted string version of the current value in chunky.
So the current logic is:
1. User sets text, internal value is updated
2. Set text field to locale formatted version of the internal value
3. Text field has changed (by ourselves in the previous step), set internal value to re-parsed text value
kind of insane.
=> Fix always rounding to 3 decimal places

chunky/src/java/se/llbit/chunky/ui/elements/TextFieldLabelWrapper.java
fixes #1378 (best effort: is better now, but not perfect)
=> Fix initial text overflow for labeled text fields by scrolling to the end

chunky/src/java/se/llbit/chunky/resources/ResourcePackLoader.java
From [discord](https://discord.com/channels/541221265512464394/571769711402942467/1004066872918024192):
```
Exception in thread "main" java.util.zip.ZipError: zip END header not found
[...]
Chunky exited abnormally with exit value 1
```
This PR catches the `ZipError` and rethrows it as an `IOException`. In my testing this only happens in Java 8. This appears safe to catch despite being an `Error` (see [stackoverflow post](https://stackoverflow.com/a/51715939)).
=> Catch `ZipError` when loading resource packs.

.github/workflows/gradle.yml
Previously the `master` build was not a special case and would create an artifact tagged with `-DEV`. Change it to be tagged with `-SNAPSHOT`.
=> Fix master snapshot build tag.

chunky/src/res/se/llbit/chunky/ui/Chunky.fxml
I also made it match the size of the buttons below because that looks nice
old:
new:
=> Use the new number entry for the map coordinates

chunky/src/java/se/llbit/chunky/ui/ChunkMap.java
Fixes #1294. It's the only icon that uses a texture from the resource pack. Since we're going to remove this functionality from Chunky (at move it into a plugin), I don't think it's necessary to change the icon at this point.
=> Fix icon size of the delete selected chunks icon for larget resource packs.

chunky/src/java/se/llbit/chunky/ui/render/tabs/SkyTab.java
=> Fix sky mode settings not being shown after loading a scene.

chunky/src/java/se/llbit/chunky/renderer/scene/PreviewRayTracer.java
Just realized that the grid is supposed to be aligned to the chunks, like this:
=> Fix preview render grid not being aligned to chunks.

.github/workflows/gradle.yml
Now builds on the snapshot branch will properly be named `2.4.3-SNAPSHOT`.
Closes #1429
=> Fix `2.4.x` build tag.

chunky/src/res/se/llbit/chunky/ui/Chunky.fxml, chunky/src/res/se/llbit/chunky/ui/render/tabs/GeneralTab.fxml
The Y clip controls in the `Scene` tab and the `Map` tab were labeled to make it clearer where they take effect.
=> Change y clipping labels to make them more clear.

chunky/src/java/se/llbit/chunky/ui/controller/ResourcePackChooserController.java
fixes #1445 
The file browser for unlisted resource pack failed to open if .minecraft/resourcepacks directory did not exist.
Instead, it will now open at the filesystem root.
=> Don't fail to open file browser when resourcepacks directory is missing

chunky/src/java/se/llbit/chunky/ui/controller/ChunkyFxController.java, chunky/src/java/se/llbit/chunky/ui/controller/SceneChooserController.java, chunky/src/java/se/llbit/chunky/ui/dialogs/SceneChooser.java
Also fix being able to open multiple scene chooser windows at once.
I'm not entirely sure we're closing them correctly, `close()` actually just calls `hide()` internally. We might be slowly stacking up popup windows internally, not sure
=> Add Loading scenes list title to inform user

chunky/src/java/se/llbit/chunky/model/AABBModel.java, chunky/src/java/se/llbit/chunky/model/AnimatedQuadModel.java, chunky/src/java/se/llbit/chunky/model/QuadModel.java, chunky/src/java/se/llbit/chunky/model/Tint.java, chunky/src/java/se/llbit/chunky/ui/render/tabs/TexturesTab.java
This also changes the tinting to not tint every hit but only the final block hit color, resulting in less biome color lookups.
=> Fix single color textures not working with biome colors

chunky/src/java/se/llbit/chunky/renderer/SceneProvider.java, chunky/src/java/se/llbit/chunky/renderer/scene/AsynchronousSceneManager.java, chunky/src/java/se/llbit/chunky/renderer/scene/SceneManager.java, chunky/src/java/se/llbit/chunky/renderer/scene/SynchronousSceneManager.java, chunky/src/test/se/llbit/chunky/main/PluginApiTest.java, chunky/src/test/se/llbit/chunky/renderer/MockSceneProvider.java
For plugins like the denoiser plugin, it would be useful to keep track of scene refresh events (to invalidate auxiliary buffers for example). Currently this is only possible (without hacks) if the plugin registers a renderer and that renderer is being used.
=> Add scene refresh event plugin API.

chunky/src/java/se/llbit/chunky/main/Chunky.java, chunky/src/java/se/llbit/chunky/plugin/ContextMenuTransformer.java, chunky/src/java/se/llbit/chunky/ui/ChunkMap.java, chunky/src/java/se/llbit/chunky/ui/RenderCanvasFx.java
These transformers can be used to add more context menu items to the map and render displays. (ie. buttons for map editor plugin or show albedo/normal/beauty/denoised for denoiser).
=> Add context menu transformers for map and render view.

chunky/src/java/se/llbit/chunky/renderer/scene/PreviewRayTracer.java, chunky/src/java/se/llbit/chunky/renderer/scene/Sky.java, chunky/src/java/se/llbit/chunky/ui/render/tabs/LightingTab.java, chunky/src/res/se/llbit/chunky/ui/render/tabs/LightingTab.fxml
Closes #514.
- Fixed the `Sky light` control changing apparent sky brightness in render preview, but not in the path-traced render.
- Renamed `Sky light` to `Sky brightness`.
- Added an `Apparent sky brightness` control which acts independently from the `Sky brightness` control.
**New:**
Please tell me if I did anything wrong, and feel free to commit fixes, if any are needed.
=> Add an `Apparent sky brightness` control

chunky/src/java/se/llbit/chunky/ui/render/tabs/GeneralTab.java, chunky/src/res/se/llbit/chunky/ui/render/tabs/GeneralTab.fxml, chunky/src/res/se/llbit/chunky/ui/render/tabs/HelpTab.fxml, chunky/src/res/se/llbit/chunky/ui/render/tabs/LightingTab.fxml, chunky/src/res/se/llbit/chunky/ui/render/tabs/SkyTab.fxml
Fixes #1432.
- Reorganized the `Scene` tab; grouped related controls together.
- Renamed dump controls to "autosave" controls.
- Placed autosave controls into a collapsible panel akin to those in #1456.
- Added separators to the `Lighting` and `Sky & Fog` tabs to separate different groups of controls.
**Scene tab:**
**Lighting tab:**
**Sky & Fog tab:**
=> Reorganize `Scene` tab and add `<Separator />`s to the `Lighting` and `Sky & Fog` tabs

chunky/src/java/se/llbit/chunky/ui/render/tabs/WaterTab.java, chunky/src/res/se/llbit/chunky/ui/render/tabs/SkyTab.fxml, chunky/src/res/se/llbit/chunky/ui/render/tabs/WaterTab.fxml
Fixes #1454.
- Hide and collapse `Water world mode settings` panel if `Water world mode` is disabled.
- Hide and collapse `Procedural water settings` panel if `Procedural water` is disabled.
- Set the animated property of aforementioned panels and the `Sky mode settings` panel to false.
**Collapsed and hidden when disabled:**
**Expanded and shown when enabled:**
=> Automatically hide and collapse `Water` tab panels

chunky/src/java/se/llbit/chunky/renderer/scene/Sky.java, chunky/src/java/se/llbit/chunky/ui/render/tabs/SkyTab.java
Fixes #1388.
- Changed default cloud size to 12, to match Minecraft Fancy clouds.
- Changed cloud X offset range to (-256, 256).
- Changed cloud Y offset range to (-64, 320).
- Changed cloud Z offset range to (-256, 256).
- Added a tooltip to `Cloud size` control.
**New:**
=> Increase the range of cloud offset sliders and change default cloud size

chunky/src/java/se/llbit/chunky/renderer/projection/ProjectionMode.java, chunky/src/java/se/llbit/chunky/renderer/projection/stereo/ODSSinglePerspectiveProjector.java, chunky/src/java/se/llbit/chunky/renderer/projection/stereo/ODSVerticalSplitProjector.java, chunky/src/java/se/llbit/chunky/renderer/projection/stereo/ODSVerticalStackedProjector.java, chunky/src/java/se/llbit/chunky/renderer/projection/stereo/OmniDirectionalStereoProjector.java, chunky/src/java/se/llbit/chunky/renderer/scene/Camera.java
Adds a vertically split ODS projector which contains both eye's perspectives of a 360° image in a vertically split image.
This matches the way Google documented the 360° media format: [rendering documentation](https://developers.google.com/vr/jump/rendering-ods-content.pdf#page=7), [WebVR library documentation](https://developers.google.com/vr/discover/360-degree-media).
=> Add vertically stacked omni-directional stereo projector

chunky/src/java/se/llbit/chunky/renderer/scene/PathTracer.java, chunky/src/java/se/llbit/chunky/renderer/scene/Sky.java, chunky/src/java/se/llbit/chunky/renderer/scene/Sun.java, chunky/src/java/se/llbit/chunky/ui/render/tabs/LightingTab.java, chunky/src/res/se/llbit/chunky/ui/render/tabs/LightingTab.fxml
Fixes #1471.
Fixes #1472.
Fixes #1317.
Closes #54.
- Added a `Sky exposure` control, which changes both the sky brightness and the apparent sky brightness.
- The controls `Sky brightness` and `Apparent sky brightness` modify the values separately.
- Fixed `Apparent sky brightness` changing the apparent brightness of the sun in the path-traced render.
- Added an `Apparent sun brightness` control, which changes the apparent brightness of the texture of the sun. `Sun Intensity` and `Sun Luminosity` no longer change the apparent brightness of the sun.
- Fixed `Draw sun` disabling sunlight.
- Added `Modify sun texture by color`, which changes whether `Apparent sun color` has an effect on the texture of the sun.
- Added `Apparent sun color`, which has an effect on the sun texture if `Modify sun …
=> Add a `Sky exposure` control, fix the `Draw sun` control disabling sunlight, and add few new sun controls

chunky/src/java/se/llbit/chunky/ui/render/tabs/EntitiesTab.java, chunky/src/java/se/llbit/chunky/world/material/BeaconBeamMaterial.java
Previously, there was no way to change the `Metalness` material property for beacon beams. This PR adds a control to change that.
**GUI:**
**Effect:**
=> Add a `Metalness` control for beacon beams

chunky/src/java/se/llbit/chunky/renderer/scene/Sun.java
Fixes #993.
The preview now always appears as though the `Sun color` were white and the `Sun intensity` were 1.25.
**New:**
Please tell me if I did anything wrong, and feel free to commit fixes, if any are needed.
=> Remove effects of `Sun intensity` and `Sun color` on preview

chunky/src/java/se/llbit/chunky/renderer/scene/Camera.java, chunky/src/java/se/llbit/chunky/ui/RenderCanvasFx.java, chunky/src/java/se/llbit/chunky/ui/render/tabs/CameraTab.java, chunky/src/res/se/llbit/chunky/ui/render/tabs/CameraTab.fxml
Fixes #1396.
- Added a `Lock selected camera` control, which is associated with the separate cameras.
- The control disables many other controls in the `Camera` tab, and disables camera input from the `Render preview`.
**Disabled:**
**Enabled:**
Testing is appreciated.
=> Add a control to lock the camera angle.

chunky/src/java/se/llbit/chunky/renderer/scene/Sky.java
Partial fix for #1069.
Save sky color as an RGB object while maintaining backwards-compatibility with scenes saved in older Chunky versions.
**Old:**
```json
"color": [
0.0,
0.0,
0.0
],
```
**New:**
```json
"color": {
"red": 0.671875,
"green": 0.29656982421875,
"blue": 0.29656982421875
}
```
=> Save sky color as an RGB object

chunky/src/java/se/llbit/chunky/ui/render/settings/SkymapSettings.java
=> Make `Vertical resolution` box use no space when `Sky mode` is set to `Skymap (angular)`

chunky/src/java/se/llbit/chunky/renderer/scene/Sky.java, chunky/src/java/se/llbit/chunky/ui/render/tabs/SkyTab.java
- Renamed `Skymap (panoramic)` to `Skymap (equirectangular)`.
- Renamed `Skymap (spherical)` to `Skymap (angular)`.
- Fixed failure to load an angular skymap of a saved scene.
- Retain backwards-compatibility with scenes saved in older versions of Chunky.
=> Rename Skymap modes; fix scene loading issue

chunky/src/java/se/llbit/chunky/renderer/projection/ParallelProjector.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
Apply the parallel projection clipping fix to `computeAlpha`.
Fixes #1507 . Needs testing.
=> Potential fix for clipping with parallel projection and transparent sky.

chunky/src/java/se/llbit/chunky/renderer/scene/PathTracer.java
Fixes #1512.
Fixes #608.
Fixes #1231.
Test scene reflects emitters off a 100% specular floor:
Master:
PR:
Equivalent scene in Blender:
=> Carry energy through specular reflection, metallic reflection, and transmission.

launcher/src/se/llbit/chunky/launcher/ChunkyLauncher.java, launcher/src/se/llbit/chunky/launcher/JavaFxDownloads.java, launcher/src/se/llbit/chunky/launcher/JavaFxInstaller.java, launcher/src/se/llbit/chunky/launcher/JavaFxLocator.java
When JavaFX is not detected, the following installer will open:
The fields will attempt to auto-populate, however the user can change the fields if they are incorrect. Clicking on the `Download and Install` button will download the JavaFX sdk and extract it to `~/.chunky/javafx/`. The JavaFX finder has been modified to also look for this path.
This requires the update site to have a `javafx.json` file such as:
```json
[
{
"name": "Windows",
"regex": "Windows.*",
"archs": [
{
"name": "x64",
"regex": "amd64",
"url": "https://download2.gluonhq.com/openjfx/17.0.2/openjfx-17.0.2_windows-x64_bin-sdk.zip"
}
]
}
]
```
=> Add a simple JavaFX installer to the launcher.

chunky/src/test/se/llbit/chunky/main/PluginApiTest.java
When the test fails, the render manager stack trace generally looks like:
```
[java.base@17/java.lang.Object.wait(Native Method), java.base@17/java.lang.Object.wait(Object.java:338), app//se.llbit.chunky.renderer.scene.SynchronousSceneManager.awaitSceneStateChange(SynchronousSceneManager.java:291), app//se.llbit.chunky.renderer.DefaultRenderManager.run(DefaultRenderManager.java:247)]
```
This ensures that the render manager has properly shut down before starting the test.
Closes #1532
=> Fix issue where `PluginApiTest.testSetSceneResetListener` could fail randomly.

chunky/src/java/se/llbit/chunky/block/LightBlock.java, chunky/src/java/se/llbit/chunky/chunk/BlockPalette.java, chunky/src/java/se/llbit/chunky/model/LightBlockModel.java
- Reduced the size of the light block model from a full block to 1/2 block length cubed.
- Quadrupled default emittance values for light blocks to compensate.
Previously, light blocks would unnaturally fully illuminate any texture directly adjacent to it. By reducing the size of the model, this effect is eliminated.
**Old:**
**New: (actual results are similar; this is an older render)**
=> Reduce size of light block model

chunky/src/java/se/llbit/chunky/ui/ChunkMap.java, chunky/src/java/se/llbit/chunky/ui/dialogs/SelectChunksInRadiusDialog.java, chunky/src/java/se/llbit/chunky/world/ChunkSelectionTracker.java
Adds the ability to select a circle of chunks, within a radius. It's added to the right click menu on the map view
Additionally there's a config dialog available in the right click menu.
I can't figure out how to get the button to be square though, so it's a little chunkier than the rest of the icons. If any javafx wizard wants to fix that it'd be much appreciated
=> Add `Select chunks in radius` button, with configuration menu

chunky/src/java/se/llbit/chunky/chunk/BlockPalette.java
As mentioned in the issue, sea lanterns are light level 15 and therefore should have an emittance of 1.0.
=> Increase sea lantern light level

chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/world/Chunk.java, chunky/src/java/se/llbit/chunky/world/region/MCRegion.java
Previously I'd wanted to wait until I'd moved CubicChunks support out, and could rewrite the region parsing altogether.
This implementation isn't ideal but should be fine for now.
Ideally the first three commits should be squashed with the last being separate, let me know if I should do that or if it'll be done in the merge
=> Implement entity regions

chunky/src/java/se/llbit/chunky/renderer/scene/Fog.java, chunky/src/java/se/llbit/chunky/renderer/scene/FogLayer.java, chunky/src/java/se/llbit/chunky/renderer/scene/FogMode.java, chunky/src/java/se/llbit/chunky/renderer/scene/PathTracer.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/ui/render/tabs/AdvancedTab.java, chunky/src/java/se/llbit/chunky/ui/render/tabs/SkyTab.java
Completely rewrote the code for the fog so that fog can e.g. concentrate at the bottom, allowing for a wider range of effects. Fog density is modelled as a function of y. It is a sum of bell shaped sigmoid functions. Each fog layer has a center y coordinate, a density and a breadth value. Scattering works only for one layer so far. The scene JSON structure has been altered so that all fog data is stored in one JsonObject. The previous fog behavior is still supported and old scenes will be saved in the new format.
Import the following settings to test the new features:
`{"fog":{"mode":"LAYERED","layers":[{"y":62,"breadth":10,"density":1}]}}`
`{"fog":{"mode":"UNIFORM","uniformDensity":0.05}}`
`{"fog":{"mode":"NONE"}}`
A GUI implementation is still missing. So far the GUI still works the …
=> Add freely adjustable layered fog

chunky/src/java/se/llbit/chunky/renderer/scene/Fog.java
This behavior properly matches the original fog implementation and causes the builds to not fail.
=> Don't apply sky fog if fog mode is uniform and density is 0.

chunky/src/java/se/llbit/chunky/renderer/scene/EntityLoadingPreferences.java, chunky/src/java/se/llbit/chunky/ui/render/tabs/GeneralTab.java, chunky/src/res/se/llbit/chunky/ui/render/tabs/GeneralTab.fxml, lib/src/se/llbit/chunky/PersistentSettings.java
This is pretty trivial but since beacon beams are some of the most visually intrusive entities, it is often desirable to disable rendering them e.g. in a survival world. But currently they are lumped under "Other" which means that you would have to either disable rendering those other entities, or manually remove each beacon beam from the list, which is tedious in the case of my world where there are dozens to cover a 300 block radius.
Let me know if there are any other files that need to be changed, but in a quick test it seems to work.
=> Add "Beacon beam" entity toggle checkbox

chunky/src/java/se/llbit/chunky/map/MapTile.java, chunky/src/java/se/llbit/chunky/world/CubicWorld.java, chunky/src/java/se/llbit/chunky/world/World.java
`regionExists` is an expensive call in a cubic chunks world, as it must check for any 3d region in the entire column. The only choice being to iterate over all files in the directory which is very expensive for large worlds.
This PR specifies a Y range to check for regions, simplifying this massively.
`CubicWorld` already had this api, it's now moved into `World` and overridden.
=> Simple optimisation for Map View in CubicChunks worlds

chunky/src/java/se/llbit/chunky/renderer/DefaultRenderManager.java, chunky/src/java/se/llbit/chunky/renderer/ResetReason.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/ui/render/tabs/AdvancedTab.java, chunky/src/java/se/llbit/math/Octree.java, chunky/src/java/se/llbit/util/PositionalOutputStream.java, chunky/src/res/se/llbit/chunky/ui/render/tabs/AdvancedTab.fxml
When complete closes #1416
Complete:
- Switch octrees in an existing scene
- Progress bar while switching octrees
To do:
=> Add ability to switch octree implementations.

chunky/src/java/se/llbit/chunky/renderer/scene/Sun.java
Previously sun radius control was not properly updating in sun sampling. Moved sun radius initialization to `Sun.initSun()` to initialize the radius values properly.
=> Fix sun radius control on sun sampling.

chunky/src/java/se/llbit/chunky/entity/WallSignEntity.java
Wall signs didn't have the correct proportions, resulting in stretched textures. The position was slightly off too.
Left before, right after:
=> Fix wall sign dimension and position.

chunky/src/java/se/llbit/chunky/ui/render/tabs/AdvancedTab.java
Addresses #1594 in snapshot.
Initializing the `Advanced` tab was causing the octree implmentation control callback to be fired. This adds a check if the octree implementation actually changed before refreshing.
=> Prevent spurious refresh from the octree implementation control.

chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
(cherry picked from commit a0f937419b0a08a73bd0b3f70aa887dca0415fb6)
Addresses #1594 in stable.
=> Backport #1237. Fix scene reset from opening `Advanced` tab.

chunky/src/java/se/llbit/chunky/renderer/scene/Camera.java
Fixes #1584.
This change should prevent view speed from scaling with "FOV" in `Parallel` projection. The value of *0.5* which I used corresponds to a "FOV" value of about *57*.
=> Use a constant multiplier on `Parallel` projection

chunky/src/java/se/llbit/chunky/model/QuadModel.java, chunky/src/java/se/llbit/math/Quad.java
When I was working on the Decorated Pot model (#1602), I noticed that the Javadocs for the Quad constructors seem wrong, since as far as I can tell, the first three arguments are the bottom left, bottom right, and top left coordinates of the quad, respectively. Hopefully this helps explain - these are `Quad`s defined in `QuadModel`:
```
public static final Quad FULL_BLOCK_NORTH_SIDE = new Quad(
new Vector3(1, 0, 0),
new Vector3(0, 0, 0),
new Vector3(1, 1, 0),
new Vector4(0, 1, 0, 1));
```
```
public static final Quad FULL_BLOCK_EAST_SIDE = new Quad(
new Vector3(1, 0, 1),
new Vector3(1, 0, 0),
new Vector3(1, 1, 1),
new Vector4(0, 1, 0, 1));
```
```
public static final Quad FULL_BLOCK_TOP_SIDE = new Quad(
new Vector3(1, 1, 0),
new Vector3(0, 1, 0),
new Vector3(1, 1, 1),
new Vector4(1, 0, 1, …
```
=> Fix Javadoc for Quad constructors

chunky/src/java/se/llbit/chunky/map/WorldMapLoader.java, chunky/src/java/se/llbit/chunky/ui/ChunkMap.java
Previously players would always be rendered on the map view regardless of dimension.
Additionally, the map view wouldn't update on switching dimension and required the camera to move first
=> Fix dimension bugs in the map view

chunky/src/java/se/llbit/chunky/ui/render/tabs/AdvancedTab.java
Especially now that recent Intel and AMD processors have 24 (e.g. 13700K, 7900X) or even 32 (e.g. 13900K, 7950X) logical cores, the slider should probably match those numbers rather than its current hardcoded upper bound of 20. (Higher values could be entered with the text box, so really this is just a small "QOL" improvement.)
Before:
After:
=> Fix upper limit of "Render threads" slider

chunky/src/java/se/llbit/chunky/renderer/PathTracingRenderer.java, chunky/src/java/se/llbit/chunky/renderer/scene/PathTracer.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/ui/render/tabs/AdvancedTab.java, lib/src/se/llbit/chunky/PersistentSettings.java
Don't branch on the first few SPP to avoid some potential performance-related issues (such as pointed out [here](https://discord.com/channels/541221265512464394/1144538849582792847/1144538849582792847) on Discord) based on the square root of the branch count (arbitrary, but seems to work fine)
Examples:
If BC=5, sequence will be 1, 1, 1, 2, 5, 5, 5, ...
If BC=10, sequence will be 1, 1, 1, 1, 6, 10, 10, 10, ...
If BC=20, sequence will be 1, 1, 1, 1, 1, 15, 20, 20, 20, ...
Also, this sets the default branch count to 10 instead of 5 (since there are now fewer issues with that.)
=> Workaround for some potential drawbacks of ray branching

chunky/src/java/se/llbit/chunky/renderer/scene/PathTracer.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/ui/render/tabs/AdvancedTab.java, chunky/src/res/se/llbit/chunky/ui/render/tabs/AdvancedTab.fxml
Adds a checkbox that allows disabling the changes in #1513, in case some people prefer the previous behavior (not sure why they would, but just in case)
If disabled, it hides the transmissivity cap slider to reduce clutter.
=> Add option to disable "fancier translucency"

chunky/src/java/se/llbit/chunky/block/HangingSign.java, chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java, chunky/src/java/se/llbit/chunky/block/WallHangingSign.java, chunky/src/java/se/llbit/chunky/entity/Entity.java, chunky/src/java/se/llbit/chunky/entity/HangingSignEntity.java, chunky/src/java/se/llbit/chunky/entity/SignEntity.java, chunky/src/java/se/llbit/chunky/entity/WallHangingSignEntity.java, chunky/src/java/se/llbit/chunky/entity/WallSignEntity.java, chunky/src/java/se/llbit/chunky/model/Model.java, chunky/src/java/se/llbit/chunky/resources/SignTexture.java, chunky/src/java/se/llbit/chunky/resources/Texture.java, chunky/src/java/se/llbit/math/Quad.java
=> Add hanging signs.

chunky/src/java/se/llbit/chunky/renderer/scene/Fog.java, chunky/src/java/se/llbit/chunky/renderer/scene/FogLayer.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/ui/render/settings/LayeredFogSettings.java, chunky/src/java/se/llbit/chunky/ui/render/settings/UniformFogSettings.java, chunky/src/java/se/llbit/chunky/ui/render/tabs/SkyTab.java, chunky/src/res/se/llbit/chunky/ui/render/settings/LayeredFogSettings.fxml
Closes #1479.
Instead of creating a more complicated GUI as shown in the issue, I decided to create a simpler one.
**New:**
=> Add a GUI for layered fog

chunky/src/java/se/llbit/chunky/resources/SignTexture.java
Fixes #1632 (regression from #1600).
=> Fix NPE when rendering scenes with empty signs.

chunky/src/java/se/llbit/chunky/ui/render/tabs/EntitiesTab.java
Since the `leftHand` and `rightHand` entity gear fields do not actually have any effect, they have been hidden to avoid user confusion.
=> Hide broken entity gear fields

chunky/src/java/se/llbit/chunky/main/Chunky.java
=> Ensure the common thread pool has at least 2 threads.

chunky/src/java/se/llbit/chunky/resources/TexturePackLoader.java
When using `addSimpleTexture` or the `@TexturePath` annotation, textures are deduped by their filename (not their path). This causes eg. mangrove sign textures not to load if the `hanging/mangrove.png` texture was already loaded.
Fixes bamboo, cherry and mangrove signs. Regression probably introduced by #1600
=> Fix loading multiple textures with the same file name with addSimpleTexture.

chunky/src/java/se/llbit/chunky/entity/PlayerEntity.java
The Minecraft Fandom wiki has been forked to a new domain: minecraft.wiki. Learn more here: https://minecraft.wiki/w/Minecraft_Wiki:Moving_from_Fandom. This PR updates all URLs accordingly.
=> Update Minecraft wiki links to new domain

chunky/src/java/se/llbit/chunky/entity/HangingSignEntity.java, chunky/src/java/se/llbit/chunky/entity/SignEntity.java, chunky/src/java/se/llbit/chunky/entity/WallHangingSignEntity.java, chunky/src/java/se/llbit/chunky/entity/WallSignEntity.java, chunky/src/java/se/llbit/chunky/resources/SignTexture.java
This PR adds dyed signs. Dyes can be different on the front and back side of a sign.
Note that the 16 dye colors are different from the usual sign text colors (except for black). This means that we can't use the existing 4-bit palette for the dye color. In order to not have to add more bits to the palette, I made it so that if the palette contains a `1` but the text mask is `0`, the sign texture treats the pixel as _dye color_, which requires only 32 or 64 bits (ie. an enum value) per sign texture.
I extracted the colors via screenshots from dyed signs. They may be incorrect.
Closes #1625 and related to #789.
=> Add dyed signs.

chunky/src/java/se/llbit/chunky/renderer/export/Tiff32ExportFormat.java, chunky/src/java/se/llbit/imageformats/tiff/TiffFileWriter.java
- fixes #1491
- make it easier to extend TIFF format in the future
- add lots of documentation
- add the Chunky version to software metadata
- add date/timestamp to metadata
=> Fix TIFF format export

chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java, chunky/src/java/se/llbit/chunky/block/SolidNonOpaqueBlock.java, chunky/src/java/se/llbit/chunky/block/minecraft/CopperBulb.java, chunky/src/java/se/llbit/chunky/block/minecraft/Crafter.java, chunky/src/java/se/llbit/chunky/block/minecraft/RedstoneLamp.java, chunky/src/java/se/llbit/chunky/chunk/BlockPalette.java, chunky/src/java/se/llbit/chunky/model/Model.java, chunky/src/java/se/llbit/chunky/model/RotatableBlockModel.java, chunky/src/java/se/llbit/chunky/resources/Texture.java
This PR adds support for the additions in Minecraft snapshots 22w42a and 22w43a. These include:
**22w42a**
- the Crafter, with its `crafting` and `triggered` block states as well as 12 different orientations
**22w43a**
- Copper doors and trapdoors
- Chiseled copper and copper grate blocks
- Copper bulbs, a light source which acts as a flip-flop and has `lit` and `powered` block states
- All waxed and oxidized variants of the new copper blocks
- Tuff stairs, slabs, and walls
- Tuff bricks, with stair, slab, and wall variants
- Polished tuff, with stair, slab, and wall variants
- Chiseled tuff and tuff bricks
The built-in material defaults have been updated to give copper-like properties to the new copper blocks and the proper emittance values for the copper bulbs, which decreases from 15 …
=> 22w42a (crafter) and 22w43a (copper & tuff additions)

chunky/src/java/se/llbit/chunky/main/CommandLineOptions.java, launcher/src/se/llbit/chunky/launcher/ChunkyDeployer.java, launcher/src/se/llbit/chunky/launcher/ChunkyLauncher.java, launcher/src/se/llbit/chunky/launcher/VersionInfo.java, launcher/src/se/llbit/chunky/launcher/ui/UpdateDialogController.java, lib/src/se/llbit/chunky/launcher/LauncherSettings.java, lib/src/se/llbit/util/Util.java, releasetools/src/releasetools/ReleaseBuilder.java
It's 2023 and md5 is basically broken. This PR adds sha256 verification support. The `latest.json` for Chunky 2.4.5 on my server already contains the sha256 hashes.
Using `--dangerouslyDisableLibraryValidation`, checksum validation of libraries can now be disabled. This is a potential security issue and thus not recommended. It does help with local debugging and sharing custom Chunky versions though. Closes #1509
=> Add sha256 support for library verification to the launcher and a flag to disable it.

launcher/src/se/llbit/chunky/launcher/ui/ChunkyLauncherController.java
This should help with questions like this: https://old.reddit.com/r/chunky/comments/wjezxv/anyway_to_allow_chunky_to_use_more_then_16gb_of/
=> Use the available physical memory as upper memory limit for the slider in the launcher.

chunky/src/java/se/llbit/chunky/model/minecraft/CauldronModel.java, chunky/src/java/se/llbit/chunky/renderer/WaterShadingStrategy.java, chunky/src/java/se/llbit/chunky/renderer/scene/PathTracer.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/renderer/scene/SimplexWaterShader.java, chunky/src/java/se/llbit/chunky/renderer/scene/StillWaterShader.java, chunky/src/java/se/llbit/chunky/ui/render/tabs/WaterTab.java, chunky/src/res/se/llbit/chunky/ui/render/tabs/WaterTab.fxml, lib/src/se/llbit/chunky/PersistentSettings.java
Removed the `Still water` and `Procedural water` checkboxes and replaced them with a `Water shader` dropdown that contins options: `SIMPLEX` (default), `LEGACY`, and `STILL`. Also updated the persistent settings to support the new GUI. Scenes from older versions should have their water settings preserved when loaded.
**New:**
=> Use a ChoiceBox for water shader

chunky/src/java/se/llbit/chunky/renderer/postprocessing/HableToneMappingFilter.java, chunky/src/java/se/llbit/chunky/renderer/postprocessing/PostProcessingFilter.java, chunky/src/java/se/llbit/chunky/renderer/postprocessing/PostProcessingFilters.java, chunky/src/java/se/llbit/chunky/renderer/postprocessing/UE4ToneMappingFilter.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/ui/render/tabs/PostprocessingTab.java, chunky/src/java/se/llbit/util/Configurable.java, chunky/src/res/se/llbit/chunky/ui/render/tabs/PostprocessingTab.fxml
I just wanted to render a few example images for the post-processing section of the docs, and somehow went down this rabbit hole.
1. [UE4 Filmic Tonemapping](https://docs.unrealengine.com/4.26/en-US/RenderingAndGraphics/PostProcessEffects/ColorGrading/) is now implemented; basically configurable ACES, defaults to matching the ACES curve (UE4 legacy tone mapping preset is also in the code already)
2. Hable was wrong (missing Gamma Correction and arbitrary x16 exposure)
3. Compared [Hable's GDC talk](https://dokumen.tips/documents/hable-john-uncharted2-hdr-lighting.html?page=1) with the [blog post](http://filmicworlds.com/blog/filmic-tonemapping-operators/) and noticed that there were different parameters; added presets for both
4. Hable and UE4 Filmic Tonemaps can now be configured ~~(JSON …
=> Add UE4 filmic tone mapping and make Hable tone mapping configurable.

chunky/src/java/se/llbit/chunky/chunk/BlockPalette.java, chunky/src/java/se/llbit/chunky/renderer/scene/PathTracer.java, chunky/src/java/se/llbit/math/Ray.java
As has been discussed previously (#1555, #1549), the apparent brightness of emitters when viewed directly does not scale with their emittance. While investigating this, it became clear that there was a deeper issue here. See this render done on master:
Emitter intensity is set to 0, so the blocks themselves shouldn't be lit up at all. But not only are they lit up, they are somehow slightly illuminating the scene. To simplify things, consider the case where all surfaces are diffuse. Looking at the relevant code:
`indirectEmitterColor` and `next.emittance` will always be zero, and `emittance` is forced to be zero after the first diffuse reflection (which as far as I can tell is just a workaround that makes things look less wrong). Thus, everything but the emitters themselves should be dark, …
=> Simplify emitter logic and make it more correct

chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
Due to an oversight, I only made regular copper grates support transparency, not any of the oxidized variants:
(second image is on the emitter mapping branch just because that's what I had easily available)
=> fix exposed, weathered, and oxidized copper grates

chunky/src/java/se/llbit/chunky/main/Chunky.java, chunky/src/java/se/llbit/chunky/renderer/export/PfmExportFormat.java, chunky/src/java/se/llbit/chunky/renderer/export/PictureExportFormat.java, chunky/src/java/se/llbit/chunky/renderer/export/PngExportFormat.java, chunky/src/java/se/llbit/chunky/renderer/export/Tiff32ExportFormat.java, chunky/src/java/se/llbit/chunky/renderer/scene/AlphaBuffer.java, chunky/src/java/se/llbit/chunky/renderer/scene/PreviewRayTracer.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/ui/controller/ChunkyFxController.java, chunky/src/java/se/llbit/chunky/ui/render/tabs/AdvancedTab.java, chunky/src/java/se/llbit/imageformats/png/PngFileWriter.java, chunky/src/java/se/llbit/imageformats/tiff/IFDTag.java, chunky/src/java/se/llbit/imageformats/tiff/TiffFileWriter.java
- refactored alpha channel computation and storage
- renamed some PictureExportFormat stuff and replaced `isTransparencySupported` with `transparencyType`
- added TIFF alpha channel export (#1651)
- PR based on top of PR 1659
=> TIFF alpha channel

chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java, chunky/src/java/se/llbit/chunky/block/minecraft/Grass.java, chunky/src/java/se/llbit/chunky/resources/TexturePackLoader.java
As of 1.20.3-pre2, grass now has completed its journey from tallgrass over grass to short_grass – without changing its size. :rofl:
=> Rename grass to short_grass.

chunky/src/java/se/llbit/chunky/renderer/scene/PathTracer.java, chunky/src/java/se/llbit/math/Ray.java
Chunky would rely `Ray.set(Ray)` to increase the depth, however different routines calls this a different amount of times leading to different ray depths in a scene. Here I have removed that change and made ray depth increase explicitly to successive frames in `PathTracer.pathTrace`.  Currently this does  not explicitly change the output, but it could be a easy mistake in the future or if the ray depth is needed in other parts of the code.
=> Homogenize Depth

chunky/src/java/se/llbit/chunky/ui/controller/SceneChooserController.java
An unchecked call on the Optional result of `Alert#showAndWait()` may throw an exception at run time.
This commit refactors it to one of the recommended approaches to safely get its value [here](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/Alert.html).
=> Fix for possible crash in SceneChooserController.java

launcher/src/se/llbit/chunky/launcher/ui/ChunkyLauncherController.java
To reproduce this condition, remove your Chunky config and all versions (eg. rename your chunky directory) and start the launcher.
* If the launcher is outdated, only the launcher update dialog is shown (and no Chunky update dialog)
* If the launcher is up to date, the Chunky update dialog is shown, cancel it
* If you now try to launch, it will yell at you (with this PR applied, it will search for updates instead)
Fixes #1304
Cc @Peregrine05
=> Search for updates instead of telling the user if no versions are installed when trying to launch Chunky.

chunky/src/java/se/llbit/chunky/block/AbstractModelBlock.java, chunky/src/java/se/llbit/chunky/block/Block.java, chunky/src/java/se/llbit/chunky/block/legacy/blocks/LegacyFlowerPot.java, chunky/src/java/se/llbit/chunky/block/legacy/blocks/LegacyVine.java, chunky/src/java/se/llbit/chunky/model/AABBModel.java, chunky/src/java/se/llbit/chunky/model/BlockModel.java, chunky/src/java/se/llbit/chunky/model/QuadModel.java, chunky/src/java/se/llbit/chunky/model/Tint.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/renderer/scene/biome/BiomeBlendingUtility.java, chunky/src/java/se/llbit/chunky/renderer/scene/biome/ChunkBiomeBlendingHelper.java, chunky/src/java/se/llbit/chunky/ui/render/tabs/TexturesTab.java, chunky/src/java/se/llbit/math/structures/Position3d2IntPackedArray.java, chunky/src/res/se/llbit/chunky/ui/render/tabs/TexturesTab.fxml
This PR improves performance of doing biome blending during chunk loading. 
The combined time of step 3 and 4 (loading chunks and finalization ; biome blending occurs during step 4) has roughly been halved based on my rough timings. (Sorry, no precise timings provided, I've been winging it a bit). 
The improved performance and the improved asymptotic complexity of blur make it reasonable to do blur bigger than 3*3*3 so that's now possible and exposed in the UI. 
As an added bonus that wasn't really intentional, memory usage has decreased when using trivial 3D biome structure (by virtue of not storing biome color for every block, more on that later).
The improved performances are achieved for 3 reasons:
- When possible a 2D blur is used instead of a 3D one. To know when using a 2D blur can …
=> Improve biome blending in 3D

chunky/src/java/se/llbit/chunky/renderer/PreviewRenderer.java, chunky/src/java/se/llbit/chunky/ui/controller/ChunkyFxController.java, chunky/src/res/se/llbit/chunky/ui/Chunky.fxml
The current render status pane is somewhat messy with odd and inconsistent formatting, leading to issues like #1213, where `Rendering: 5 of 7` can be misinterpreted as _currently_ rendering 5 of 7. I tried to make it overall more readable and intuitively organized.
This (mostly) fixes #1213. It can still be misinterpreted, but it should be somewhat clearer without having to add additional visual clutter like "5 of 7 done".
I've attached before/after images below for comparison.
=> Clarify render status UI

chunky/src/java/se/llbit/chunky/renderer/scene/biome/Trivial2dBiomeStructure.java, chunky/src/java/se/llbit/chunky/renderer/scene/biome/Trivial3dBiomeStructure.java, chunky/src/java/se/llbit/util/Registerable.java
Possible values are:
* `Active` - not deprecated
* `Deprecated` - use is discouraged but still an option
* `Hidden` - hidden and exists only for backwards compatibility
The intention is that in the future `Hidden` items will be hidden in the UI and `Deprecated` items will have some sort of indicator / note.
=> Add deprecation status to `Registerable`.

chunky/src/java/se/llbit/chunky/renderer/scene/PathTracer.java
The problem is that `Fancier translucency` isn't using the material's texture brightness to determine how much light should be reflected diffusely vs. absorbed. With this change, a translucent white block with e.g. 49% opacity will now reflect 51% of light and absorb 0%, instead of reflecting 30% and then absorbing 21% (30% of 70%).
This fixes the white furnace test - before:
After:
=> Fix loss of energy when passing through translucent white blocks when fancier translucency is enabled

chunky/src/java/se/llbit/chunky/map/MapTile.java, chunky/src/java/se/llbit/chunky/world/ChunkPosition.java, chunky/src/java/se/llbit/chunky/world/ChunkSelectionTracker.java
On slower computers loading very large maps can take a long time, this PR allows chunks to be selected even if they're empty.
To clarify: `EmptyChunk`s only exist if the region they're within exists. `EmptyRegionChunk`s still cannot be selected.
=> Allow empty chunks to be selected if their region exists

.github/workflows/gradle.yml
This will speed up the Actions by ~2 minutes. If someone needs the javadoc, they can always build it by themselves.
=> Do not upload javadoc as artifact in gh actions.

build.gradle, launcher/build.gradle, launcher/src/se/llbit/chunky/launcher/ui/UpdateDialogController.java
Fixes jumbled status cell entries after downloading missing dependencies / updates.
Bug was caused by incorrect use of JavaFX (common mistake, I did the same multiple times).
Also made the launcher launchable as a Gradle task (application plugin) and cached the status icons, instead of loading them on every status change.
=> [Launcher] Fix jumbled download status column after updating libraries

launcher/src/se/llbit/chunky/launcher/JavaFxDownloads.java
HttpURLConnection does not handle redirects from HTTP to HTTPS. This PR fixes being unable to fetch JavaFX versions from the update site when a redirect across protocols occurs. Handles the HTTP 307 and 308 responses by following the redirect.
This leaves only HTTP 300 and 304 unhandled. 300 could be handled by choosing the Location field if it exists on the response. 304 should never be seen here and would require caching a previous response.
=> Fix HTTP Redirects in the launcher when fetching JFX versions

chunky/src/java/se/llbit/chunky/entity/StandingBanner.java
Found a bug while working on #1707, which also affects stable Chunky.
Before:
After:
=> Fix banner pattern alpha channel being ignored.

README.md, licenses/semver4j.txt
Solves #1700
Lists Semver4j as third party dependency in README and ads Semver4j's MIT license.
=> Include Semver4j in README

launcher/src/se/llbit/chunky/launcher/ChunkyLauncher.java, lib/src/se/llbit/chunky/resources/SettingsDirectory.java
Solves: #1720
This prevents a FirstTimeSetupDialog GUI from being opened if a `chunky.home` system property is specified by the user.
=> Fix FirstTimeSetupDialog when chunky.home is set

build.gradle, chunky/build.gradle, chunky/src/test/se/llbit/chunky/block/SkullTextureTest.java, chunky/src/test/se/llbit/chunky/chunk/BlockPaletteTest.java, chunky/src/test/se/llbit/chunky/entity/MarshallingTest.java, chunky/src/test/se/llbit/chunky/main/OptionHandlerTest.java, chunky/src/test/se/llbit/chunky/main/PluginApiTest.java, chunky/src/test/se/llbit/chunky/nbt/NBTTest.java, chunky/src/test/se/llbit/chunky/renderer/BlankRenderTest.java, chunky/src/test/se/llbit/chunky/renderer/renderdump/RenderDumpTest.java, chunky/src/test/se/llbit/chunky/renderer/scene/SceneManagerTest.java, chunky/src/test/se/llbit/chunky/renderer/scene/SceneTest.java, chunky/src/test/se/llbit/chunky/resources/AnimatedTextureTest.java, chunky/src/test/se/llbit/fxutil/GroupedChangeListenerTest.java, chunky/src/test/se/llbit/log/LogTest.java, chunky/src/test/se/llbit/math/MutableAABBTest.java, chunky/src/test/se/llbit/math/QuickMathTest.java, chunky/src/test/se/llbit/util/RingBufferTest.java, chunky/src/test/se/llbit/util/WeakInternerTest.java, launcher/build.gradle, lib/build.gradle, settings.gradle
I switched from google truth to assertj, as truth depends heavily on junit4. No code changes thankfully, only imports (apis we use are identical)
Only thing of note: `QuickMathTest#testAbs_1` was previously incorrect (and now fails, relevant part is commented out)
Probably best not to squash as the two commits are entirely separate
=> Update to JUnit5, Update to J17 and J21 for tests

chunky/src/java/se/llbit/chunky/entity/PaintingEntity.java, chunky/src/java/se/llbit/chunky/resources/DataPackUtil.java, chunky/src/java/se/llbit/chunky/resources/ResourcePackBiomeLoader.java, chunky/src/java/se/llbit/chunky/resources/ResourcePackLoader.java, chunky/src/java/se/llbit/chunky/resources/ResourcePackPaintingLoader.java
=> Add support for loading dynamic paintings from resource packs.

chunky/src/java/se/llbit/chunky/renderer/scene/PathTracer.java
Fixes #1718
Before: pure black pixels are transparent
After: pure black pixels are opaque
=> Fix "transmission without refraction" logic

launcher/build.gradle, lib/build.gradle
Neither oracle nor azul include jfx on both windows & linux in their java 8 jdks.
Corretto documentation says that its [mac jdk doesn't include jfx](https://aws.amazon.com/corretto/faqs/), so we still have a build problem on apple systems
If someone can tell me a mac jdk8 that includes jfx I'll PR another fix.
=> Fix build issues on windows due to azul not including JFX on windows

chunky/src/java/se/llbit/chunky/renderer/scene/PathTracer.java
When emitter sampling is enabled and `Prevent normal emitter when using emitter sampling` is checked, direct hits on emitters don't glow. This fixes that.
Master:
Fix:
=> Fix emitters with emitter sampling.

chunky/src/java/se/llbit/chunky/ui/controller/ChunkyFxController.java
Previously it was always the buffered one, it never output any INFO level logs to anywhere.
This makes them output to the console if enabled, which was the behaviour before the buffered receiver
`INFO` logs are hidden behind the `logLevel` system property, so it's not surprising that no one noticed
=> Fix not logging any INFO level messages in UI mode

chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/math/Octree.java, chunky/src/test/se/llbit/math/OctreeTest.java, chunky/src/test/se/llbit/math/QuickMathTest.java, chunky/src/test/se/llbit/testutil/TestUtils.java, lib/src/se/llbit/math/QuickMath.java
Due to an incorrect maxDimension calculation
This happened because we were trying to set a cube of height 16 less than 16 blocks from the edge of the octree. (which was then masked to within bounds and so wrapped)
Thoughts on adding some assertions in packedoctree that the arguments are even valid?
=> Fix blocks overflowing over the top of octree bounds

chunky/src/java/se/llbit/chunky/renderer/ConsoleProgressListener.java, chunky/src/java/se/llbit/chunky/renderer/DefaultRenderManager.java, chunky/src/java/se/llbit/chunky/renderer/PreviewRenderer.java, chunky/src/java/se/llbit/chunky/ui/controller/ChunkyFxController.java, chunky/src/java/se/llbit/util/ProgressListener.java, chunky/src/java/se/llbit/util/TaskTracker.java, chunky/src/test/se/llbit/chunky/renderer/renderdump/RenderDumpTest.java
=> Show time elapsed for all tasks and use Duration for the duration and eta.

chunky/src/java/se/llbit/chunky/world/Chunk.java, chunky/src/java/se/llbit/chunky/world/CubicDimension.java, chunky/src/java/se/llbit/chunky/world/Dimension.java, chunky/src/java/se/llbit/chunky/world/ImposterCubicChunk.java
Some WorldPainter worlds have their ChunkDataVersion set to a version prior to minecraft's support for worlds with >=256 height.
This PR changes how we create `ChunkData` objects to be based on the actual block range found in a chunk, rather than its version
=> Fix ChunkDataVersion issues with third party applications

README.md, chunky/src/java/se/llbit/chunky/ui/controller/CreditsController.java, chunky/src/res/se/llbit/chunky/ui/dialogs/Credits.fxml, launcher/build.gradle, launcher/src/se/llbit/chunky/launcher/ChunkyLauncher.java, launcher/test/se/llbit/chunky/launcher/ChunkyLauncherCliParseTest.java, lib/src/se/llbit/chunky/HelpCopyright.java, lib/src/se/llbit/chunky/cli/CliUtil.java
=> Improve launcher command line interface.

chunky/src/java/se/llbit/chunky/renderer/scene/Fog.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/renderer/scene/sky/Sky.java, chunky/src/java/se/llbit/chunky/renderer/scene/sky/Sun.java, chunky/src/java/se/llbit/chunky/ui/render/tabs/SkyTab.java, chunky/src/java/se/llbit/chunky/world/material/BeaconBeamMaterial.java, chunky/src/java/se/llbit/math/ColorUtil.java, chunky/src/java/se/llbit/util/JsonUtil.java, chunky/src/test/se/llbit/chunky/renderer/BlankRenderTest.java, chunky/src/test/se/llbit/math/ColorUtilTest.java
=> Scene file improvements

chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java, chunky/src/java/se/llbit/chunky/block/minecraft/OrientableTrapdoor.java, chunky/src/java/se/llbit/chunky/model/minecraft/OrientableTrapdoorModel.java
Wondered why pale_oak_trapdoor didn't look right. Turns out there have been two different trapdoor models for a while, and Chunky only supported one of them.
=> Fix trapdoor textures.

chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java, chunky/src/java/se/llbit/chunky/block/minecraft/CreakingHeart.java, chunky/src/java/se/llbit/chunky/block/minecraft/PaleMossCarpet.java, chunky/src/java/se/llbit/chunky/entity/HangingSignEntity.java, chunky/src/java/se/llbit/chunky/entity/SignEntity.java, chunky/src/java/se/llbit/chunky/model/minecraft/FlowerPotModel.java, chunky/src/java/se/llbit/chunky/model/minecraft/PaleMossCarpetModel.java, chunky/src/java/se/llbit/chunky/resources/Texture.java, chunky/src/java/se/llbit/chunky/world/biome/Biomes.java
=> Add 24w40a blocks and pale garden biome

chunky/src/java/se/llbit/chunky/renderer/scene/OctreeFinalizer.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
This is not the fastest way to do this, perhaps we could add in a single value cache for the most recently checked chunk?
Though as it's only on water in finalisation I decided against optimising for now
=> Fix fluids shape on octree edge

chunky/src/java/se/llbit/chunky/renderer/scene/AlphaBuffer.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
=> Fix transparent sky not working with render regions.

chunky/src/java/se/llbit/chunky/block/minecraft/Comparator.java, chunky/src/java/se/llbit/chunky/block/minecraft/RedstoneTorch.java, chunky/src/java/se/llbit/chunky/block/minecraft/RedstoneWallTorch.java, chunky/src/java/se/llbit/chunky/block/minecraft/Repeater.java, chunky/src/java/se/llbit/chunky/block/minecraft/Torch.java, chunky/src/java/se/llbit/chunky/block/minecraft/WallTorch.java, chunky/src/java/se/llbit/chunky/model/minecraft/ComparatorModel.java, chunky/src/java/se/llbit/chunky/model/minecraft/ComparatorModel1212.java, chunky/src/java/se/llbit/chunky/model/minecraft/RedstoneRepeaterModel.java, chunky/src/java/se/llbit/chunky/model/minecraft/RedstoneRepeaterModel1212.java, chunky/src/java/se/llbit/chunky/model/minecraft/RedstoneTorchModel.java, chunky/src/java/se/llbit/chunky/model/minecraft/RedstoneWallTorchModel.java, chunky/src/java/se/llbit/chunky/model/minecraft/TorchModel.java
This adds the new redstone torch model from Minecraft 1.21.2 (added in 24w33a). Credits to @Peregrine05 :clap: 
Related #1780
Closes #1781 and #1782
Once this PR updates the comparator and repeater models, this also fixes #1783
=> Add new redstone torch model

chunky/src/java/se/llbit/chunky/block/minecraft/Leaves.java
=> Fix map color of spurce and birch leaves.

chunky/src/java/se/llbit/chunky/main/Chunky.java
=> Fix crash when loading plugins in headless mode if JavaFX is not installed

chunky/src/java/se/llbit/chunky/entity/ChickenEntity.java, chunky/src/java/se/llbit/chunky/entity/CowEntity.java, chunky/src/java/se/llbit/chunky/entity/Dyeable.java, chunky/src/java/se/llbit/chunky/entity/Entity.java, chunky/src/java/se/llbit/chunky/entity/MooshroomEntity.java, chunky/src/java/se/llbit/chunky/entity/PigEntity.java, chunky/src/java/se/llbit/chunky/entity/Saddleable.java, chunky/src/java/se/llbit/chunky/entity/SheepEntity.java, chunky/src/java/se/llbit/chunky/entity/SquidEntity.java, chunky/src/java/se/llbit/chunky/entity/Variant.java, chunky/src/java/se/llbit/chunky/model/builder/BoxModelBuilder.java, chunky/src/java/se/llbit/chunky/renderer/scene/EntityLoadingPreferences.java, chunky/src/java/se/llbit/chunky/renderer/scene/SceneEntities.java, chunky/src/java/se/llbit/chunky/resources/Texture.java, chunky/src/java/se/llbit/chunky/ui/render/tabs/EntitiesTab.java, chunky/src/java/se/llbit/chunky/ui/render/tabs/GeneralTab.java, chunky/src/java/se/llbit/chunky/world/material/DyedTextureMaterial.java, chunky/src/java/se/llbit/math/Transform.java, chunky/src/java/se/llbit/math/Vector3.java, chunky/src/res/se/llbit/chunky/ui/render/tabs/GeneralTab.fxml, lib/src/se/llbit/chunky/PersistentSettings.java
This PR is the first of a (probably very long) series where I'll be adding entities. This one adds Sheep, Cows, Pigs, Chickens, Mooshrooms, and Squids and sets up interfaces to accommodate future mobs. 
All mobs are fully poseable via the Entities Tab. 
Some mobs have more specific customization available in the Entities tab:
- Sheep can be recolored and sheared/unsheared
- Pigs can be Saddled
- Mooshrooms' mushrooms can be hidden and their Variant can be changed.
Built from #1719 
Related to #41
=> Mobs and Entities Part 1 (Sheep, Cows, Pigs, Chickens, Mooshrooms, Squids)

chunky/src/java/se/llbit/chunky/ui/render/tabs/GeneralTab.java
Noticed I forgot Squids in the Select/Deselect All buttons for the Load Entities drop down in the Scene tab. This fixes those buttons not correctly changing the setting.
=> Fix select/deselect all for Squids

chunky/src/java/se/llbit/chunky/renderer/scene/AsynchronousSceneManager.java, chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java, chunky/src/java/se/llbit/chunky/renderer/scene/SceneManager.java, chunky/src/java/se/llbit/chunky/renderer/scene/SynchronousSceneManager.java, chunky/src/java/se/llbit/chunky/ui/ChunkMap.java, chunky/src/java/se/llbit/chunky/ui/render/tabs/GeneralTab.java, chunky/src/java/se/llbit/chunky/world/ChunkSelectionTracker.java
Merge after #1256
Rather than loading chunks in the order they appear in the chunk list, now load chunks region by region, which should lead to much better region loading performance, also the task scheduling has been cleaned up.
Maybe some minor improvements cache-wise for the octree due to loading chunks close to each other too
Still need to create some `ChunkData` cache, as each chunk currently allocates one
=> Load chunks per-region in Scene#loadChunks

chunky/src/java/se/llbit/chunky/resources/texturepack/ConditionalTextures.java, chunky/src/java/se/llbit/chunky/resources/texturepack/JsonFontTextureLoader.java
Fixed #1724 (ie. [Conquest_](https://www.curseforge.com/minecraft/texture-packs/conquest_/files/5741192) now works fine).
=> Fix crash when loading some resource packs.

chunky/src/java/se/llbit/chunky/model/AABBModel.java
Cherry pick from #1570 which should improve AABB model performance back to 2.4.x levels
=> Improve AABB performance
