- chunky/src/java/se/llbit/chunky/world/Block.java
> Now "End Rod" emits light

- ChangeLog.txt
This tiny feature was missing in the changelog.
> Add new post-processors to the changelog

- chunky/src/java/se/llbit/chunky/block/Block.java
- chunky/src/java/se/llbit/chunky/renderer/scene/OctreeFinalizer.java
> Fixed red sandstone and purpur stairs rendering

- chunky/src/java/se/llbit/chunky/renderer/scene/OctreeFinalizer.java
- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
> Fix and improve invisible block handling

- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
- chunky/src/java/se/llbit/chunky/ui/render/PostprocessingTab.java
> Threaded postprocessing

- chunky/src/java/se/llbit/chunky/renderer/projection/ShiftProjector.java
- chunky/src/java/se/llbit/chunky/renderer/scene/Camera.java
- chunky/src/java/se/llbit/chunky/renderer/scene/CameraPreset.java
- chunky/src/java/se/llbit/chunky/ui/render/CameraTab.java
- chunky/src/res/se/llbit/chunky/ui/render/CameraTab.fxml
> Add camera lense shift via a wrapped projector.

- chunky/src/java/se/llbit/chunky/block/Chest.java
- chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
- chunky/src/java/se/llbit/chunky/model/ChestModel.java
- chunky/src/java/se/llbit/chunky/resources/BitmapImage.java
- chunky/src/java/se/llbit/chunky/resources/TexturePackLoader.java
- chunky/src/java/se/llbit/chunky/resources/texturepack/AllTextures.java
- chunky/src/java/se/llbit/chunky/resources/texturepack/ChestTexture.java
- chunky/src/java/se/llbit/chunky/resources/texturepack/ConditionalTextures.java
- chunky/src/java/se/llbit/chunky/resources/texturepack/LargeChestTexture.java
- chunky/src/java/se/llbit/chunky/resources/texturepack/SplitLargeChestTexture.java
> Fix chest textures

- chunky/src/java/se/llbit/chunky/resources/TexturePackLoader.java
- chunky/src/java/se/llbit/chunky/ui/ChunkyFxController.java
- chunky/src/java/se/llbit/chunky/ui/ResourceLoadOrderEditor.java
> Texturepack improvements

- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
- chunky/src/java/se/llbit/chunky/ui/ChunkMap.java
- chunky/src/java/se/llbit/chunky/ui/ChunkyFxController.java
- chunky/src/java/se/llbit/chunky/world/ChunkSelectionTracker.java
> Improve chunk selection

- chunky/src/java/se/llbit/chunky/block/DragonEgg.java
- chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
- chunky/src/java/se/llbit/chunky/model/DragonEggModel.java
> Add dragon egg and update its model

- chunky/src/java/se/llbit/chunky/ui/ChunkyFxController.java
- chunky/src/java/se/llbit/chunky/ui/ResourceLoadOrderEditor.java
- chunky/src/java/se/llbit/chunky/ui/SceneChooserController.java
- chunky/src/java/se/llbit/chunky/ui/render/AdvancedTab.java
- chunky/src/java/se/llbit/chunky/ui/render/EntitiesTab.java
- chunky/src/java/se/llbit/chunky/ui/render/Poser.java
- chunky/src/java/se/llbit/chunky/ui/render/SkyboxSettings.java
- chunky/src/java/se/llbit/chunky/ui/render/SkymapSettings.java
- launcher/src/se/llbit/chunky/launcher/ui/PluginManagerController.java
`setSelectedExtensionFilter` has no effect if that filter isn't added yet so file filters didn't work.
> Fix file filters

- chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
The bottom texture was changed in 20w19a.
> Update the bottom texture of blackstone.

- chunky/src/java/se/llbit/chunky/main/CommandLineOptions.java
- chunky/src/java/se/llbit/util/MCDownloader.java
> Update the minecraft downloader to fix downloading newer versions.

- chunky/src/java/se/llbit/chunky/map/MapBuffer.java
> Fix exception in map view if the view is updated while painting.

- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
- chunky/src/java/se/llbit/chunky/renderer/scene/SynchronousSceneManager.java
- chunky/src/java/se/llbit/chunky/ui/ChunkyFxController.java
- chunky/src/java/se/llbit/chunky/ui/render/GeneralTab.java
- chunky/src/res/se/llbit/chunky/ui/render/GeneralTab.fxml
> Add a button to restore the default scene settings.

- chunky/src/java/se/llbit/chunky/main/Chunky.java
- chunky/src/java/se/llbit/chunky/ui/ChunkyFxController.java
- chunky/src/java/se/llbit/chunky/ui/render/GeneralTab.java
- chunky/src/java/se/llbit/chunky/world/Chunk.java
- chunky/src/java/se/llbit/chunky/world/listeners/ChunkUpdateListener.java
> Add some warnings, disable reload chunks button if no chunks are loaded

- chunky/src/java/se/llbit/chunky/entity/PlayerEntity.java
Fixes https://github.com/leMaik/chunky/issues/13
> Fix player head rotation origin.

- chunky/src/java/se/llbit/chunky/entity/PlayerEntity.java
> Ignore elytra for now instead of rendering broken chest armor skins.

- chunky/src/java/se/llbit/chunky/block/BlastFurnace.java
- chunky/src/java/se/llbit/chunky/block/Furnace.java
- chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
- chunky/src/java/se/llbit/chunky/block/Smoker.java
- chunky/src/java/se/llbit/chunky/chunk/BlockPalette.java
> Make lit furnaces, smokers and blast furnaces emitters

- chunky/src/java/se/llbit/chunky/ui/ChunkMap.java
I was working a bit on the map drawing today so aligned the selection.
Fixes #614 
The fix is a bit strange, especially the part where I had  to offset by one block for x but not for z but it seems to work fine
> Align selection rectangle with chunks

- chunky/src/java/se/llbit/chunky/renderer/RenderContext.java
- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
- chunky/src/java/se/llbit/chunky/renderer/scene/SynchronousSceneManager.java
> Don't create scene directories if nothing is saved

- chunky/src/java/se/llbit/chunky/renderer/scene/Camera.java
> Fix Position & Orientation tab not updating when camera moved in map

- chunky/src/java/se/llbit/chunky/block/Chain.java
- chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
- chunky/src/java/se/llbit/chunky/model/ChainModel.java
1.16.2-pre1 included a change to chains that allows for X/Z alignment. This PR adds that functionality to Chunky.
> Update chain model for 1.16.2-pre1

- chunky/src/java/se/llbit/chunky/ui/RenderCanvasFx.java
Fixes the missing guides noted in #653 however more work would be required to add additional.
Used the guide code found in the 1.4.5 release as a template. Hopefully it's up to standard.
> Readded rule of third guides

- chunky/src/java/se/llbit/chunky/renderer/RenderManager.java
Fixes #654, I'll wait for confirmation from @stormboomer before merging this PR.
> Change job ids to long to fix deadlocks after long render times.

- chunky/src/java/se/llbit/chunky/entity/HeadEntity.java
I forgot the y offset yesterday to textured heads attached to a wall were at the bottom of the block.
Before: 
After:
> Fix wall head position

- chunky/src/java/se/llbit/chunky/entity/PlayerEntity.java
> Fix missing turtle helmet texture.

- chunky/src/java/se/llbit/chunky/entity/HeadEntity.java
- chunky/src/java/se/llbit/chunky/entity/PlayerEntity.java
I'll wait for feedback on this one. The hat size change is tiny but the helmet size change is pretty significant. I believe it looks like ingame now, though.
> Increase hat and helmet sizes

- chunky/src/java/se/llbit/chunky/resources/HDRTexture.java
- chunky/src/java/se/llbit/chunky/resources/PFMTexture.java
- chunky/src/java/se/llbit/chunky/world/World.java
- chunky/src/java/se/llbit/math/Octree.java
- chunky/src/java/se/llbit/png/IEND.java
- chunky/src/java/se/llbit/png/IHDR.java
- chunky/src/java/se/llbit/png/ITXT.java
- chunky/src/java/se/llbit/png/PngFileWriter.java
- chunky/src/java/se/llbit/util/MCDownloader.java
- chunky/src/java/se/llbit/util/ZipExport.java
- launcher/src/se/llbit/chunky/launcher/ChunkyDeployer.java
- launcher/src/se/llbit/chunky/launcher/ChunkyLauncher.java
- launcher/src/se/llbit/chunky/launcher/UpdateChecker.java
- lib/src/se/llbit/chunky/JsonSettings.java
- lib/src/se/llbit/chunky/resources/MinecraftFinder.java
- releasetools/src/releasetools/ReleaseBuilder.java
...to ensure that input streams are always closed.
> Use try-with-resources everywhere

- chunky/src/java/se/llbit/chunky/main/Chunky.java
This fixes issues with plugins that register listeners to `chunky.getRenderController().getRenderer()` in `attach()` not working due to the renderController and the renderer being re-initialized in `doHeadlessRender()`.
If a plugin uses the renderController, it gets initialized at that point. If no plugin does, everything works as before. In non-headless mode, that was already the case (so the plugins worked fine there).
cc @stormboomer
> Don't overwrite the render controller after loading the plugins in headless mode.

- chunky/src/java/se/llbit/chunky/renderer/OutputMode.java
- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
- chunky/src/java/se/llbit/pfm/PfmFileWriter.java
Export to PFM directly from Chunky, without needing to complete a render with the Denoise plugin.
PfmFileWriter class code is modified from PFM saving code in @leMaik's Denoise Plugin.
> Added support for exporting PFM files.

- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
> Reset render when changing the ray depth

- chunky/src/java/se/llbit/chunky/world/Chunk.java
> Fix some 1.16 chunks being loaded incorrectly.

- chunky/src/java/se/llbit/chunky/block/Cauldron.java
- chunky/src/java/se/llbit/chunky/block/LavaCauldron.java
- chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
- chunky/src/java/se/llbit/chunky/block/PowderSnowCauldron.java
- chunky/src/java/se/llbit/chunky/model/CauldronModel.java
- chunky/src/java/se/llbit/chunky/resources/Texture.java
- chunky/src/java/se/llbit/chunky/resources/TexturePackLoader.java
> Add new blocks from 20w46a

- chunky/src/java/se/llbit/chunky/entity/Campfire.java
- chunky/src/java/se/llbit/chunky/world/ExtraMaterials.java
Campfire flame emittance was hard-coded until now.
> Add the campfire and soul campfire flame materials to the materials tab.

- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
Guess I also forgot to save the option preventNormalEmitterWithSampling in the scene, duh
> Save the option preventNormalEmitterWithSampling in the scene

- chunky/src/java/se/llbit/chunky/entity/Campfire.java
- chunky/src/java/se/llbit/chunky/entity/Entity.java
- chunky/src/java/se/llbit/chunky/entity/FlameParticles.java
- chunky/src/java/se/llbit/chunky/renderer/scene/PathTracer.java
- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
- chunky/src/java/se/llbit/math/Grid.java
Add emitter sampling support for entities. Particularly useful for small entities like candle's flames
Change the file format of the grid.
Also fix a bug with emitter sampling in general where emitter sampling wasn't working as expected in interior scene
> Entity emitter sampling

- chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
- chunky/src/java/se/llbit/chunky/block/PointedDripstone.java
- chunky/src/java/se/llbit/chunky/resources/Texture.java
- chunky/src/java/se/llbit/chunky/resources/TexturePackLoader.java
> Add dripstone block and pointed dripstone

- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
> Fix exception when trying to save a scene without any chunks.

- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
> Change order of parameter

- chunky/src/java/se/llbit/chunky/block/Dispenser.java
- chunky/src/java/se/llbit/chunky/block/Dropper.java
- chunky/src/java/se/llbit/chunky/block/Furnace.java
- chunky/src/java/se/llbit/chunky/block/OrientedTexturedBlock.java
- chunky/src/java/se/llbit/chunky/model/TexturedBlockModel.java
Checking another item from #518 (Wrong orientation in regular block textures)
> Fix texture rotation

- README.md
- chunky/build.gradle
- chunky/src/java/se/llbit/chunky/chunk/ChunkData.java
- chunky/src/java/se/llbit/chunky/chunk/EmptyChunkData.java
- chunky/src/java/se/llbit/chunky/chunk/GenericChunkData.java
- chunky/src/java/se/llbit/chunky/chunk/SimpleChunkData.java
- chunky/src/java/se/llbit/chunky/map/BiomeLayer.java
- chunky/src/java/se/llbit/chunky/map/SurfaceLayer.java
- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
- chunky/src/java/se/llbit/chunky/world/Chunk.java
- chunky/src/java/se/llbit/chunky/world/EmptyChunk.java
- chunky/src/java/se/llbit/chunky/world/EmptyRegionChunk.java
- licenses/fast-util.txt
Moved from https://github.com/leMaik/chunky/pull/22 as we discussed
Once I've looked into the options for `IntObjectMaps` I'll mark as ready for review
> Chunkdata rewrite master

- chunky/src/java/se/llbit/chunky/map/SurfaceLayer.java
- chunky/src/java/se/llbit/chunky/renderer/scene/AsynchronousSceneManager.java
- chunky/src/java/se/llbit/chunky/renderer/scene/SynchronousSceneManager.java
- chunky/src/java/se/llbit/chunky/world/Chunk.java
These are just random things I see and optimise as I go through my other PR
There will be a lot of commits as I'm splitting things up. Should probably all be squashed before merge
> fixes & optimisations

- .github/workflows/gradle.yml
See https://github.com/actions/setup-java/issues/18 and docs for setup-java.
> Fix for missing JFX with Actions

- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
> Fix yClipMin and yClipMax not being saved when saving a scene.

- chunky/src/java/se/llbit/chunky/chunk/SimpleChunkData.java
- chunky/src/java/se/llbit/chunky/renderer/scene/OctreeFinalizer.java
> Fix wrong isBlockOnEdge implementation in SimpleChunkData.

- chunky/src/java/se/llbit/chunky/chunk/BlockPalette.java
Defaults
Updated with metalness and roughness
> Update defaults for Iron-like blocks

- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
Plus a camera position fix.
Creating as a draft, will add the suggested camera controls when I wake up tomorrow
> Additional camera controls for use in very tall worlds

- chunky/src/java/se/llbit/chunky/model/SmallDripleafModel.java
- chunky/src/java/se/llbit/chunky/resources/Texture.java
- chunky/src/java/se/llbit/chunky/resources/TexturePackLoader.java
> Update the small dripleaf textures.

- chunky/src/java/se/llbit/chunky/renderer/scene/PreethamSky.java
- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
- chunky/src/java/se/llbit/chunky/renderer/scene/Sky.java
- chunky/src/java/se/llbit/chunky/renderer/scene/SkyCache.java
First I fixed the synchronization but then I just made it obsolete. Check it commit-by-commit to see the history.
@alexhliu Can't select you as a reviewer but your feedback is much appreciated :raised_hands: 
Fixes #825
> Fix skymap bugs due to synchronization issues

- chunky/src/java/se/llbit/chunky/ui/render/CameraTab.java
- chunky/src/res/se/llbit/chunky/ui/render/CameraTab.fxml
`Lense shift` has been corrected to `lens shift`.
Thanks for the help!
> Corrected spelling error: lense shift

- chunky/src/java/se/llbit/chunky/main/Chunky.java
- chunky/src/java/se/llbit/chunky/main/CommandLineOptions.java
> Return non-zero exit codes on errors

- chunky/src/java/se/llbit/chunky/main/SceneHelper.java
- chunky/src/java/se/llbit/chunky/ui/SceneChooserController.java
Regression from #848
cc @jackjt8
> Improve scene chooser for scenes with backup files

- chunky/src/java/se/llbit/chunky/renderer/scene/OctreeFinalizer.java
- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
> Fix water chunk border finalization

- chunky/src/java/se/llbit/chunky/renderer/renderdump/FloatingPointCompressor.java
- chunky/src/java/se/llbit/chunky/renderer/renderdump/RenderDump.java
- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
- chunky/src/java/se/llbit/chunky/resources/OctreeFileFormat.java
- chunky/src/java/se/llbit/chunky/world/ChunkDataSource.java
- chunky/src/java/se/llbit/math/Octree.java
> "just using java correctly" - @NotStirred 
My testing shows ~26x faster scene loading simply by using a buffered input stream (9k chunks in 3 seconds).
> Improve scene loading speed drastically.

- chunky/src/java/se/llbit/chunky/ui/render/SkyTab.java
`fogColor` already had a fix where the listener was removed before updating and re-added after updating. I applied this fix to the other sources of resets. This fixes #860.
> Fix render reset on opening Sky & Fog tab.

- chunky/src/java/se/llbit/pfm/PfmFileWriter.java
Skipped post processing for PFM exports - I didn't swap any loops since PFMs should be right side up in most programs.
Hope this works 👀
> Do not post process PFM exports

- chunky/src/java/se/llbit/chunky/chunk/ChunkData.java
- chunky/src/java/se/llbit/chunky/chunk/GenericChunkData.java
- chunky/src/java/se/llbit/chunky/chunk/SimpleChunkData.java
- chunky/src/java/se/llbit/chunky/map/SurfaceLayer.java
- chunky/src/java/se/llbit/chunky/world/Chunk.java
- chunky/src/java/se/llbit/chunky/world/EmptyChunk.java
- chunky/src/java/se/llbit/chunky/world/EmptyRegionChunk.java
- chunky/src/java/se/llbit/chunky/world/RegionParser.java
Some minor optimisations to the map view loading.
Also fixed not using `SimpleChunkData` when possible
Draft because I'm going to do some more profiling before pushing another change
> Minor optimisations 3

- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
- chunky/src/java/se/llbit/math/BVH.java
- chunky/src/java/se/llbit/util/PositionalInputStream.java
- chunky/src/java/se/llbit/util/TaskTracker.java
This does not seem to impact loading performance.
> ETA and progress bar for creating and loading Octrees and BVH.

- chunky/src/java/se/llbit/math/primitive/TexturedTriangle.java
Fixes a regression introduced in #870
> Fix textured triangle uv mapping.

- chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
> Add waxed oxidized copper and cut copper.

- chunky/src/java/se/llbit/chunky/entity/ArmorStand.java
> Fix loading chunks with armor stands from upgraded older minecraft versions

- chunky/src/java/se/llbit/chunky/block/Head.java
Not really a bug but a difference to Minecraft which seems to handle these textures well.
> Fix loading skull textures with wrong base64 padding.

- chunky/src/java/se/llbit/chunky/main/Chunky.java
- chunky/src/java/se/llbit/chunky/ui/ChunkyFx.java
- chunky/src/java/se/llbit/chunky/ui/ChunkyFxController.java
- chunky/src/java/se/llbit/chunky/ui/Credits.java
- chunky/src/java/se/llbit/chunky/ui/CreditsController.java
- chunky/src/res/se/llbit/chunky/ui/Chunky.fxml
- chunky/src/res/se/llbit/chunky/ui/Credits.fxml
- chunky/src/res/style.css
> Updated credits. Added copyright notice. PluginAPI to add plugin credits.

- chunky/src/java/se/llbit/chunky/block/Fire.java
- chunky/src/java/se/llbit/chunky/block/SoulFire.java
- chunky/src/java/se/llbit/chunky/model/FireModel.java
- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
- chunky/src/java/se/llbit/chunky/resources/AnimatedTexture.java
- chunky/src/java/se/llbit/chunky/ui/render/AdvancedTab.java
- chunky/src/res/se/llbit/chunky/ui/render/AdvancedTab.fxml
Added a time slider which increments the animated texture. Animated textures are now based on block position.
Closes #137, related to #889
> Animated textures.

- chunky/src/java/se/llbit/chunky/chunk/SimpleChunkData.java
- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
> correct isBlockOnEdge checks

- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
- chunky/src/java/se/llbit/math/PackedOctree.java
Should fix every bug listed in #923 
Should also fix #908 
Some detail about the reason the bugs were occurring and their fixes are in each commit message
> Various octree bugfixes

- chunky/src/java/se/llbit/chunky/renderer/scene/Camera.java
- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
Add a tooltip displaying the current camera facing direction.
> Facing tooltip.

- chunky/src/java/se/llbit/math/Octree.java
Explanation is in the comment :D
> Fix the freeze when looking down and  in parallel projection

- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
> Fix clipping when using parallel projection

- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
Add a json field in the scene that can be used by plugin to store data that relates to a scene
> Add a way for plugin to save data in a scene

- chunky/src/java/se/llbit/chunky/entity/PlayerEntity.java
- chunky/src/java/se/llbit/chunky/world/World.java
- chunky/src/java/se/llbit/chunky/world/WorldTexture.java
- chunky/src/java/se/llbit/chunky/world/model/JsonModel.java
- launcher/src/se/llbit/chunky/launcher/Logger.java
I've been stashing this for a week now, so here is a PR. I ran IntelliJ inspection and it showed a lot of warnings, this fixes some of them.
> Small cleanup, fix warnings

- chunky/src/java/se/llbit/chunky/ui/ChunkyErrorDialog.java
- chunky/src/res/se/llbit/chunky/ui/ErrorDialog.fxml
- chunky/src/res/se/llbit/chunky/ui/WarningDialog.fxml
Adds a "Dismiss All" button to the warning and error dialogs.
> Add "Dismiss All" to warnings dialog

- chunky/src/java/se/llbit/chunky/entity/PaintingEntity.java
> Fix skeleton painting texture for 1.13 or older resourcepacks

- chunky/src/java/se/llbit/chunky/block/Lava.java
- chunky/src/java/se/llbit/chunky/block/Water.java
> Add a bottom face for lava

- chunky/src/java/se/llbit/chunky/model/VineModel.java
Somehow hard-coded in Minecraft, this logic isn't present in the block model.
Fixes #928
> Fix vine top part orientation

- chunky/src/java/se/llbit/chunky/block/CakeWithCandle.java
- chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
- chunky/src/java/se/llbit/chunky/model/CakeWithCandleModel.java
- chunky/src/java/se/llbit/chunky/resources/Texture.java
- chunky/src/java/se/llbit/chunky/resources/TexturePackLoader.java
> Update blocks for Minecraft 1.17-rc1

- chunky/src/java/se/llbit/chunky/renderer/postprocessing/SimplePixelPostProcessingFilter.java
- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
> Fix additional data and post processing progress.

- chunky/src/java/se/llbit/chunky/ui/CreditsController.java
- chunky/src/java/se/llbit/chunky/ui/render/AdvancedTab.java
- chunky/src/java/se/llbit/chunky/ui/render/PostprocessingTab.java
- chunky/src/java/se/llbit/chunky/ui/render/SkyTab.java
- chunky/src/res/se/llbit/chunky/ui/Chunky.fxml
- chunky/src/res/se/llbit/chunky/ui/Credits.fxml
- chunky/src/res/se/llbit/chunky/ui/render/GeneralTab.fxml
* This is on top of #1020.
* Fix progress bar being pushed offscreen
* Fix scroll from expanding scene tab, now it shows everything
* Update contributors list (This should be updated again before 2.4.0 is released)
* Update licenses format and add JavaFX
> Various UI fixes for 2.4.0

- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
Only comments changed. Should be trivial.
> PFM should be listed as an output file type in JavaDoc in Scene.java

- chunky/src/java/se/llbit/chunky/ui/RenderCanvasFx.java
> Show a hint in the render tab if no chunks are loaded.

- chunky/src/java/se/llbit/chunky/ui/CreditsController.java
- chunky/src/res/se/llbit/chunky/ui/Credits.fxml
* Add plugin page link.
* Update contributors.
* Add Java to licenses.
**Link is currently dead. https://github.com/chunky-dev/docs/pull/1 must be merged first.**
> Add plugin page link.

- chunky/src/java/se/llbit/chunky/map/MapBuffer.java
- chunky/src/java/se/llbit/chunky/renderer/export/PfmExportFormat.java
- chunky/src/java/se/llbit/chunky/renderer/export/PngExportFormat.java
- chunky/src/java/se/llbit/chunky/renderer/export/Tiff32ExportFormat.java
- chunky/src/java/se/llbit/imageformats/pfm/PfmFileWriter.java
- chunky/src/java/se/llbit/imageformats/png/CrcOutputStream.java
- chunky/src/java/se/llbit/imageformats/png/IDAT.java
- chunky/src/java/se/llbit/imageformats/png/IEND.java
- chunky/src/java/se/llbit/imageformats/png/IHDR.java
- chunky/src/java/se/llbit/imageformats/png/ITXT.java
- chunky/src/java/se/llbit/imageformats/png/PngChunk.java
- chunky/src/java/se/llbit/imageformats/png/PngFileWriter.java
- chunky/src/java/se/llbit/imageformats/tiff/TiffFileWriter.java
... to declutter the se.llbit.* package.
> Collect different image file writers into own package

- chunky/src/java/se/llbit/chunky/renderer/projection/ParallelProjector.java
- chunky/src/java/se/llbit/chunky/renderer/scene/Camera.java
- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
> Fix parallel projection autofocus

- lib/src/se/llbit/chunky/ui/SliderAdjuster.java
Closes #1050
Slider was broken in 2.4:
Now:
> Fix Target SPP slider.

- chunky/src/java/se/llbit/chunky/main/CommandLineOptions.java
Closes #828.
Now when run with `-help`:
```
> Task :chunky:Chunky.main()
Settings loaded from [...]
Chunky 2.4.0, Copyright (c) 2010-2021 Jesper Oqvist and Chunky Contributors
Chunky comes with ABSOLUTELY NO WARRANTY. This is free software, 
and you are welcome to redistribute it under certain conditions.
See the GNU General Public License v3 for more details.
Usage: mapLoader [OPTIONS] [WORLD DIRECTORY]
...
```
> Terminal interaction copyright notice.

- chunky/src/res/se/llbit/chunky/ui/render/PostprocessingTab.fxml
Old hint mentioned "preview window". Updated it for one window UI.
> Update hint in postprocessing tab

- README.md
- chunky/src/java/se/llbit/chunky/block/Cauldron.java
- chunky/src/java/se/llbit/chunky/model/CauldronModel.java
- chunky/src/java/se/llbit/chunky/renderer/scene/LegacyWaterShader.java
- chunky/src/java/se/llbit/chunky/renderer/scene/PathTracer.java
- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
- chunky/src/java/se/llbit/chunky/renderer/scene/SimplexWaterShader.java
- chunky/src/java/se/llbit/chunky/renderer/scene/WaterShader.java
- chunky/src/java/se/llbit/chunky/renderer/scene/WaterShading.java
- chunky/src/java/se/llbit/chunky/ui/CreditsController.java
- chunky/src/java/se/llbit/chunky/ui/render/WaterTab.java
- chunky/src/java/se/llbit/math/SimplexNoise.java
- chunky/src/res/se/llbit/chunky/ui/Credits.fxml
- chunky/src/res/se/llbit/chunky/ui/render/WaterTab.fxml
Closes #880, probably closes #628 as well?
This PR adds a new option to use procedural water shading and a few parameters to control it. The new procedural water is a simple fractal noise based on simplex noise. I tried to do something more fancy but in the end it just looked bad so I decided to stick with the simplicity.
Example:
> Implement water shading using noise

- chunky/src/java/se/llbit/chunky/ui/render/GeneralTab.java
I have no idea why this fixes it.
> Fix scene tab scroll

- chunky/src/java/se/llbit/chunky/main/Chunky.java
- chunky/src/java/se/llbit/chunky/main/ChunkyOptions.java
- chunky/src/java/se/llbit/chunky/main/CommandLineOptions.java
Haven't found a method to load changes mades on my world.
> Add -reload-chunks option to headless mode

- chunky/src/java/se/llbit/chunky/renderer/scene/SynchronousSceneManager.java
Fixes #1093 (a regression introduced by #1075)
> Fix scene renaming not switching the directory.

- chunky/src/java/se/llbit/chunky/block/Button.java
> Make buttons not solid.

- chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
This will be backported to 2.4.x as part of #1120
> Fix ice block not being translucent.

- chunky/src/java/se/llbit/chunky/block/Button.java
- chunky/src/java/se/llbit/chunky/block/FrostedIce.java
- chunky/src/java/se/llbit/chunky/block/Glass.java
- chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
- chunky/src/java/se/llbit/chunky/block/MinecraftBlockTranslucent.java
- chunky/src/java/se/llbit/chunky/block/ShulkerBox.java
- chunky/src/java/se/llbit/chunky/block/Slab.java
- chunky/src/java/se/llbit/chunky/block/Slime.java
- chunky/src/java/se/llbit/chunky/block/TintedGlass.java
Follow-up for #1116 (e.g. lever was still solid)
> Make translucent blocks non-solid by default.

- chunky/src/java/se/llbit/chunky/block/AbstractModelBlock.java
- chunky/src/java/se/llbit/chunky/block/Button.java
- chunky/src/java/se/llbit/chunky/block/ChainCommandBlock.java
- chunky/src/java/se/llbit/chunky/block/CommandBlock.java
- chunky/src/java/se/llbit/chunky/block/Dispenser.java
- chunky/src/java/se/llbit/chunky/block/FrostedIce.java
- chunky/src/java/se/llbit/chunky/block/Glass.java
- chunky/src/java/se/llbit/chunky/block/GrassBlock.java
- chunky/src/java/se/llbit/chunky/block/Log.java
- chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
- chunky/src/java/se/llbit/chunky/block/MinecraftBlockTranslucent.java
- chunky/src/java/se/llbit/chunky/block/RepeatingCommandBlock.java
- chunky/src/java/se/llbit/chunky/block/Slab.java
- chunky/src/java/se/llbit/chunky/block/Slime.java
- chunky/src/java/se/llbit/chunky/block/TexturedBlock.java
- chunky/src/java/se/llbit/chunky/block/TintedGlass.java
- chunky/src/java/se/llbit/chunky/block/TopBottomOrientedTexturedBlock.java
Follow-up for #1116, e.g. levers were also solid.
> Fix solid blocks

- launcher/src/se/llbit/chunky/launcher/ChunkyDeployer.java
- launcher/src/se/llbit/chunky/launcher/ChunkyLauncher.java
- launcher/src/se/llbit/chunky/launcher/JreUtil.java
- launcher/src/se/llbit/chunky/launcher/ui/ChunkyLauncherController.java
- lib/src/se/llbit/chunky/launcher/LauncherSettings.java
> Show a warning in the launcher when not using a 64-bit JVM

- chunky/src/java/se/llbit/chunky/resources/Texture.java
- chunky/src/java/se/llbit/chunky/resources/TexturePackLoader.java
> Fix sign texture with pre-1.14 resourcepacks.

- chunky/src/java/se/llbit/chunky/block/BlockSpec.java
- chunky/src/java/se/llbit/chunky/chunk/ChunkData.java
- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
- chunky/src/java/se/llbit/chunky/renderer/scene/Sky.java
- chunky/src/java/se/llbit/chunky/resources/Texture.java
- chunky/src/java/se/llbit/chunky/resources/TexturePackLoader.java
- chunky/src/java/se/llbit/chunky/world/Chunk.java
- chunky/src/java/se/llbit/chunky/world/biome/ArrayBiomePalette.java
- chunky/src/java/se/llbit/chunky/world/biome/MapBiomePalette.java
- chunky/src/java/se/llbit/util/NbtUtil.java
- chunky/src/java/se/llbit/util/NotNull.java
- chunky/src/java/se/llbit/util/annotation/NotNull.java
- chunky/src/java/se/llbit/util/annotation/Nullable.java
also moved `NotNull` into new `annotation` package
> Add Nullable Annotation

- chunky/src/java/se/llbit/chunky/block/GrassBlock.java
Fixes #1129, regression from #1118
> Fix grass block being non-solid.

- chunky/src/java/se/llbit/chunky/world/biome/Biomes.java
> Fix badlands and roofed forest biome colors

- chunky/src/java/se/llbit/chunky/model/Tint.java
Master branch:
With gamma corrected tints:
> Gamma correct tint colors.

- chunky/src/java/se/llbit/chunky/renderer/scene/SimplexWaterShader.java
> Fix NaN in procedural water.

- chunky/src/java/se/llbit/chunky/ui/SceneChooserController.java
- chunky/src/java/se/llbit/chunky/ui/TableSortConfigSerializer.java
- chunky/src/java/se/llbit/chunky/ui/WorldChooserController.java
- chunky/src/java/se/llbit/chunky/world/World.java
- chunky/src/res/se/llbit/chunky/ui/WorldChooser.fxml
- lib/src/se/llbit/chunky/PersistentSettings.java
> Sort worlds by last modified time.

- chunky/src/java/se/llbit/chunky/ui/RenderControlsFxController.java
> Fix not updating gui tabs on chunk load/reload

- build.gradle
- chunky/src/java/se/llbit/chunky/model/AnimatedQuadModel.java
- chunky/src/java/se/llbit/imageformats/png/CrcOutputStream.java
* Set Java build release version to Java 8
* Replace `Math.floorMod` with simple cast to `int`
* Fix potential Java 8 compatibility issue in `CrcOutputStream`
This closes #1187
> Fix `NoSuchMethodError` in `AnimatedQuadModel`

- chunky/src/java/se/llbit/chunky/ui/elements/SizeInput.java
> Fix chain icon applying to all CheckBoxes

- chunky/src/java/se/llbit/chunky/ui/render/tabs/GeneralTab.java
> Fix initial canvas size control value.

- chunky/src/java/se/llbit/chunky/entity/PlayerEntity.java
> Fix player height to be 1.875m instead of 2m.

- .editorconfig
- chunky/src/java/se/llbit/chunky/world/biome/Biome.java
- chunky/src/java/se/llbit/chunky/world/biome/BiomeBuilder.java
- chunky/src/java/se/llbit/chunky/world/biome/Biomes.java
Refactors biomes to prepare for custom biomes (#1217) and adds deep dark and mangrove swamp biomes (#1218).
> Add biomes builder and new 1.19 biomes

- chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
- chunky/src/java/se/llbit/chunky/resources/Texture.java
- chunky/src/java/se/llbit/chunky/resources/TexturePackLoader.java
Some blocks for #1219 and #1221
> Add mud blocks and reinforced deepslate.

- chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
- chunky/src/java/se/llbit/chunky/block/SculkCatalyst.java
- chunky/src/java/se/llbit/chunky/block/SculkShrieker.java
- chunky/src/java/se/llbit/chunky/block/SculkVein.java
- chunky/src/java/se/llbit/chunky/chunk/BlockPalette.java
- chunky/src/java/se/llbit/chunky/model/FlowerPotModel.java
- chunky/src/java/se/llbit/chunky/model/SculkShriekerModel.java
- chunky/src/java/se/llbit/chunky/model/SculkVeinModel.java
- chunky/src/java/se/llbit/chunky/resources/Texture.java
Closes #1218, closes #1221, closes #1223
> Add sculk catalyst, sculk shrieker and sculk veins.

- chunky/src/res/se/llbit/chunky/ui/Chunky.fxml
Update the copyright shown in the About tab.
> Update Chunky copyright

- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
> Fix scene reset from opening `Advanced Tab`

- chunky/src/java/se/llbit/chunky/ui/controller/ChunkyFxController.java
> Fix wrong scene path after saving it.

- chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
- chunky/src/java/se/llbit/chunky/block/RedstoneTorch.java
- chunky/src/java/se/llbit/chunky/block/RedstoneWallTorch.java
- chunky/src/java/se/llbit/chunky/block/WallTorch.java
- chunky/src/java/se/llbit/chunky/chunk/BlockPalette.java
Resolves #1033 
Water specular now 0.255 from 0.12;
Torch and wall torch emittance now 5.0 from 50.0;
Soul torch and Soul wall torch emittance now 3.5 from 35.0;
Added Redstone wall torch emittance of 1.0;
Added Enchanting table emittance of 0.6;
> Update material defaults

- chunky/src/java/se/llbit/chunky/ui/controller/ChunkyFxController.java
- chunky/src/java/se/llbit/chunky/ui/controller/SceneChooserController.java
- chunky/src/res/se/llbit/chunky/ui/Chunky.fxml
- chunky/src/res/se/llbit/chunky/ui/dialogs/SceneChooser.fxml
As [promised](https://github.com/chunky-dev/chunky/pull/1253#issuecomment-1120205530)... This will help removing the options panel.
> Move the scenes directory buttons to the scene chooser dialog.

- chunky/src/java/se/llbit/chunky/renderer/scene/SynchronousSceneManager.java
> Fix scene directory after launch or after creating a new scene.

- chunky/src/java/se/llbit/chunky/renderer/RenderContext.java
- chunky/src/java/se/llbit/chunky/renderer/SceneIOProvider.java
- chunky/src/java/se/llbit/chunky/renderer/scene/AsynchronousSceneManager.java
- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
- chunky/src/java/se/llbit/chunky/renderer/scene/SynchronousSceneManager.java
- chunky/src/java/se/llbit/chunky/ui/ChunkMap.java
- chunky/src/java/se/llbit/chunky/ui/ChunkyFx.java
- chunky/src/java/se/llbit/chunky/ui/HyperlinkMenuItem.java
- chunky/src/java/se/llbit/chunky/ui/RenderCanvasFx.java
- chunky/src/java/se/llbit/chunky/ui/controller/ChunkyFxController.java
- chunky/src/java/se/llbit/chunky/ui/controller/CreditsController.java
- chunky/src/java/se/llbit/chunky/ui/controller/RenderControlsFxController.java
- chunky/src/java/se/llbit/chunky/ui/dialogs/Credits.java
- chunky/src/java/se/llbit/chunky/ui/dialogs/ValidatingTextInputDialog.java
- chunky/src/java/se/llbit/chunky/ui/render/tabs/AdvancedTab.java
- chunky/src/java/se/llbit/chunky/ui/render/tabs/GeneralTab.java
- chunky/src/java/se/llbit/chunky/ui/render/tabs/TexturesTab.java
- chunky/src/res/se/llbit/chunky/ui/Chunky.fxml
- chunky/src/res/se/llbit/chunky/ui/dialogs/Credits.fxml
- chunky/src/res/se/llbit/chunky/ui/render/tabs/AdvancedTab.fxml
- chunky/src/res/se/llbit/chunky/ui/render/tabs/TexturesTab.fxml
Related to #1046 
Closes #1173 
Only the _Map View_ and _Options_ tabs are remaining.
> Improve UI

- chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
- chunky/src/java/se/llbit/chunky/world/region/RegionParser.java
> Backport - Fix palette error due to expecting block name to contian "minecraft:" #1265 

- chunky/src/java/se/llbit/chunky/ui/elements/AngleAdjuster.java
- chunky/src/java/se/llbit/chunky/ui/render/tabs/AdvancedTab.java
- chunky/src/java/se/llbit/chunky/ui/render/tabs/LightingTab.java
- lib/src/se/llbit/chunky/ui/Adjuster.java
- lib/src/se/llbit/chunky/ui/SliderAdjuster.java
> Improve chunk reload prompts after changing the emitter grid.

- .github/workflows/gradle.yml
- launcher/src/se/llbit/chunky/launcher/ChunkyLauncher.java
- launcher/src/se/llbit/chunky/launcher/UpdateChecker.java
Allowing redirects for downloads makes dynamic update sites possible, eg. I'm currently working on an update site that can serve any PR build. That's also why we need chunky-core as an artifact.
> Make the launcher follow redirects and add a chunky core artifact

- chunky/src/java/se/llbit/chunky/block/Fern.java
- chunky/src/java/se/llbit/chunky/block/Grass.java
- chunky/src/java/se/llbit/chunky/block/LargeFern.java
- chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
- chunky/src/java/se/llbit/chunky/block/SugarCane.java
- chunky/src/java/se/llbit/chunky/block/TallGrass.java
- chunky/src/java/se/llbit/chunky/model/GrassTintedSpriteModel.java
> Tint sugar cane with the grass color.

- chunky/src/java/se/llbit/chunky/world/Chunk.java
Currently we have artefacts in the map view where the surface is one thick, and we skip through it
> Fix off by one error in heightmap updating, and minimum bounds on iteration

- chunky/src/java/se/llbit/chunky/ui/controller/ChunkyFxController.java
- chunky/src/java/se/llbit/chunky/ui/render/tabs/CameraTab.java
- chunky/src/java/se/llbit/chunky/ui/render/tabs/GeneralTab.java
- chunky/src/java/se/llbit/chunky/ui/render/tabs/LightingTab.java
- chunky/src/java/se/llbit/chunky/ui/render/tabs/MaterialsTab.java
- chunky/src/java/se/llbit/chunky/ui/render/tabs/PostprocessingTab.java
- chunky/src/java/se/llbit/chunky/ui/render/tabs/SkyTab.java
- chunky/src/java/se/llbit/chunky/ui/render/tabs/TexturesTab.java
- chunky/src/java/se/llbit/chunky/ui/render/tabs/WaterTab.java
- chunky/src/res/se/llbit/chunky/ui/render/tabs/HelpTab.fxml
Fixes #1303 
Improved some existing tooltips and added new tooltips to the controls.
> Update control tooltips

- chunky/src/java/se/llbit/chunky/renderer/scene/biome/BiomeStructure.java
- chunky/src/java/se/llbit/chunky/renderer/scene/biome/Trivial2dBiomeStructure.java
- chunky/src/java/se/llbit/chunky/renderer/scene/biome/Trivial3dBiomeStructure.java
- chunky/src/java/se/llbit/chunky/renderer/scene/biome/WorldTexture2dBiomeStructure.java
- chunky/src/java/se/llbit/chunky/ui/render/tabs/AdvancedTab.java
> Use the compacted WorldTexture for 2d biomes by default again

- chunky/src/java/se/llbit/util/mojangapi/MinecraftSkin.java
> Fix crash if a profile has no skins.

- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
- lib/src/se/llbit/chunky/PersistentSettings.java
Follow-up for #1329 that actually changes the default implementation.
> Change default biome structure implementation to world texture 2d.

- chunky/src/java/se/llbit/chunky/entity/PlayerEntity.java
- chunky/src/test/se/llbit/chunky/block/SkullTextureTest.java
Somehow we didn't have this yet :man_shrugging:
> Download skins of heads that only have a skull owner but no embedded skin

- chunky/src/java/se/llbit/chunky/world/WorldTexture.java
> Do not insert new empty chunk textures when getting a color.

- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
- chunky/src/java/se/llbit/chunky/world/Chunk.java
- chunky/src/java/se/llbit/chunky/world/ChunkVersion.java
- chunky/src/java/se/llbit/chunky/world/ImposterCubicChunk.java
> Make chunk version an enum and give it a default value.

- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
- chunky/src/java/se/llbit/chunky/world/WorldTexture.java
Fixes #1299 
Fixes #1281 
#1354 is still fixed
> Fix two bugs related to world textures and water.

- chunky/src/java/se/llbit/chunky/ui/RenderCanvasFx.java
> Fix camera rotation issues when using precise movement (holding shift)

- chunky/src/java/se/llbit/chunky/ui/render/tabs/MaterialsTab.java
> Sort materials list

- chunky/src/java/se/llbit/chunky/world/ChunkSelectionTracker.java
> Properly notify the map view of the cleared selection

- lib/src/se/llbit/chunky/PersistentSettings.java
fixes #1366
also fixes missing path separator in deprecated method
> Fix saving of resource pack configuration

- chunky/build.gradle
> Fix missing dependencies in chunky-core pom file.

- chunky/src/java/se/llbit/chunky/ui/controller/ChunkyFxController.java
Closes #1359 and proper fix for #1345
> Only update the map selection if the user loads the world associated with a scene

- chunky/src/java/se/llbit/chunky/entity/HeadEntity.java
> Fix head entity x/z position.

- chunky/src/java/se/llbit/chunky/ui/controller/SceneChooserController.java
> Fix error if the scene directory chooser dialog is closed.

- chunky/src/java/se/llbit/chunky/ui/render/tabs/SkyTab.java
- lib/src/se/llbit/chunky/ui/Adjuster.java
- lib/src/se/llbit/chunky/ui/ValidatingNumberStringConverter.java
> Allow for input fields to have their own precision & set fog precision to 6 decimal places

- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
- chunky/src/java/se/llbit/util/ZipExport.java
> Fix scene zip export.

- chunky/src/java/se/llbit/chunky/ui/ChunkMap.java
- chunky/src/java/se/llbit/chunky/ui/controller/ChunkyFxController.java
- chunky/src/res/se/llbit/chunky/ui/Chunky.fxml
> Add a "Show Players" checkbox to the map settings

- chunky/src/java/se/llbit/chunky/renderer/scene/Sky.java
> Fix horizon offset being dropped when render starts.

- chunky/src/java/se/llbit/chunky/model/BedModel.java
> Flip bed top texture.

- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
- chunky/src/java/se/llbit/chunky/world/Chunk.java
Fixes #1345 in Chunky 2.4, see https://github.com/chunky-dev/chunky/issues/1359#issuecomment-1229555439 for why we do need this fix (TL;DR ChunkyMap and anyone else loading empty chunks programmatically).
> Fix loading empty chunks.

- chunky/src/java/se/llbit/math/NodeBasedOctree.java
> Fix NPE when loading a world without water with NODE octree.

- chunky/src/java/se/llbit/chunky/ui/dialogs/SettingsExport.java
- chunky/src/java/se/llbit/fxutil/ColumnsBoxBuilder.java
Closes #1439 . New settings export box:
> Resize `Settings Export` Box. Add `Select All` button.

- chunky/src/java/se/llbit/chunky/renderer/projection/ApertureProjector.java
- chunky/src/java/se/llbit/chunky/renderer/scene/AsynchronousSceneManager.java
- chunky/src/java/se/llbit/chunky/renderer/scene/Sky.java
- chunky/src/java/se/llbit/chunky/resources/HDRTexture.java
- chunky/src/java/se/llbit/chunky/resources/PFMTexture.java
* Add special error message for when loading a skymap with too many pixels
* Improve error logging for failing to load skymap
* Improve some other error logging
Closes #1467
> Improve skymap and other error logging.

- chunky/src/java/se/llbit/chunky/renderer/scene/Sky.java
- chunky/src/java/se/llbit/chunky/ui/render/settings/SkyboxSettings.java
- chunky/src/java/se/llbit/chunky/ui/render/settings/SkymapSettings.java
- chunky/src/java/se/llbit/math/Matrix3.java
- chunky/src/res/se/llbit/chunky/ui/render/settings/SkyboxSettings.fxml
- chunky/src/res/se/llbit/chunky/ui/render/settings/SkymapSettings.fxml
> Add pitch and roll rotation for skymap and skyboxes.

- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
> Fix ESS when yMin is negative.

- chunky/src/java/se/llbit/chunky/map/MapView.java
- chunky/src/java/se/llbit/chunky/ui/controller/ChunkyFxController.java
- chunky/src/java/se/llbit/chunky/ui/controller/RenderControlsFxController.java
- chunky/src/java/se/llbit/chunky/ui/render/tabs/GeneralTab.java
- chunky/src/res/se/llbit/chunky/ui/Chunky.fxml
- chunky/src/res/se/llbit/chunky/ui/render/tabs/GeneralTab.fxml
- chunky/src/res/style.css
- lib/src/se/llbit/chunky/ui/Adjuster.java
Fixes #1444, which imho is mostly a GUI bug.
> Add validation for y clipping ranges

- chunky/src/java/se/llbit/chunky/renderer/scene/SceneManager.java
- chunky/src/java/se/llbit/chunky/renderer/scene/SynchronousSceneManager.java
> De-duplicate scene saving code to ensure onSceneSaved is always called.

- chunky/src/java/se/llbit/chunky/ui/render/tabs/AdvancedTab.java
- chunky/src/res/se/llbit/chunky/ui/render/tabs/AdvancedTab.fxml
Would appreciate if someone else could test this also :works_on_my_machine:
> Allow multiple dumps to be merged at once by switching to a multi-file dialog.

- launcher/src/se/llbit/chunky/launcher/ui/ChunkyLauncherController.java
> Fix issue where the auto-update popup appears over first time setup.

- chunky/src/java/se/llbit/chunky/world/ChunkDataSource.java
- chunky/src/java/se/llbit/chunky/world/region/ChunkReadException.java
- chunky/src/java/se/llbit/chunky/world/region/MCRegion.java
- chunky/src/java/se/llbit/chunky/world/region/Region.java
- rewrite error handling of chunk loading
- add some more documentation
> More details in error messages in MCA chunk loading

- chunky/src/java/se/llbit/chunky/renderer/scene/Sun.java
- chunky/src/java/se/llbit/chunky/ui/render/tabs/LightingTab.java
- chunky/src/java/se/llbit/chunky/ui/render/tabs/WaterTab.java
> Do not limit water plane y-values and change `Sun Radius` to degrees.

- chunky/src/java/se/llbit/chunky/model/AABBModel.java
- chunky/src/java/se/llbit/chunky/model/Tint.java
> Fix light block (and build) in 2.4.x.

- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
- chunky/src/java/se/llbit/chunky/world/Chunk.java
- chunky/src/java/se/llbit/chunky/world/region/MCRegion.java
Backport/feature/entity_regions #1522
> Backport entity regions support

- chunky/src/java/se/llbit/chunky/renderer/scene/Fog.java
- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
- chunky/src/java/se/llbit/chunky/ui/render/settings/UniformFogSettings.java
- chunky/src/java/se/llbit/chunky/ui/render/tabs/SkyTab.java
- chunky/src/res/se/llbit/chunky/ui/render/settings/UniformFogSettings.fxml
- chunky/src/res/se/llbit/chunky/ui/render/tabs/SkyTab.fxml
This does not implement a GUI for layered fog. It only adds a simpler way to enable and disable fog.
**New:**
> Add a choice box for fog type

- chunky/src/java/se/llbit/chunky/main/Chunky.java
- chunky/src/java/se/llbit/chunky/ui/ChunkMap.java
- chunky/src/java/se/llbit/chunky/ui/RenderCanvasFx.java
This sets the user data of the context menu to the `Vector2` representing the coordinate.
> Add an API to get the canvas / map coordinate in the context menu callback.

- chunky/src/java/se/llbit/chunky/model/AABBModel.java
AABB UV mappings were not applied properly (all faces were using the mapping for the top face).
> Fix AABB UV mapping.

- chunky/src/java/se/llbit/chunky/ui/render/tabs/CameraTab.java
> Fix camera renaming cloning the camera

- chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
- chunky/src/java/se/llbit/chunky/resources/Texture.java
- chunky/src/java/se/llbit/chunky/resources/TexturePackLoader.java
> Fix jukebox side texture.

- chunky/src/java/se/llbit/chunky/ui/render/settings/SkyboxSettings.java
- chunky/src/java/se/llbit/chunky/ui/render/settings/SkymapSettings.java
> Display JPEG files in image file browsers

- chunky/src/java/se/llbit/chunky/block/DecoratedPot.java
- chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
- chunky/src/java/se/llbit/chunky/block/PinkPetals.java
- chunky/src/java/se/llbit/chunky/block/SnifferEgg.java
- chunky/src/java/se/llbit/chunky/block/TorchflowerCrop.java
- chunky/src/java/se/llbit/chunky/model/DecoratedPotModel.java
- chunky/src/java/se/llbit/chunky/model/Flowerbed.java
- chunky/src/java/se/llbit/chunky/model/SnifferEggModel.java
- chunky/src/java/se/llbit/chunky/resources/Texture.java
- chunky/src/java/se/llbit/chunky/world/biome/Biomes.java
> Add new blocks and update blocks from 23w12a, 23w13a and 23w16a

- chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
- chunky/src/java/se/llbit/chunky/block/PitcherPlant.java
- chunky/src/java/se/llbit/chunky/block/SculkSensor.java
- chunky/src/java/se/llbit/chunky/block/SnifferEgg.java
- chunky/src/java/se/llbit/chunky/model/PitcherPlantBottomModel.java
- chunky/src/java/se/llbit/chunky/model/PitcherPlantTopModel.java
- chunky/src/java/se/llbit/chunky/resources/Texture.java
Related to #1563, #1575 and #1582.
> Add more block updates from 1.20

- chunky/src/java/se/llbit/chunky/entity/SignEntity.java
- chunky/src/java/se/llbit/chunky/entity/WallSignEntity.java
- chunky/src/java/se/llbit/chunky/resources/SignTexture.java
- chunky/src/java/se/llbit/chunky/resources/texturepack/JsonFontTextureLoader.java
> Add support for font file references to support 1.20 fonts and back-side sign texts.

- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
- chunky/src/java/se/llbit/chunky/renderer/scene/SceneEntities.java
Another PR in the quest for a cleaner Scene class :)
> Move entity related stuff into separate class

- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
- chunky/src/java/se/llbit/chunky/ui/render/tabs/GeneralTab.java
- chunky/src/res/se/llbit/chunky/ui/render/tabs/GeneralTab.fxml
- lib/src/se/llbit/chunky/PersistentSettings.java
Very simple pr.
The only thing of note is that I'm removing some fields and persistent settings methods. I don't expect any plugin is using them though.
Closes #1588
> Remove persistent settings entries for y-clip

- README.md
- chunky/src/java/se/llbit/chunky/ui/controller/SceneChooserController.java
- chunky/src/res/se/llbit/chunky/ui/dialogs/Credits.fxml
> Reload scenes after switching the scenes directory.

- chunky/src/java/se/llbit/chunky/block/CalibratedSculkSensor.java
- chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
- chunky/src/java/se/llbit/chunky/block/PitcherCrop.java
- chunky/src/java/se/llbit/chunky/block/SculkSensor.java
- chunky/src/java/se/llbit/chunky/chunk/BlockPalette.java
- chunky/src/java/se/llbit/chunky/entity/CalibratedSculkSensorAmethyst.java
- chunky/src/java/se/llbit/chunky/entity/Entity.java
- chunky/src/java/se/llbit/chunky/model/CalibratedSculkSensorModel.java
- chunky/src/java/se/llbit/chunky/model/PitcherCropBottomModel.java
- chunky/src/java/se/llbit/chunky/model/PitcherCropTopModel.java
- chunky/src/java/se/llbit/chunky/resources/Texture.java
- chunky/src/java/se/llbit/chunky/world/ExtraMaterials.java
> Add the pitcher crop and calibrated sculk sensor.

- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
- chunky/src/java/se/llbit/chunky/renderer/scene/Sky.java
- chunky/src/java/se/llbit/chunky/ui/render/settings/SkyboxSettings.java
- chunky/src/java/se/llbit/chunky/ui/render/settings/SkymapSettings.java
> Add support for relative skymap paths in scene description files.

- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
- chunky/src/java/se/llbit/chunky/resources/OctreeFileFormat.java
- chunky/src/java/se/llbit/util/TaskTracker.java
* Log completed steps and elapsed time when a task is closed
* Add more detailed step information in scene loading
> Small tasktracker improvments.

- chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
- chunky/src/java/se/llbit/chunky/block/minecraft/Head.java
- chunky/src/java/se/llbit/chunky/block/minecraft/WallHead.java
- chunky/src/java/se/llbit/chunky/entity/PlayerEntity.java
- chunky/src/java/se/llbit/chunky/entity/SkullEntity.java
- chunky/src/java/se/llbit/chunky/entity/UVMapHelper.java
- chunky/src/java/se/llbit/chunky/resources/Texture.java
Adds piglin heads and a utility class that will make adding entity models simpler in the future.
Closes #1550
> Add piglin heads.

- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
- chunky/src/java/se/llbit/chunky/ui/render/tabs/EntitiesTab.java
- chunky/src/res/se/llbit/chunky/ui/render/tabs/EntitiesTab.fxml
> Add a dropdown field to select the entity type that is being added.

- chunky/src/java/se/llbit/chunky/renderer/scene/Camera.java
- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
> Prevent locking camera from resetting render

- chunky/src/java/se/llbit/chunky/renderer/export/Tiff32ExportFormat.java
- chunky/src/java/se/llbit/chunky/renderer/renderdump/ClassicDumpFormat.java
- chunky/src/java/se/llbit/chunky/renderer/renderdump/GzipDumpFormat.java
- chunky/src/java/se/llbit/chunky/renderer/renderdump/HuffmanDumpFormat.java
- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
- chunky/src/java/se/llbit/imageformats/tiff/BasicIFD.java
- chunky/src/java/se/llbit/imageformats/tiff/CompressionType.java
- chunky/src/java/se/llbit/imageformats/tiff/FinalizableBFCOutputStream.java
- chunky/src/java/se/llbit/imageformats/tiff/IFDTag.java
- chunky/src/java/se/llbit/imageformats/tiff/ImageFileDirectory.java
- chunky/src/java/se/llbit/imageformats/tiff/TiffFileWriter.java
- chunky/src/java/se/llbit/math/Octree.java
- chunky/src/java/se/llbit/util/io/BufferedFileChannelOutputStream.java
- chunky/src/java/se/llbit/util/io/IsolatedOutputStream.java
- chunky/src/java/se/llbit/util/io/PositionalInputStream.java
- chunky/src/java/se/llbit/util/io/PositionalOutputStream.java
- chunky/src/java/se/llbit/util/io/RepositionableMeasurableDataOutput.java
- chunky/src/java/se/llbit/util/io/ZipExport.java
- refactored TIFF export (again)
- easier to extend (for #1651)
- added compression (part of #1651)
- should be faster too
> TIFF compression

- chunky/src/java/se/llbit/chunky/entity/PaintingEntity.java
- chunky/src/java/se/llbit/chunky/renderer/scene/SceneEntities.java
> Infer painting orientation from the position instead of using the angle from the entity tag.

- chunky/src/java/se/llbit/chunky/block/minecraft/Crafter.java
The top texture was flipped and rotated by 180° in some snapshot.
> Update crafter top texture orientation.

- chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
- chunky/src/java/se/llbit/chunky/block/minecraft/Vault.java
- chunky/src/java/se/llbit/chunky/model/minecraft/VaultModel.java
- chunky/src/java/se/llbit/chunky/resources/Texture.java
This adds the vault block from 24w05a.
> Add vault block.

- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
As discussed [on discord](https://discord.com/channels/541221265512464394/541221265512464397/1213953672308989992) and in #1692 this is a temporary fix and requires some changes to block providers to actually fix the underlying bug
> Ignore waterlogged air specifically (Temp fixes #1692)

- chunky/src/java/se/llbit/chunky/world/EmptyChunk.java
Fixes [this bug](https://discord.com/channels/541221265512464394/541221265512464397/1216065174230929489)
> Fix weird behaviour due to not clearing chunk data objects when loading empty chunks.

- chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
- chunky/src/java/se/llbit/chunky/block/legacy/blocks/LegacyBanner.java
- chunky/src/java/se/llbit/chunky/block/minecraft/Banner.java
- chunky/src/java/se/llbit/chunky/block/minecraft/HeavyCore.java
- chunky/src/java/se/llbit/chunky/block/minecraft/WallBanner.java
- chunky/src/java/se/llbit/chunky/entity/BannerDesign.java
- chunky/src/java/se/llbit/chunky/entity/StandingBanner.java
- chunky/src/java/se/llbit/chunky/model/minecraft/DecoratedPotModel.java
- chunky/src/java/se/llbit/chunky/model/minecraft/HeavyCoreModel.java
- chunky/src/java/se/llbit/chunky/resources/Texture.java
- chunky/src/java/se/llbit/chunky/world/BlockData.java
> Add 24w11a blocks and patterns.

- chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
- chunky/src/java/se/llbit/chunky/block/legacy/blocks/LegacySkull.java
- chunky/src/java/se/llbit/chunky/block/minecraft/Head.java
- chunky/src/java/se/llbit/chunky/block/minecraft/WallHead.java
- chunky/src/java/se/llbit/chunky/entity/PlayerEntity.java
- chunky/src/java/se/llbit/util/UuidUtil.java
- chunky/src/java/se/llbit/util/mojangapi/MojangApi.java
- chunky/src/test/se/llbit/chunky/block/SkullTextureTest.java
> Add support for new profile field in player head blocks and items.

- chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
- chunky/src/java/se/llbit/chunky/block/minecraft/TrialSpawner.java
- chunky/src/java/se/llbit/chunky/block/minecraft/Vault.java
- chunky/src/java/se/llbit/chunky/model/minecraft/TrialSpawnerModel.java
- chunky/src/java/se/llbit/chunky/model/minecraft/VaultModel.java
- chunky/src/java/se/llbit/chunky/resources/Texture.java
> Add trial spawner and ominous vault.

- chunky/src/java/se/llbit/chunky/entity/BannerDesign.java
- chunky/src/java/se/llbit/chunky/resources/ResourcePackBannerPatternLoader.java
- chunky/src/java/se/llbit/chunky/resources/ResourcePackBiomeLoader.java
- chunky/src/java/se/llbit/chunky/resources/ResourcePackLoader.java
- chunky/src/java/se/llbit/chunky/resources/ResourcePackPaintingLoader.java
Closes #1733
So here's [Blahaj](https://www.reddit.com/r/BLAHAJ/comments/1bn5o8c/minecraft_121_adds_custom_banner_patterns_so_i/):
> Add support for custom (data-driven) banner patterns

- chunky/src/java/se/llbit/chunky/block/UntintedLeaves.java
> Fix azalea leaves and cherry leaves ignoring material properties.

- chunky/src/java/se/llbit/chunky/entity/SporeBlossom.java
- chunky/src/java/se/llbit/chunky/model/minecraft/SporeBlossomModel.java
- chunky/src/java/se/llbit/chunky/world/ExtraMaterials.java
As mentioned in https://github.com/chunky-dev/chunky/issues/1745#issuecomment-2282235286
> Allow customizing the spore blossom material properties.

- chunky/src/java/se/llbit/chunky/resources/Texture.java
- chunky/src/java/se/llbit/chunky/resources/TexturePackLoader.java
> Fix ejecting and unlocking vault textures.

- chunky/src/java/se/llbit/chunky/block/minecraft/Head.java
> Fix loading custom player head textures in 1.21 worlds.

- chunky/src/java/se/llbit/chunky/block/minecraft/Cocoa.java
- chunky/src/java/se/llbit/chunky/model/minecraft/CocoaPlantModel.java
- chunky/src/java/se/llbit/chunky/model/minecraft/CocoaPlantModel119.java
Turns out the model for stage 2 was changed a while ago.
Fixes #1761
> Add new cocoa model

- launcher/src/se/llbit/chunky/launcher/ui/ChunkyLauncher.fxml
> Rename `...` buttons to `Browse`

- chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
> Store the biome blending radius in the scene file.

- chunky/src/java/se/llbit/chunky/model/minecraft/OrientableTrapdoorModel.java
> Fix some variants of trapdoors being rotated incorrectly.

- chunky/src/java/se/llbit/chunky/renderer/projection/StereographicProjector.java
- chunky/src/java/se/llbit/chunky/renderer/scene/Camera.java
> Fix FoV for stereographic projector and fix DoF support for stereographic and ODS projectors.

- chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
- chunky/src/java/se/llbit/chunky/block/minecraft/CreakingHeart.java
- chunky/src/java/se/llbit/chunky/block/minecraft/Wildflowers.java
- chunky/src/java/se/llbit/chunky/resources/Texture.java
- chunky/src/java/se/llbit/chunky/resources/TexturePackLoader.java
- chunky/src/java/se/llbit/chunky/resources/texturepack/TexturePath.java
Closes #1798 and adds full 25w02a support :tada:
> Add dormant creaking hearts and wildflowers.

- chunky/src/java/se/llbit/chunky/model/minecraft/OrientableTrapdoorModel.java
- chunky/src/java/se/llbit/chunky/model/minecraft/TrapdoorModel.java
> Fix trapdoor orientation in some cases.

- chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
- chunky/src/java/se/llbit/chunky/chunk/BlockPalette.java
- chunky/src/java/se/llbit/chunky/resources/Texture.java
- chunky/src/java/se/llbit/chunky/resources/TexturePackLoader.java
> Rename chain to iron_chain but keep compatibility with chain.

- chunky/src/java/se/llbit/chunky/resources/texturepack/CloudsTexture.java
- chunky/src/java/se/llbit/chunky/world/Clouds.java
> Fix cloud textures being overlaid when changing resource packs

- chunky/src/java/se/llbit/chunky/model/minecraft/GlassPaneModel.java
Fixes #892 by making sure that the model matches the ingame model. Also fixes glass panes not having any reflection in the transparent textured areas.
|Before|After|
|---|---|
|<img width="400" height="400" alt="image" src="https://github.com/user-attachments/assets/621b816b-99eb-43aa-b828-b66e969a547f" />|<img width="400" height="400" alt="image" src="https://github.com/user-attachments/assets/87785f4b-bef0-4b22-a144-e6ff05f9107f" />|
Look "inside" a glass pane:
> Fix glass pane model

- chunky/src/java/se/llbit/chunky/block/MinecraftBlockProvider.java
- chunky/src/java/se/llbit/chunky/block/minecraft/Observer.java
- chunky/src/java/se/llbit/chunky/block/minecraft/PressurePlate.java
- chunky/src/java/se/llbit/chunky/block/minecraft/Tripwire.java
- chunky/src/java/se/llbit/chunky/model/minecraft/ObserverModel.java
- chunky/src/java/se/llbit/chunky/model/minecraft/PressurePlateModel.java
- chunky/src/java/se/llbit/chunky/model/minecraft/TripwireModel.java
> Fix pressed pressure plates, observer and attached tripwire block models.
